import os
import shutil
import tempfile
from pathlib import Path
from typing import List, Optional

from curl_cffi import requests as cffi_requests
from playwright.sync_api import sync_playwright


BLOCK_MARKERS = (
    "403 error",
    "the request could not be satisfied",
    "request blocked",
    "generated by cloudfront",
    "access denied",
    "just a moment",
    "cf-chl",
    "captcha",
)

DEFAULT_HEADERS = {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
    "Accept-Language": "en-AU,en;q=0.9",
    "Cache-Control": "no-cache",
    "Pragma": "no-cache",
    "Upgrade-Insecure-Requests": "1",
    "User-Agent": (
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/136.0.0.0 Safari/537.36"
    ),
}

DEFAULT_IMPERSONATIONS = ("chrome136", "chrome131", "chrome124", "chrome120")


def get_macos_chrome_profile() -> Optional[str]:
    """Auto-locate standard Chrome User Data directory on macOS."""
    path = Path.home() / "Library/Application Support/Google/Chrome"
    if path.exists():
        return str(path)
    return None


def get_proxies() -> Optional[dict]:
    """Parse RACENET_PROXIES env var (e.g. 'http://user:pass@host:port')."""
    proxy_str = os.getenv("RACENET_PROXIES")
    if proxy_str:
        return {"http": proxy_str, "https": proxy_str}
    return None


class RacenetBlockedError(RuntimeError):
    pass


def detect_blocked_response(text: str, status_code: Optional[int] = None) -> bool:
    if status_code in {401, 403, 429, 503}:
        return True
    lowered = (text or "").lower()
    return any(marker in lowered for marker in BLOCK_MARKERS)


def extract_nuxt_from_html(html: str) -> Optional[dict]:
    with tempfile.NamedTemporaryFile("w", suffix=".html", delete=False, encoding="utf-8") as handle:
        handle.write(html)
        temp_path = Path(handle.name)

    try:
        with sync_playwright() as p:
            browser = p.chromium.launch(headless=True)
            page = browser.new_page()
            page.goto(temp_path.as_uri(), wait_until="domcontentloaded")
            nuxt_data = page.evaluate("() => window.__NUXT__ || null")
            browser.close()
        return nuxt_data
    finally:
        temp_path.unlink(missing_ok=True)


def fetch_nuxt_data(url: str, referer: Optional[str] = None, context_label: str = "Racenet") -> dict:
    blockers: List[str] = []

    curl_result = _try_curl(url, referer=referer, context_label=context_label)
    if curl_result["nuxt_data"] is not None:
        return curl_result["nuxt_data"]
    if curl_result["blocker"]:
        blockers.append(curl_result["blocker"])

    browser_result = _try_live_browser(url, referer=referer, context_label=context_label)
    if browser_result["nuxt_data"] is not None:
        return browser_result["nuxt_data"]
    if browser_result["blocker"]:
        blockers.append(browser_result["blocker"])

    raise RacenetBlockedError(_build_block_message(url, context_label, blockers))


def fetch_html(url: str, referer: Optional[str] = None, context_label: str = "Racenet") -> str:
    blockers: List[str] = []

    curl_result = _try_curl(url, referer=referer, context_label=context_label, decode_nuxt=False)
    if curl_result["html"]:
        return curl_result["html"]
    if curl_result["blocker"]:
        blockers.append(curl_result["blocker"])

    browser_result = _try_live_browser(url, referer=referer, context_label=context_label)
    if browser_result["html"]:
        return browser_result["html"]
    if browser_result["blocker"]:
        blockers.append(browser_result["blocker"])

    raise RacenetBlockedError(_build_block_message(url, context_label, blockers))


def _try_curl(url: str, referer: Optional[str], context_label: str, decode_nuxt: bool = True) -> dict:
    headers = dict(DEFAULT_HEADERS)
    if referer:
        headers["Referer"] = referer

    proxies = get_proxies()

    for impersonate in DEFAULT_IMPERSONATIONS:
        try:
            resp = cffi_requests.get(
                url, 
                impersonate=impersonate, 
                headers=headers, 
                proxies=proxies,
                timeout=30
            )
        except Exception as exc:
            blocker = f"{context_label}: curl_cffi {impersonate} exception: {exc}"
            print(f"⚠️ {blocker}", flush=True)
            continue

        if detect_blocked_response(resp.text, resp.status_code):
            blocker = f"{context_label}: curl_cffi {impersonate} blocked with HTTP {resp.status_code}"
            print(f"⚠️ {blocker}", flush=True)
            return {"nuxt_data": None, "html": None, "blocker": blocker}

        if not decode_nuxt:
            print(f"✅ {context_label}: curl_cffi {impersonate} fetched HTML ({len(resp.text)} bytes)", flush=True)
            return {"nuxt_data": None, "html": resp.text, "blocker": None}

        nuxt_data = extract_nuxt_from_html(resp.text)
        if nuxt_data:
            print(f"✅ {context_label}: curl_cffi {impersonate} fetched and decoded __NUXT__", flush=True)
            return {"nuxt_data": nuxt_data, "html": resp.text, "blocker": None}

        print(f"⚠️ {context_label}: curl_cffi {impersonate} returned HTML without __NUXT__", flush=True)

    return {"nuxt_data": None, "html": None, "blocker": None}


def _try_live_browser(url: str, referer: Optional[str], context_label: str) -> dict:
    headless = os.getenv("RACENET_HEADLESS", "1").lower() not in {"0", "false", "no"}
    timeout_ms = int(os.getenv("RACENET_TIMEOUT_MS", "90000"))
    channel = os.getenv("RACENET_BROWSER_CHANNEL") or _default_browser_channel()
    storage_state = os.getenv("RACENET_STORAGE_STATE")
    user_data_dir = os.getenv("RACENET_USER_DATA_DIR")
    profile_dir = os.getenv("RACENET_PROFILE_DIR", "Default")

    launch_args = [
        "--disable-blink-features=AutomationControlled",
        "--disable-dev-shm-usage",
        "--no-first-run",
        "--no-default-browser-check",
    ]
    if profile_dir and user_data_dir:
        launch_args.append(f"--profile-directory={profile_dir}")

    proxies = get_proxies()
    playwright_proxy = None
    if proxies and "http" in proxies:
        playwright_proxy = {"server": proxies["http"]}

    use_local = os.getenv("RACENET_USE_LOCAL_CHROME", "0") in {"1", "true", "yes"}
    if use_local and not user_data_dir:
        user_data_dir = get_macos_chrome_profile()
        if user_data_dir:
            print(f"ℹ️ Using local Chrome profile: {user_data_dir}")

    try:
        with sync_playwright() as p:
            if user_data_dir:
                context = p.chromium.launch_persistent_context(
                    user_data_dir=user_data_dir,
                    channel=channel,
                    headless=headless,
                    args=launch_args,
                    viewport={"width": 1440, "height": 1200},
                    locale="en-AU",
                    timezone_id="Australia/Sydney",
                    proxy=playwright_proxy,
                )
                browser = None
            else:
                browser = p.chromium.launch(
                    channel=channel,
                    headless=headless,
                    args=launch_args,
                    proxy=playwright_proxy,
                )
                context_kwargs = {
                    "user_agent": DEFAULT_HEADERS["User-Agent"],
                    "viewport": {"width": 1440, "height": 1200},
                    "locale": "en-AU",
                    "timezone_id": "Australia/Sydney",
                }
                if storage_state:
                    context_kwargs["storage_state"] = storage_state
                context = browser.new_context(**context_kwargs)

            page = context.new_page()
            page.add_init_script(
                """
                Object.defineProperty(navigator, 'webdriver', { get: () => undefined });
                Object.defineProperty(navigator, 'platform', { get: () => 'MacIntel' });
                Object.defineProperty(navigator, 'language', { get: () => 'en-AU' });
                Object.defineProperty(navigator, 'languages', { get: () => ['en-AU', 'en'] });
                """
            )
            if referer:
                page.set_extra_http_headers({"Referer": referer})

            response = page.goto(url, wait_until="domcontentloaded", timeout=timeout_ms)
            page.wait_for_timeout(4000)
            html = page.content()
            status_code = response.status if response else None

            if detect_blocked_response(html, status_code):
                blocker = f"{context_label}: Playwright live browser blocked with HTTP {status_code}"
                print(f"⚠️ {blocker}", flush=True)
                context.close()
                if browser:
                    browser.close()
                return {"nuxt_data": None, "html": None, "blocker": blocker}

            nuxt_data = page.evaluate("() => window.__NUXT__ || null")
            if not nuxt_data and html:
                nuxt_data = extract_nuxt_from_html(html)

            context.close()
            if browser:
                browser.close()

            if nuxt_data:
                print(f"✅ {context_label}: Playwright live browser decoded __NUXT__", flush=True)
                return {"nuxt_data": nuxt_data, "html": html, "blocker": None}

            if html:
                print(f"✅ {context_label}: Playwright live browser fetched HTML ({len(html)} bytes)", flush=True)
                return {"nuxt_data": None, "html": html, "blocker": None}
    except Exception as exc:
        blocker = f"{context_label}: Playwright live browser exception: {exc}"
        print(f"⚠️ {blocker}", flush=True)
        return {"nuxt_data": None, "html": None, "blocker": blocker}

    return {"nuxt_data": None, "html": None, "blocker": None}


def _default_browser_channel() -> Optional[str]:
    chrome_path = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
    if shutil.which("google-chrome") or Path(chrome_path).exists():
        return "chrome"
    return None


def _build_block_message(url: str, context_label: str, blockers: List[str]) -> str:
    bullet_lines = "\n".join(f"  - {item}" for item in blockers if item) or "  - No transport produced usable HTML."
    user_data_hint = os.path.expanduser("~/Library/Application Support/Google/Chrome")
    return (
        f"{context_label} fetch blocked for {url}\n"
        f"Observed transport failures:\n{bullet_lines}\n"
        "Suggested recovery:\n"
        "  1. Open Racenet once in regular Chrome on this Mac to establish a fresh human session.\n"
        "  2. Retry with `RACENET_USE_LOCAL_CHROME=1 RACENET_HEADLESS=0` (Ensures your real cookies are used).\n"
        "  3. If you have a Proxy, use `RACENET_PROXIES='http://host:port'`.\n"
        f"  4. If needed, retry with specific profile: `RACENET_USER_DATA_DIR='{user_data_hint}' RACENET_PROFILE_DIR='Default'`.\n"
        "  5. If Racenet still returns CloudFront 403, change your IP via Mobile Hotspot or VPN."
    )
