import json
import os

file_path = "/Users/imac/Library/CloudStorage/GoogleDrive-kelvin1761@gmail.com/我的雲端硬碟/Antigravity Shared/Antigravity/2026-04-14 Hawkesbury Race 1-7/Race_1_Logic.json"

with open(file_path, "r", encoding="utf-8") as f:
    data = json.load(f)

# Note: keep the nonce generated by au_orchestrator!
existing = data.get("horses", {}).get("2", {})
nonce = existing.get("_validation_nonce", "")

data["horses"]["2"].update({
    "_validation_nonce": nonce,
    "scenario_tags": ["大馬房", "試閘第一", "有實戰經驗", "2檔慳位", "上仗犯錯但上名"],
    "status_cycle": "初出後進步",
    "trend_summary": "上仗首次出賽走位不規矩但仍獲亞軍，其後試閘掄元，明顯見熟。",
    "analytical_breakdown": {
        "class_weight": "上仗出戰兩歲馬處女馬賽得亞軍，證明卡士足夠。負磅未知。",
        "engine_distance": "曾跑 900m 展現出速度，今仗增程 100m 預料亦能應付。估計為 Type A 帶前速型。",
        "track_surface_gait": "上仗於軟地(Soft)作賽得亞軍，場地性能已有證明。",
        "gear_intent": "無特別紀錄。",
        "jockey_trainer_combination": "Ciaron Maher 加 Tommy Berry，強勢騎練組合，必拼之選。"
    },
    "sectional_forensic": {
        "raw_L400": "N/A",
        "correction_factor": "無",
        "corrected_assessment": "欠缺詳細段速，但上仗出閘笨拙兼人馬角力仍能獲亞，實際能力比賽績更好。",
        "trend": ""
    },
    "eem_energy": {
        "last_run_position": "4th3→F2",
        "cumulative_drain": "0",
        "assessment": "上仗初出沿途搶口且外疊犯錯，浪費大量體力。今次排2檔，有助穩定走勢及慳力。"
    },
    "forgiveness_archive": {
        "factors": "起步笨拙、碰撞對手、搶口",
        "conclusion": "上仗初出稚嫩做錯大量細節仍得亞軍，絕對值得寬恕，今仗修正後威力倍增。"
    },
    "matrix": {
        "狀態與穩定性": {"score": "✅", "reasoning": "試閘掄元，狀態已提升及見熟"},
        "段速與引擎": {"score": "✅", "reasoning": "有實際速度展現"},
        "EEM與形勢": {"score": "✅", "reasoning": "2檔完美及極有利慳位"},
        "騎練訊號": {"score": "✅", "reasoning": "Ciaron Maher配Tommy Berry，誠意之選"},
        "級數與負重": {"score": "✅", "reasoning": "已有處女馬賽上名卡士"},
        "場地適性": {"score": "✅", "reasoning": "曾經在軟地上名"},
        "賽績線": {"score": "➖", "reasoning": "對手賽績線尚淺"},
        "裝備與距離": {"score": "➖", "reasoning": "首次增程至 1000m"}
    },
    "base_rating": "A-",
    "fine_tune": {
        "direction": "+",
        "trigger": "排2檔極佳、上仗犯錯寬恕、強配"
    },
    "override": {
        "rule": ""
    },
    "final_rating": "A",
    "core_logic": "上仗初出表現極為稚嫩，起步笨拙又搶口兼外疊，做錯大量細節下依然能夠跑獲亞軍，反映其純質素極高。賽後再安排試閘兼且勝出，可見練馬師 Ciaron Maher 已針對性修正其走規。今仗配上大師傅 Tommy Berry 兼排黃金 2 檔，出閘後可從容守好位，預期演出會比上仗有大幅度進步，屬今場爭勝主角。",
    "advantages": ["已有實戰上名經驗", "上仗犯錯下仍獲亞，實力強橫", "排2檔極有利", "名牌大馬房配一線騎師", "近期試閘第一"],
    "disadvantages": ["走規有隱憂（以往曾搶口）", "首次增程至 1000m"],
    "stability_index": "中高",
    "tactical_plan": {
        "start": "順利起步，跟隨 1 檔馬或埋欄帶放",
        "middle": "穩定走規，守在內欄前領/居中位置保持節奏",
        "straight": "移出望空交出衝刺"
    },
    "dual_track": {
        "triggered": False
    },
    "underhorse": {
        "triggered": False,
        "condition": "",
        "reason": ""
    }
})

with open(file_path, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Horse 2 logic filled.")
