#!/usr/bin/env python3
import os
os.environ.setdefault('PYTHONUTF8', '1')
"""
compile_analysis_template_hkjc.py — HKJC V4.2 Output Compiler (JSON -> Markdown)
========================================================================

Takes a given `Facts.md` and a matching `Race_X_Logic.json` (generated by the LLM),
and compiles them into a perfectly formatted V4.2 `Analysis.md`, applying the Calculator Pattern.

Usage:
  python3 .agents/skills/hkjc_racing/hkjc_wong_choi/scripts/compile_analysis_template_hkjc.py <Facts.md> <Logic.json> --output <Analysis.md>
"""

import sys
import json
import argparse
from pathlib import Path
import re

# We will reuse the core logic from generate_skeleton.py by importing it safely
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..', '..', 'scripts')))
import generate_skeleton as gs

# Import Dummy Prevention Layer
from racing_content_guard import assert_no_dummy_json, assert_no_dummy_text, quarantine_file
from validate_hkjc_matrix_confidence import validate_hkjc_matrix_confidence, apply_hkjc_matrix_caps

# ── V4.2: Import central schema constants ──
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from hkjc_schema import (
    HKJC_SCHEMA_VERSION,
    HKJC_MATRIX_SCHEMA,
    HKJC_MATRIX_EXPECTED_KEYS,
    HKJC_MATRIX_LABELS,
    HKJC_MATRIX_RENDER,
    HKJC_VALID_SCORES,
    normalize_matrix_keys,
)
from validate_hkjc_logic_schema import validate_logic_json

# ── ABCD 正規字母評級系統 (V4.2: S-tier only via ✅✅ promotion) ──────────
GRADE_ORDER = ['S+', 'S', 'S-', 'A+', 'A', 'A-', 'B+', 'B', 'B-', 'C+', 'C', 'C-', 'D+', 'D']

# V4.2: Canonical 7-dimension map only — no legacy aliases
MATRIX_TO_DIM = {k: k for k in HKJC_MATRIX_EXPECTED_KEYS}

DIMENSION_TYPES = {
    k: ('core' if v == 'core' else 'semi_core' if v == 'semi' else 'auxiliary')
    for k, v in HKJC_MATRIX_SCHEMA.items()
}

MATRIX_TEMPLATE_HINTS = {
    'stability': [
        '近6場/全賽績穩定性、名次波動、頭馬距離趨勢',
        '醫療事故作廢規則：有事故場次要先判斷可否納入',
    ],
    'sectional': [
        '引擎類型、L400/L600、全段速剖面 Δ、完成時間偏差',
        '距離證據 / Sire AWD / 首試路程風險已併入此維度',
    ],
    'race_shape': [
        '檔位統計、今日預計位置、近仗走位消耗/受阻',
        '此維度不以步速作主要評分理由；步速只保留於 race-level speed map / sectional / Top4 情境保險',
    ],
    'trainer_signal': [
        '練馬師部署、騎師配搭、近6場騎師歷史、換騎效應',
        '配備變動 / Gear Reset / 配備意圖已併入此維度',
    ],
    'horse_health': [
        '休賽日數、體重趨勢、健康掃描、場地轉換新鮮感',
        '健康事故需以復原證據判斷，不能直接當作永久扣分',
    ],
    'form_line': [
        'Facts.md 賽績線強度、對手後續表現、強組/弱組判定',
        '中組 / N/A 可視為不計入，避免硬塞 ✅/❌',
    ],
    'class_advantage': [
        '班次升降、評分趨勢、負磅甜蜜點、頂磅壓力',
        '負重/班次若已打 ✅，不可再用同一因素微調升級',
    ],
}


def _write_compile_blocked(output_path: str, message: str) -> None:
    out = Path(output_path)
    runtime_dir = out.parent / ".runtime"
    runtime_dir.mkdir(parents=True, exist_ok=True)
    names = {f"compile_blocked_{out.stem}.txt"}
    race_match = re.search(r"Race[_ ](\d+)", out.name)
    if race_match:
        names.add(f"compile_blocked_Race_{race_match.group(1)}.txt")
    for name in names:
        (runtime_dir / name).write_text(message, encoding="utf-8")

def _score_to_tick(score):
    """Convert a score to 5-tier tick: ✅✅/✅/➖/❌/❌❌."""
    if isinstance(score, str):
        s = score.strip()
        if s == '✅✅': return '✅✅'
        if '✅' in s: return '✅'
        if s == '❌❌': return '❌❌'
        if '❌' in s: return '❌'
        if '➖' in s or 'N/A' in s: return '➖'
        try:
            score = int(s)
        except ValueError:
            return '➖'
    if not isinstance(score, (int, float)):
        return '➖'
    if score >= 9:
        return '✅✅'
    elif score >= 7:
        return '✅'
    elif score >= 4:
        return '➖'
    elif score >= 2:
        return '❌'
    else:
        return '❌❌'

def _count_dimensions(dims: dict) -> dict:
    """Count dimensions with 5-tier display. ✅✅/❌❌ count as one pass/fail."""
    counts = {
        'core_strong': 0, 'core_neutral': 0, 'core_weak': 0,
        'semi_strong': 0, 'semi_neutral': 0, 'semi_weak': 0,
        'aux_strong': 0, 'aux_neutral': 0, 'aux_weak': 0,
        'total_strong': 0, 'total_weak': 0,
        'has_core_weak': False, 'has_core_double_weak': False,
        # Raw counts for display
        'core_dbl_strong': 0, 'semi_dbl_strong': 0, 'aux_dbl_strong': 0,
        'total_dbl_strong': 0, 'total_dbl_weak': 0,
        'core_single_strong': 0, 'semi_single_strong': 0, 'aux_single_strong': 0,
    }
    for dim_key, value in dims.items():
        v = value.strip() if isinstance(value, str) else str(value)
        if v in ('N/A', '不計入'):
            continue
        dim_type = DIMENSION_TYPES.get(dim_key, 'auxiliary')
        if v == '✅✅':
            counts['total_strong'] += 1
            counts['total_dbl_strong'] += 1
            if dim_type == 'core':
                counts['core_strong'] += 1
                counts['core_dbl_strong'] += 1
            elif dim_type == 'semi_core':
                counts['semi_strong'] += 1
                counts['semi_dbl_strong'] += 1
            else:
                counts['aux_strong'] += 1
                counts['aux_dbl_strong'] += 1
        elif v == '✅':
            counts['total_strong'] += 1
            if dim_type == 'core':
                counts['core_strong'] += 1
                counts['core_single_strong'] += 1
            elif dim_type == 'semi_core':
                counts['semi_strong'] += 1
                counts['semi_single_strong'] += 1
            else:
                counts['aux_strong'] += 1
                counts['aux_single_strong'] += 1
        elif v == '❌❌':
            counts['total_weak'] += 1
            counts['total_dbl_weak'] += 1
            if dim_type == 'core':
                counts['core_weak'] += 1
                counts['has_core_weak'] = True
                counts['has_core_double_weak'] = True
            elif dim_type == 'semi_core': counts['semi_weak'] += 1
            else: counts['aux_weak'] += 1
        elif v == '❌':
            counts['total_weak'] += 1
            if dim_type == 'core':
                counts['core_weak'] += 1
                counts['has_core_weak'] = True
            elif dim_type == 'semi_core': counts['semi_weak'] += 1
            else: counts['aux_weak'] += 1
        else:  # ➖ neutral
            if dim_type == 'core': counts['core_neutral'] += 1
            elif dim_type == 'semi_core': counts['semi_neutral'] += 1
            else: counts['aux_neutral'] += 1
    return counts

def _lookup_base_grade(c: dict) -> tuple:
    cs, ss, axs, tw = c['core_strong'], c['semi_strong'], c['aux_strong'], c['total_weak']
    # V4.2: full-house ordinary package is A+. S-tier is promotion-only.
    if cs >= 2 and ss >= 2 and axs >= 2 and tw == 0:
        return 'A+', f'2核心✅ + 2半核心✅ + {axs}輔助✅ + 0❌ (全滿)'
    if cs >= 2 and tw == 0:
        return 'A', f'2核心✅ + 0❌'
    if (cs >= 1 and ss >= 1 and tw == 0) or (cs >= 2 and tw <= 1):
        return 'A-', f'{cs}核心✅ + {ss}半核心✅ + {tw}❌'
    if cs >= 1 and tw <= 1:
        return 'A-', f'{cs}核心✅ + ❌≤1'
    if (cs >= 1 and tw == 2) or (ss >= 2 and tw <= 1):
        return 'B+', f'{cs}核心✅/{ss}半核心✅ + {tw}❌'
    if ss >= 1 and axs >= 2 and tw <= 2:
        return 'B', f'{ss}半核心✅ + {axs}輔助✅ + {tw}❌'
    if cs == 0 and ss == 0 and axs >= 3 and tw <= 2:
        return 'B-', f'0核心/半核心✅ + {axs}輔助✅'
    if tw == 3 and (cs >= 1 or ss >= 1):
        return 'C+', f'{tw}❌ + 有核心/半核心✅挽救'
    if tw == 3:
        return 'C', f'{tw}❌ + 無核心/半核心✅'
    if tw == 4:
        return 'C-', f'{tw}❌'
    ts = c['total_strong']
    if tw >= 5 and (cs >= 1 or ss >= 1 or axs >= 2):
        return 'D+', f'{tw}❌ + 有✅({ts})'
    if tw >= 5 or ts == 0:
        return 'D', f'{tw}❌ / 無✅'
    return 'C', f'未匹配 (core✅={cs}, semi✅={ss}, aux✅={axs}, ❌={tw})'

def _grade_idx(g: str) -> int:
    return GRADE_ORDER.index(g) if g in GRADE_ORDER else 99

def _apply_core_constraint(grade: str, counts: dict, dims: dict) -> tuple:
    if not counts['has_core_weak']:
        return grade, ''
    # ❌❌ in core = strict cap at B+, no exemption
    if counts.get('has_core_double_weak'):
        if _grade_idx(grade) < _grade_idx('B+'):
            return 'B+', '核心防護牆: 核心❌❌ → 封頂B+ (無豁免)'
        return grade, ''
    if _grade_idx(grade) < _grade_idx('B+'):
        return 'B+', '核心防護牆: 核心❌ → 封頂B+'
    return grade, ''

def _apply_micro(grade: str, direction: str) -> tuple:
    i = _grade_idx(grade)
    if direction in ('UP', '+', '升', '升一級') and i > 0:
        return GRADE_ORDER[i - 1], '升一級'
    elif direction in ('DOWN', '-', '降', '降一級') and i < len(GRADE_ORDER) - 1:
        return GRADE_ORDER[i + 1], '降一級'
    return grade, '無變動'


def _is_debut_runner_hkjc(h_logic: dict) -> bool:
    if h_logic.get('debut_runner', False) or h_logic.get('is_debut', False):
        return True
    if str(h_logic.get('career_tag', '')).upper() == 'DEBUT':
        return True
    try:
        return int(h_logic.get('career_race_starts', h_logic.get('hk_starts', 999))) == 0
    except (TypeError, ValueError):
        return False


def _apply_debut_cap_hkjc(grade: str, h_logic: dict) -> tuple:
    """Debut runners keep normal matrix arithmetic but cannot exceed A."""
    if not _is_debut_runner_hkjc(h_logic):
        return grade, ''
    if _grade_idx(grade) < _grade_idx('A'):
        return 'A', f'初出馬封頂: 7維矩陣照計，但 final rating 最高A ({grade}→A)'
    return grade, '初出馬封頂檢查: 未超過A'

def _apply_double_strong_promotion(grade: str, counts: dict) -> tuple:
    """Promote A+ to S-tier only via core/semi-core ✅✅ conviction evidence."""
    if grade != 'A+':
        return grade, ''
    steps = min(counts.get('core_dbl_strong', 0), 2)
    if counts.get('semi_dbl_strong', 0) >= 2:
        steps += 1
    if steps <= 0:
        return grade, ''
    promo_map = {1: 'S-', 2: 'S', 3: 'S+'}
    final = promo_map.get(min(steps, 3), 'S+')
    return final, f'✅✅推進+{min(steps, 3)} → {final}'

def _infer_ticks_from_rating(rating: str) -> dict:
    """OBSOLETE: Do not use synthetic tick inference."""
    raise ValueError("Synthetic matrix inference from final_rating is prohibited in production.")



def _build_synthetic_matrix_reasoning(h_logic: dict) -> dict:
    """Build reasoning strings from matrix reasoning when available, empty fallback otherwise."""
    matrix = h_logic.get('matrix', {})
    result = {}
    for key in ['stability', 'sectional', 'race_shape', 'trainer_signal', 'horse_health', 'form_line', 'class_advantage']:
        item = matrix.get(key, {})
        result[key] = item.get('reasoning', '') if isinstance(item, dict) else ''
    return result


def _extract_matrix_reason_parts(reasoning_raw: str) -> tuple:
    """Split V4.2 matrix reasoning into evidence bullets and final judgement."""
    evidence_parts = []
    verdict_text = ''
    for part in str(reasoning_raw or '').split('\n'):
        part = part.strip()
        if not part:
            continue
        if part.startswith('→ [判讀:') or part.startswith('→ [判讀：'):
            verdict_text = part.replace('→ [判讀:', '').replace('→ [判讀：', '').rstrip(']').strip()
            continue
        if part.startswith('[') and part.endswith(']'):
            evidence_parts.append(part[1:-1].strip())
        else:
            evidence_parts.append(part)
    if not verdict_text and evidence_parts:
        verdict_text = evidence_parts[-1]
        evidence_parts = evidence_parts[:-1]
    evidence_parts = [p for p in evidence_parts if p and p != verdict_text]
    return evidence_parts, verdict_text

def _zh_trackwork_status(value: str) -> str:
    return {'ok': '已提取', 'partial': '部分提取', 'missing': '缺資料', 'failed': '提取失敗'}.get(str(value), str(value))

def _zh_trackwork_category(value: str) -> str:
    return {
        'status_continuity': '狀態延續',
        'pattern_replay': '翻案復刻',
        'debut_pressure': '初出備戰',
        'insufficient_data': '資料不足',
    }.get(str(value), str(value))

def _zh_trackwork_trend(value: str) -> str:
    return {'improving': '加強中', 'stable': '穩定', 'easing': '放緩', 'interrupted': '中斷', 'unknown': '未明'}.get(str(value), str(value))

def _first_reason(matrix: dict, key: str) -> str:
    item = matrix.get(key, {}) if isinstance(matrix, dict) else {}
    if not isinstance(item, dict):
        return ''
    evidence, verdict = _extract_matrix_reason_parts(item.get('reasoning', ''))
    return verdict or (evidence[-1] if evidence else '')

def _matrix_score_value(matrix_data, key):
    item = (matrix_data or {}).get(key, {})
    return str(item.get('score', '') if isinstance(item, dict) else item)

def _race_shape_risk(matrix_data):
    score = _matrix_score_value(matrix_data, 'race_shape')
    if '❌' in score:
        return 2
    if '➖' in score or not score:
        return 1
    return 0

def _top2_sort_tuple(grade_i, counts, matrix_data, horse_num):
    h_num_sort = int(horse_num) if str(horse_num).isdigit() else 999
    return (
        grade_i,
        -counts.get('core_strong', 0),
        -counts.get('total_dbl_strong', 0),
        counts.get('total_weak', 0),
        counts.get('core_weak', 0),
        _race_shape_risk(matrix_data),
        -counts.get('total_strong', 0),
        h_num_sort,
    )


def _compute_letter_grade(m_data: dict, h_logic: dict) -> dict:
    """Compute the proper ABCD letter grade from matrix numeric scores.
    Falls back to final_rating-based inference when matrix is absent.
    """
    matrix_missing = not m_data  # no matrix at all

    if matrix_missing:
        h_name = h_logic.get('horse_name', 'unknown')
        raise ValueError(
            f"HKJC compile blocked: matrix missing for {h_name}. "
            "Do not infer matrix from final_rating."
        )

    # Check for missing dimensions
    required_dims = {
        "stability", "sectional", "race_shape", "trainer_signal",
        "horse_health", "form_line", "class_advantage"
    }
    missing = required_dims - set(m_data.keys())
    if missing:
        h_name = h_logic.get('horse_name', 'unknown')
        raise ValueError(f"HKJC compile blocked: missing matrix dimensions {sorted(missing)} for {h_name}")

    # Step 1: Convert numeric scores to ✅/❌/➖
    dims = {}
    for json_key, dim_key in MATRIX_TO_DIM.items():
        item = m_data.get(json_key, {})
        score = item.get('score', 5)
        dims[dim_key] = _score_to_tick(score)

    # Step 2: Count dimensions
    counts = _count_dimensions(dims)

    # Step 3: Check forgiveness bonus (5-tier aware)
    forg_item = m_data.get('forgiveness_bonus', {})
    forg_tick = _score_to_tick(forg_item.get('score', 0))
    if forg_tick == '✅✅':
        counts['aux_strong'] += 1
        counts['total_strong'] += 1
        counts['aux_dbl_strong'] += 1
        counts['total_dbl_strong'] += 1
    elif forg_tick == '✅':
        counts['aux_strong'] += 1
        counts['total_strong'] += 1

    # Step 4: Lookup base grade
    base_grade, base_rule = _lookup_base_grade(counts)

    # Step 5: Core constraint
    constrained_grade, constraint_note = _apply_core_constraint(base_grade, counts, dims)

    # Step 7: Micro adjustment
    ft = h_logic.get('fine_tune', {})
    ft_dir = ft.get('direction', '無') if isinstance(ft, dict) else str(ft)
    
    # Skip micro adjustment when matrix is missing (grade already exact)
    adjusted_grade, micro_note = _apply_micro(constrained_grade, ft_dir.upper())
    promoted_grade, promo_note = _apply_double_strong_promotion(adjusted_grade, counts)
    if promo_note:
        adjusted_grade = promoted_grade
        micro_note = f'{micro_note}; {promo_note}'

    capped_grade, debut_note = _apply_debut_cap_hkjc(adjusted_grade, h_logic)
    if debut_note:
        adjusted_grade = capped_grade
        micro_note = f'{micro_note}; {debut_note}'
    capped_grade, cap_notes = apply_hkjc_matrix_caps(adjusted_grade, h_logic)
    if cap_notes:
        adjusted_grade = capped_grade
        micro_note = f"{micro_note}; {'; '.join(cap_notes)}"

    return {
        'dims': dims,
        'counts': counts,
        'base_grade': base_grade,
        'base_rule': base_rule,
        'constraint_note': constraint_note,
        'adjusted_grade': adjusted_grade,
        'micro_note': micro_note,
        'final_grade': adjusted_grade,
        'matrix_missing': matrix_missing,
        'cap_notes': cap_notes if 'cap_notes' in locals() else [],
    }

def build_hkjc_panorama_compiled(json_data, facts_text, facts_horses=None):
    v = json_data.get('race_analysis', {})
    sm = v.get('speed_map', {})
    
    # Build num→name lookup
    num_to_name = {}
    if facts_horses:
        num_to_name = {str(h['num']): h['name'] for h in facts_horses}
    
    def _map_names(num_list):
        """Convert ['7','8'] or '7, 8' or ['7, 8'] to '[7] 電訊巴打, [8] 穿甲金鷹'."""
        if isinstance(num_list, str):
            num_list = [x.strip() for x in num_list.replace('、', ',').split(',')]
        elif isinstance(num_list, list):
            flat = []
            for item in num_list:
                if isinstance(item, str) and ',' in item:
                    flat.extend([x.strip() for x in item.split(',')])
                elif isinstance(item, str) and '、' in item:
                    flat.extend([x.strip() for x in item.split('、')])
                else:
                    flat.append(str(item).strip())
            num_list = flat
            
        parts = []
        for n in num_list:
            if not n: continue
            name = num_to_name.get(str(n), '')
            parts.append(f'[{n}] {name}' if name else str(n))
        return ', '.join(parts) or '[未指定]'
    
    venue = "[馬場]"
    dist = "[路程]"
    cls_grade = "[班次]"
    
    m = re.search(r'場地:\s*([^|]*?)\s*\|\s*距離:\s*([^|]*?)\s*\|\s*班次:\s*([^\n]+)', facts_text)
    if m:
        v_val = m.group(1).strip()
        if v_val: venue = v_val
        d_val = m.group(2).strip()
        if d_val and d_val != "0m": dist = d_val
        c_val = m.group(3).strip()
        if c_val: cls_grade = c_val
        
    race_type = "`[全天候跑道 (AWT)]`" if "AWT" in venue or "泥地" in facts_text else "`[草地]`"

    pace = sm.get('predicted_pace', '[未預測]')
    leaders = _map_names(sm.get('leaders', []))
    on_pace = _map_names(sm.get('on_pace', []))
    mid = _map_names(sm.get('mid_pack', []))
    closers = _map_names(sm.get('closers', []))
    
    weather_going = "詳見情報"
    bias = sm.get('track_bias', '[未預測]')
    if not bias: bias = '[未預測]'
    tactical_nodes = sm.get('tactical_nodes', '[未提供]')
    if not tactical_nodes: tactical_nodes = '[未提供]'
    collapse = sm.get('collapse_point', '[未提供]')
    if not collapse: collapse = '[未提供]'
    
    pace_details = (
        f"- **預計步速:** {pace}\n"
        f"- **跑道偏差:** {bias}\n"
        f"- **戰術節點:** {tactical_nodes}\n"
        f"- **崩潰點:** {collapse}"
    )
    
    return f"""## [第一部分] 🗺️ 戰場全景

| 項目 | 內容 |
|:---|:---|
| 賽事格局 | {cls_grade} / {dist} / {race_type.replace('`[','').replace(']`','')} / {venue} |
| **賽事類型** | **{race_type}** |
| 天氣 / 場地 | {weather_going} |
| 跑道偏差 | {bias} |
| 步速預測 | {pace} |

**📍 Speed Map (速度地圖):**
- 領放群: {leaders}
- 前中段: {on_pace}
- 中後段: {mid}
- 後上群: {closers}

**🏃 步速瀑布推演 (Step 0 結論):**
{pace_details}
"""

def _render_dimension_data(lines, dim_key, pd, h_fact, h_logic):
    """V10: Render factual data lines for a dimension from Python-guaranteed _data{} dict.
    
    This ensures 100% consistent data depth across all horses, regardless of what
    the LLM writes in the reasoning field. The LLM only needs to provide the verdict.
    """
    if dim_key == 'stability':
        lines.append(f"  - Resource Check: 05_forensic_analysis.md / 穩定性+醫療事故作廢規則")
        lines.append(f"  - 近6場數據(含班次): {pd.get('recent_6_detail', 'N/A')}")
        lines.append(f"  - 季內={pd.get('season_stats_line', 'N/A')}, 頭馬距離趨勢={pd.get('margin_trend', 'N/A')}")
        lines.append(f"  - 生涯標記: {pd.get('career_tag', 'N/A')}; 香港正式賽事場次={pd.get('hk_starts', 'N/A')}; {pd.get('career_stage_label', '標準馬')}")
        lines.append(f"  - 晨操 digest: {pd.get('trackwork_digest', 'N/A')}")
        lines.append(f"  - 晨操判讀規則: {pd.get('trackwork_instruction', '正式賽績與晨操 50/50 判讀')}")
        lines.append(f"  - 🏥 健康掃描(作廢用): {pd.get('medical_flags', 'N/A')}")
        lines.append(f"  - 📎 必讀: 05_forensic_analysis.md (穩定性計算 + 醫療事故自動作廢規則)")

    elif dim_key == 'sectional':
        lines.append(f"  - Resource Check: 03_engine_pace_context.md + 04_engine_corrections.md + 05_forensic_analysis.md / 引擎+段速修正+法醫作廢")
        lines.append(f"  - 引擎(速度分佈): {pd.get('engine_type', 'N/A')} | 最佳{pd.get('best_distance', 'N/A')}")
        lines.append(f"  - 上仗L400={pd.get('raw_l400', 'N/A')}, L400趨勢={pd.get('l400_trend', 'N/A')}, 能量趨勢={pd.get('energy_trend', 'N/A')}")
        ft_block = pd.get('finish_time_block', '')
        if ft_block:
            lines.append(f"  - 📉 完成時間偏差: {ft_block}")
        ft_adj = pd.get('finish_time_adj', '')
        ft_adj_level = pd.get('finish_time_adj_level', '')
        if ft_adj:
            lines.append(f"  - 🔧 步速修正偏差: {ft_adj} | 修正水平: {ft_adj_level if ft_adj_level else 'N/A'}")
        lines.append(f"  - 🏥 健康掃描(作廢用): {pd.get('medical_flags', 'N/A')}")
        lines.append(f"  - 📎 必讀: 03_engine_pace_context.md + 04_engine_corrections.md + 05_forensic_analysis.md")

    elif dim_key == 'race_shape':
        lines.append(f"  - Resource Check: 05_forensic_analysis.md / 檔位數據 + 今日預計走位 + 近3-5仗走位消耗")
        lines.append(f"  - 近3-5仗走位窗口: {pd.get('position_window', 'N/A')}")
        lines.append(f"  - 檔位={h_fact.get('barrier', 'N/A')} ({pd.get('draw_verdict', 'N/A')}), 跑法={pd.get('running_style', 'N/A')}, 走位PI={pd.get('position_pi', 'N/A')}")
        lines.append(f"  - 🔄 檔位-走位匹配度: {pd.get('draw_position_fit', 'N/A')}")
        lines.append(f"  - 🏟️ 場地偏差: {pd.get('track_bias', 'N/A')}")
        draw_table = pd.get('full_draw_table', '')
        if draw_table:
            lines.append(f"  - 📊 {draw_table}")
        lines.append(f"  - 📎 必讀: 05_forensic_analysis.md")

    elif dim_key == 'trainer_signal':
        lines.append(f"  - Resource Check: 07b_trainer_signals.md + 07c_jockey_profiles.md / 騎練部署+人馬配搭")
        lines.append(f"  - 騎師={pd.get('jockey_name', 'N/A')}, 練馬師={pd.get('trainer_name', 'N/A')}")
        lines.append(f"  - 配備變動: {pd.get('gear_change', 'N/A')}")
        lines.append(f"  - 晨操部署: {pd.get('trackwork_trainer', 'N/A')}")
        jc_block = pd.get('jockey_combo_block', '')
        if jc_block:
            lines.append(f"  - 🏇 人馬組合統計: {jc_block}")
        lines.append(f"  - 📎 必讀: 07b_trainer_signals.md + 07c_jockey_profiles.md")

    elif dim_key == 'horse_health':
        lines.append(f"  - Resource Check: 05_forensic_analysis.md + 10a/10b/10c_track_*.md / 健康+場地新鮮感")
        lines.append(f"  - 休賽: {pd.get('days_since_last', 'N/A')}日, 體重趨勢: {pd.get('weight_trend', 'N/A')}")
        lines.append(f"  - 晨操健康: {pd.get('trackwork_health', 'N/A')}")
        lines.append(f"  - 🏥 健康掃描: {pd.get('medical_flags', 'N/A')}")
        lines.append(f"  - 📎 健康評估規則: 有健康事故+復原證据=已復原(➖/✅); 有事故+未復原=風險(❌); 無事故=正常(✅)")

    elif dim_key == 'form_line':
        lines.append(f"  - Resource Check: Facts.md 賽績線表格 + 05_forensic_analysis.md / 對手後續強度")
        lines.append(f"  - 賽績線強度={pd.get('formline_strength', 'N/A')}")
        lines.append(f"  - 上仗名次={pd.get('last_finish', 'N/A')}, 距離差={pd.get('last_margin', 'N/A')}")
        # Also inject Facts formline data if available
        if h_fact.get('formline') and '(無往績記錄)' not in h_fact.get('formline', ''):
            fl_clean = h_fact['formline'].replace('🔗 **賽績線 (近 5 場正式賽事，官方追蹤):**', '').replace('🔗 賽績線 (近 5 場正式賽事，官方追蹤):', '').strip()
            lines.append(f"  - **Facts賽績線資料:** {fl_clean}")
        elif h_logic.get('is_debut') or h_logic.get('debut_runner'):
            lines.append("  - **Facts賽績線資料:** 初出馬無正式賽績線，N/A 不計入矩陣。")
        lines.append(f"  - 📎 必讀: 05_forensic_analysis.md (賽績線)")

    elif dim_key == 'class_advantage':
        lines.append(f"  - Resource Check: 06_rating_engine.md / 級數優勢+負重互斥規則")
        lines.append(f"  - {pd.get('total_starts', 'N/A')}戰{pd.get('total_wins', 'N/A')}勝, 評分趨勢={pd.get('rating_trend', 'N/A')}, 負磅={pd.get('weight_carried', 'N/A')}")
        lines.append(f"  - 場地轉換: {pd.get('venue_transfer', '未知')}")
        lines.append(f"  - 📎 必讀: 06_rating_engine.md + 場地模組 10a/10b/10c")


def generate_hkjc_horse_compiled(h_fact, h_logic):
    lines = []
    jockey_str = h_fact['jockey'] if h_fact['jockey'] else 'Unknown'
    trainer_str = h_fact['trainer'] if h_fact['trainer'] else 'Unknown'
    weight_str = str(h_fact['weight']) if h_fact['weight'] else 'Unknown'

    # rating/final_rating will be computed by ABCD grade system below (Section 9-10)
    rating = '[待計算]'
    final_rating = '[待計算]'
    # Build advantages/disadvantages — V4.2: matrix-only, no analytical_breakdown fallback
    disadvantages = h_logic.get('disadvantages', h_logic.get('risk_level', '見評級矩陣'))
    advantages = h_logic.get('advantages', h_logic.get('competitive_advantage', '見評級矩陣'))
    fgv = h_logic.get('scenario_tags', '無')

    # ── 1. 馬匹標題 + 情境標記 ──────────────────────────────────────────
    lines.append(f"**【No.{h_fact['num']}】 {h_fact['name']}** | 騎師:{jockey_str} | 練馬師:{trainer_str} | 負磅:{weight_str} | 檔位:{h_fact['barrier']}")
    lines.append(f"**📌 情境標記:** `{fgv}`\n")

    # ── 2. 近績解構 (排位表事實錨點) ────────────────────────────────────
    lines.append('#### ⏱️ 近績解構')
    if h_fact.get('summary') and '(無往績記錄)' not in h_fact.get('summary', ''):
        summary_clean = h_fact['summary'].replace('📌 **賽績總結:**', '').replace('📌 賽績總結:', '').strip()
        lines.append(summary_clean)
    else:
        lines.append('- **(無往績記錄)**')
    lines.append('')

    # ── 3. 完整賽績檔案 (Facts 注入，僅一次) ────────────────────────────
    if h_fact.get('table') and '(無往績記錄)' not in h_fact.get('table', ''):
        lines.append('#### 📋 完整賽績與寬恕檔案 (包含 Step 12 判斷)\n')
        race_forgiveness = h_logic.get('race_forgiveness', [])
        lines.append(gs._truncate_table(h_fact['table']) + '\n')
        lines.append(f"- **逐場寬恕判定:** `{json.dumps(race_forgiveness, ensure_ascii=False)}`\n")
    else:
        lines.append('#### 📋 完整賽績檔案: (無往績記錄)\n')

    trackwork = h_logic.get('trackwork', {})
    if isinstance(trackwork, dict) and trackwork:
        tw_digest = trackwork.get('stability_digest', {})
        tw_load = tw_digest.get('workout_load_21d', {}) if isinstance(tw_digest, dict) else {}
        tw_summary = trackwork.get('summary', {}) if isinstance(trackwork.get('summary', {}), dict) else {}
        role_counts = tw_summary.get('rider_role_counts', {})
        role_text = '、'.join(f"{k}{v}次" for k, v in role_counts.items()) if role_counts else '未標明'
        lines.append('#### 🏇 晨操摘要 (Trackwork Digest)\n')
        lines.append(
            f"- **狀態:** `{_zh_trackwork_status(trackwork.get('status', 'missing'))}` | "
            f"**分類:** `{_zh_trackwork_category(tw_digest.get('career_category', 'insufficient_data'))}` | "
            f"**趨勢:** `{_zh_trackwork_trend(tw_digest.get('workout_intensity_trend', 'unknown'))}`"
        )
        lines.append(
            f"- **近{tw_digest.get('window_days', 21)}日操練:** "
            f"快操 {tw_load.get('gallops', 0)} / 試閘 {tw_load.get('trials', 0)} / "
            f"踱步 {tw_load.get('trotting', 0)} / 游水 {tw_load.get('swimming', 0)} / "
            f"空白日 {tw_load.get('blank_days', 0)}"
        )
        lines.append(
            f"- **Digest分:** 維持分 `{tw_digest.get('maintenance_score')}` | "
            f"備戰分 `{tw_digest.get('readiness_score')}` | "
            f"復刻分 `{tw_digest.get('pattern_replay_score')}`"
        )
        lines.append(f"- **操練者身份:** {role_text}")
        lines.append(f"- **Flags:** 正面 `{', '.join(tw_digest.get('stability_positive_flags', []) or []) or '無'}` | 風險 `{', '.join(tw_digest.get('stability_risk_flags', []) or []) or '無'}`\n")
        if h_logic.get('is_debut') or h_logic.get('debut_runner'):
            lines.append("- **初出路由:** 晨操強訊號可導入騎練訊號 / 段速替代證據；穩定性可按備戰連貫度判斷，賽績線不可當正式賽績。\n")

    # ── 4+8+9. 評級矩陣 (V4.2 — 7維度 matrix-only) ────────────────

    # ── V4.2 Unified 7-Dimension Matrix ──
    m_data = h_logic.get('matrix', {})

    grade_result = _compute_letter_grade(m_data, h_logic)
    gr_dims = grade_result['dims']
    gr_counts = grade_result['counts']

    # V4.2: Use central schema for labels and ordering
    m_schema = {k: (zh, tier) for k, zh, tier in HKJC_MATRIX_RENDER}
    dim_order = [k for k, _, _ in HKJC_MATRIX_RENDER]

    lines.append('#### 🧮 評級矩陣 (7-Dimension Matrix)')
    lines.append('> 形勢與走位：只評檔位 / 今日位置 / 走位成本 / 交通風險。')
    lines.append('')

    rendered_keys = set()
    pd = h_logic.get('_data', {})  # V10: Python-guaranteed data dict
    has_pdata = bool(pd)  # True if new format with _data, False for legacy

    for canonical_key in dim_order:
        v = m_data.get(canonical_key)
        if not v or not isinstance(v, dict):
            continue
        rendered_keys.add(canonical_key)
        label, tier = m_schema.get(canonical_key, (canonical_key, '?'))
        score = v.get('score', '?')
        confidence = v.get('confidence', 'Unknown')
        trigger_rule = v.get('trigger_rule', '')
        trigger_evidence = v.get('trigger_evidence', [])
        disqualifiers = v.get('disqualifiers', [])
        reasoning_raw = v.get('reasoning', '')

        lines.append(f'##### {label} [{tier}]: `{score}` | Confidence: `{confidence}` | Rule: `{trigger_rule}`')
        lines.append('- Trigger evidence:')
        if isinstance(trigger_evidence, list) and trigger_evidence:
            for ev in trigger_evidence:
                lines.append(f'  - {ev}')
        else:
            lines.append('  - 無')
        disq_text = '、'.join(map(str, disqualifiers)) if isinstance(disqualifiers, list) and disqualifiers else '無'
        lines.append(f'- Disqualifiers: {disq_text}')

        hints = MATRIX_TEMPLATE_HINTS.get(canonical_key, [])
        if hints:
            lines.append(f"  - 🧭 **V4.2檢查點:** {'；'.join(hints)}")

        # ── V10: Python renders data from _data{}, LLM only provides verdict ──
        if has_pdata:
            _render_dimension_data(lines, canonical_key, pd, h_fact, h_logic)
            # Extract only the verdict from LLM reasoning
            _, verdict_text = _extract_matrix_reason_parts(reasoning_raw)
            if verdict_text and verdict_text != 'FILL':
                lines.append(f'  - 📊 **判讀:** `{verdict_text}`')
        else:
            # Legacy fallback: parse reasoning string for both data + verdict
            if canonical_key == 'form_line':
                if h_fact.get('formline') and '(無往績記錄)' not in h_fact.get('formline', ''):
                    fl_clean = h_fact['formline'].replace('🔗 **賽績線 (近 5 場正式賽事，官方追蹤):**', '').replace('🔗 賽績線 (近 5 場正式賽事，官方追蹤):', '').strip()
                    lines.append(f"  - **Facts賽績線資料:** {fl_clean}")
                elif h_logic.get('is_debut') or h_logic.get('debut_runner'):
                    lines.append("  - **Facts賽績線資料:** 初出馬無正式賽績線，N/A 不計入矩陣。")
                else:
                    lines.append("  - **Facts賽績線資料:** 無往績記錄或未能提取。")
            evidence_parts, verdict_text = _extract_matrix_reason_parts(reasoning_raw)
            for part in evidence_parts:
                lines.append(f'  - {part}')
            if verdict_text:
                lines.append(f'  - 📊 **判讀:** `{verdict_text}`')
        lines.append('')

    # Render any unrecognized keys
    for k, v in m_data.items():
        ck = k
        if ck in rendered_keys or not isinstance(v, dict):
            continue
        score = v.get('score', '?')
        reason = v.get('reasoning', '')
        lines.append(f'##### {k}: `{score}`')
        if reason:
            lines.append(f'  - {reason}')
        lines.append('')

    # Forgiveness bonus
    forgive_item = m_data.get('forgiveness_bonus', {})
    if isinstance(forgive_item, dict) and forgive_item:
        forg_score = forgive_item.get('score', '[-]')
        forg_reason = forgive_item.get('reasoning', forgive_item.get('reason', '[無提供]'))
        forg_tick = _score_to_tick(forg_score)
        lines.append(f"\n- 寬恕加分: `{forg_tick}` | 理據: `{forg_reason}`\n")

    # ── 10. 矩陣算術 + 14.2 基礎評級 (ABCD 正規字母制) ────────────────
    cw = '有' if gr_counts['has_core_weak'] else '無'
    cdw = '有' if gr_counts.get('has_core_double_weak') else '無'
    lines.append(f"**🔢 矩陣算術:** 核心✅✅={gr_counts.get('core_dbl_strong',0)} | 核心✅={gr_counts.get('core_single_strong',0)} | 半核心✅✅={gr_counts.get('semi_dbl_strong',0)} | 半核心✅={gr_counts.get('semi_single_strong',0)} | 輔助✅✅={gr_counts.get('aux_dbl_strong',0)} | 輔助✅={gr_counts.get('aux_single_strong',0)} | 總❌={gr_counts['total_weak']} | 總❌❌={gr_counts.get('total_dbl_weak',0)} | 核心❌={cw} | 核心❌❌={cdw} → 查表命中行={grade_result['base_grade']}")
    lines.append(f"**14.2 基礎評級:** `{grade_result['base_grade']}` | **規則**: `{grade_result['base_rule']}`")
    if grade_result['constraint_note']:
        lines.append(f"**核心防護牆:** `{grade_result['constraint_note']}`")

    # ── 11. 14.2B 微調 ────────────────────────────────────────────────────
    ft = h_logic.get('fine_tune', {})
    ft_dir = ft.get('direction', '無') if isinstance(ft, dict) else str(ft)
    ft_trig = ft.get('trigger', '無') if isinstance(ft, dict) else '無'
    ft_channel_a = ft.get('channel_a', ft_dir) if isinstance(ft, dict) else ft_dir
    ft_channel_b = ft.get('channel_b', '無') if isinstance(ft, dict) else '無'
    lines.append(f"**14.2B 微調:** 通道A: `{ft_channel_a}` | 通道B(SYN/CON): `{ft_channel_b}` | ({grade_result['micro_note']}) | 觸發: `{ft_trig}`")

    # ── 11.5. 🔗 互動矩陣 [ANCHOR-互動矩陣] ──────────────────────────────────────
    im = h_logic.get('interaction_matrix', {})
    im_syn = im.get('SYN', im.get('syn', '無')) if isinstance(im, dict) else '無'
    im_con = im.get('CON', im.get('con', '無')) if isinstance(im, dict) else '無'
    im_contra = im.get('CONTRA', im.get('contra', '無')) if isinstance(im, dict) else '無'
    lines.append(f"**🔗 互動矩陣 [ANCHOR-互動矩陣]:** SYN: `{im_syn}` | CON: `{im_con}` | CONTRA: `{im_contra}`")

    # ── 12. 14.3 覆蓋 ────────────────────────────────────────────────────
    ovr = h_logic.get('override', {})
    ovr_rule = ovr.get('rule', '無') if isinstance(ovr, dict) else str(ovr)
    lines.append(f"**14.3 覆蓋:** `{ovr_rule}`\n")

    # Update rating/final_rating to use the computed ABCD letter grade
    rating = grade_result['base_grade']
    final_rating = grade_result['final_grade']

    # V4.2: Legacy 8D matrix block removed — single 7D render above

    # ── 14. 結論與評語 ───────────────────────────────────────────────────
    lines.append('#### 💡 結論與評語 (Conclusion & Analyst View)')
    lines.extend([
        f"> - **核心邏輯:** {h_logic.get('core_logic', '[缺失核心邏輯]')}",
        f"> - **最大競爭優勢:** {advantages}",
        f"> - **最大失敗風險:** {disadvantages}\n"
    ])

    # ── 14. 法醫級推演錨點 (已移除 — V10) ─────────────────────────────────

    # ── 15. 最終評級 ─────────────────────────────────────────────────────
    lines.append(f"**⭐ 最終評級:** `{final_rating}`\n")

    # ── 16. 冷門馬訊號 ───────────────────────────────────────────────────
    uh = h_logic.get('underhorse', {})
    uh_trig = "觸發" if uh.get('triggered') else "未觸發"
    lines.append(f"🐴⚡ **冷門馬訊號 (Underhorse Signal):** `{uh_trig}`")
    if uh_trig == "觸發":
        lines.append(f"- **受惠條件:** {uh.get('condition', '')}")
        lines.append(f"- **理由:** {uh.get('reason', '')}")

    return '\n'.join(lines)


def build_hkjc_verdict_compiled(json_data, facts_horses):
    v = json_data.get('race_analysis', {}).get('verdict', {})
    horse_names = {h['num']: h['name'] for h in facts_horses}
    horses_logic = json_data.get('horses', {})
    race_info = json_data.get('race_analysis', {})
    speed_map = race_info.get('speed_map', {})

    lines = []
    lines.append('#### [第三部分] 最終預測 (The Verdict)\n')
    track_scenario = v.get('track_scenario') or f"{speed_map.get('predicted_pace', 'Moderate')} pace；{speed_map.get('track_bias', '自動形勢圖保守判斷')}"
    confidence = v.get('confidence') or '[中]'
    key_variables = v.get('key_variables') or '步速是否如預期、檔位形勢、熱門馬能否避開早段消耗'
    lines.append(f"- **跑道形勢:** {track_scenario}")
    lines.append(f"- **信心指數:** `{confidence}`")
    lines.append(f"- **關鍵變數:** {key_variables}\n")

    lines.append('**🏆 Top 4 位置精選**\n')

    # ── AUTO-COMPUTE Top 4 from ALL horses' grades (ignore LLM's manual picks) ──
    # Build a lookup of LLM's original reason/risk keyed by horse_num
    llm_picks = {}
    for item in v.get('top4', []):
        h_num = str(item.get('horse_num', item.get('horse_number', '')))
        llm_picks[h_num] = item

    # Compute grade for every horse
    all_graded = []
    for h_num_str, h_obj in horses_logic.items():
        m_data = h_obj.get('matrix', {})
        gr_res = _compute_letter_grade(m_data, h_obj)
        grade = h_obj.get("final_rating") or gr_res['final_grade']
        grade_i = _grade_idx(grade)
        counts = gr_res.get('counts', {})
        tick_count = counts.get('total_strong', 0)
        double_ticks = counts.get('total_dbl_strong', 0)
        sort_key = _top2_sort_tuple(grade_i, counts, m_data, h_num_str)
        all_graded.append((h_num_str, grade, sort_key, tick_count, double_ticks, gr_res))

    # Sort by grade, then core ability, conviction, risk profile, and horse number.
    all_graded.sort(key=lambda x: x[2])

    # Take top 4
    t4_auto = all_graded[:4]

    labels = ['🥇 **第一選**', '🥈 **第二選**', '🥉 **第三選**', '🏅 **第四選**']
    csv_rows = []
    race_num = race_info.get('race_number', '?')
    race_class = race_info.get('race_class', '?')
    race_dist = race_info.get('distance', '?')

    top_nums = []  # track for Top 2 confidence section
    for i, label in enumerate(labels):
        if i < len(t4_auto):
            h_num_str, grade, sort_key, tick_count, double_ticks, gr_res = t4_auto[i]
            h_num_int = int(h_num_str) if h_num_str.isdigit() else 0
            h_name = horse_names.get(h_num_int, '')
            h_obj = horses_logic.get(h_num_str, {})
            m_data = h_obj.get('matrix', {})
            # core_check: count ✅ ticks from computed dims (works with & without matrix)
            _gr_for_check = _compute_letter_grade(m_data, h_obj)
            _dims_for_check = _gr_for_check.get('dims', {})
            core_check = tick_count
            jockey = next((hf['jockey'] for hf in facts_horses if str(hf['num']) == h_num_str), '')
            trainer = next((hf['trainer'] for hf in facts_horses if str(hf['num']) == h_num_str), '')

            # Use LLM reason/risk if available; accept both 'rationale' and 'reason' keys
            if h_num_str in llm_picks:
                pick = llm_picks[h_num_str]
                reason = pick.get('rationale', pick.get('reason', ''))
                risk_raw = pick.get('risk', '')
                # risk may be a list or string
                if isinstance(risk_raw, list):
                    risk = ' / '.join(str(r) for r in risk_raw)
                else:
                    risk = str(risk_raw) if risk_raw else ''
                # fallback if still empty
                if not reason:
                    reason = h_obj.get('core_logic', h_obj.get('advantages', '[見核心邏輯]'))
                if not risk:
                    risk = h_obj.get('disadvantages', h_obj.get('risk_level', '[見分析]'))
            else:
                reason = h_obj.get('core_logic', h_obj.get('advantages', h_obj.get('competitive_advantage', '[自動選入]')))
                risk_raw = h_obj.get('disadvantages', h_obj.get('risk_level', '[見分析]'))
                if isinstance(risk_raw, list):
                    risk = ' / '.join(str(r) for r in risk_raw)
                else:
                    risk = str(risk_raw) if risk_raw else '[見分析]'

            lines.extend([
                label,
                f"- **馬號及馬名:** [{h_num_str}] {h_name}",
                f"- **評級與✅數量:** `[{grade}]` | ✅ {core_check}",
                f"- **核心理據:** {reason}",
                f"- **最大風險:** {risk}\n"
            ])
            reason_summary = re.sub(r'[\r\n,]+', ' ', str(reason))[:80]
            csv_rows.append(f"{race_num},{race_class},{race_dist},{jockey},{trainer},{h_num_str},{h_name},{grade},{core_check},{reason_summary}")
            top_nums.append(h_num_str)

    top1_num = top_nums[0] if len(top_nums) > 0 else '?'
    top2_num = top_nums[1] if len(top_nums) > 1 else '?'
    lines.extend([
        '**🎯 Top 2 入三甲信心度 (Top 2 Place Confidence)**',
        f"🥇 [{top1_num}]:`[{v.get('top2_confidence_1', '🟢高')}]` — 最大威脅:[{top2_num}]",
        f"🥈 [{top2_num}]:`[{v.get('top2_confidence_2', '🟢高')}]` — 最大威脅:[{top1_num}]\n",
        '**🔄 步速逆轉保險 (Pace Flip Insurance):**'
    ])

    fli = v.get('pace_flip_insurance', {})
    faster = fli.get('if_faster', {})
    slower = fli.get('if_slower', {})
    lines.append(f"- 若步速比預測更快 → 最受惠: {faster.get('benefit') or top1_num} | 最受損: {faster.get('hurt') or top2_num}")
    lines.append(f"- 若步速比預測更慢 → 最受惠: {slower.get('benefit') or top1_num} | 最受損: {slower.get('hurt') or top2_num}\n")
    
    lines.extend([
        '**🚨 緊急煞車檢查 (Emergency Brake Protocol):**',
        f"- {v.get('emergency_brake', '無')}\n",
        '---\n',
        '#### [第四部分] 分析盲區(緊隨第三部分)\n',
        f"**1. 段速含金量:** {v.get('blind_spots', {}).get('sectionals', '無')}",
        f"**2. 風險管理:** {v.get('blind_spots', {}).get('risk_management', '無')}",
        f"**3. 試閘與預期假象:** {v.get('blind_spots', {}).get('trials_illusion', '無')}",
        f"**4. 特定與老馬風險:** {v.get('blind_spots', {}).get('age_risk', '無')}\n"
    ])
    
    lines.append('**6. 🎯 步速崩潰冷門 (Pace Collapse Dark Horse) [強制檢查點]:**')
    lines.append(f"{v.get('blind_spots', {}).get('pace_collapse_darkhorse', '無')}\n")
    lines.append('\n```csv')
    lines.append('race_num,race_class,distance,jockey,trainer,horse_num,horse_name,grade,tick_count,core_reason_summary')
    lines.extend(csv_rows)
    lines.append('```\n')

    return '\n'.join(lines)


def main():
    try:
        sys.stdout.reconfigure(encoding='utf-8', errors='replace')
    except Exception:
        pass
    parser = argparse.ArgumentParser()
    parser.add_argument("facts", help="Facts.md Path")
    parser.add_argument("logic_json", help="Logic.json Path")
    parser.add_argument("--output", required=True, help="Output Analysis.md Path")
    args = parser.parse_args()
    
    facts_text = Path(args.facts).read_text(encoding='utf-8')
    with open(args.logic_json, 'r', encoding='utf-8') as f:
        logic_data = json.load(f)
        
    # ── V4.2: Schema validation gate ──
    schema_result = validate_logic_json(logic_data)
    if not schema_result['pass']:
        print(f"🚨 V4.2 Schema validation FAILED ({len(schema_result['errors'])} errors):", file=sys.stderr)
        for err in schema_result['errors']:
            print(f"  ❌ {err}", file=sys.stderr)
        if os.path.exists(args.output):
            quarantine_file(args.output, f"V4.2 schema validation failed:\n" + "\n".join(schema_result['errors']))
        _write_compile_blocked(args.output, "\n".join(schema_result['errors']))
        sys.exit(1)
    for w in schema_result.get('warnings', []):
        print(f"  ⚠️ {w}")
    print(f"✅ V4.2 schema validation passed ({schema_result['stats']['horses_passed']}/{schema_result['stats']['horses_checked']} horses)")

    try:
        # Pre-compile JSON guard (dummy content)
        assert_no_dummy_json(logic_data, f"{Path(args.logic_json).name} before compile", allow_pending_fill=False)
        
        # Also assert core_logic is present and not empty
        for h_key, h_logic in logic_data.get('horses', {}).items():
            if not h_logic.get('core_logic'):
                raise ValueError(f"HKJC compile blocked: missing core_logic for horse {h_key} ({h_logic.get('horse_name','unknown')})")
            matrix_errors = validate_hkjc_matrix_confidence(h_logic)
            if matrix_errors:
                raise ValueError(
                    f"HKJC compile blocked: matrix confidence failed for horse {h_key} "
                    f"({h_logic.get('horse_name','unknown')}):\n"
                    + "\n".join(matrix_errors)
                )

    except ValueError as e:
        print(f"🚨 Pre-compile check failed:\n{e}", file=sys.stderr)
        _write_compile_blocked(args.output, str(e))
        if os.path.exists(args.output):
            quarantine_file(args.output, f"Pre-compile failed:\n{e}")
        sys.exit(1)
        
    facts_horses = gs.parse_facts_md_hkjc(facts_text)
    
    body = []
    body.append(build_hkjc_panorama_compiled(logic_data, facts_text, facts_horses))
    body.append('---\n#### [第二部分] 全場馬匹深度分析\n')
    
    horses_logic = logic_data.get('horses', {})

    # ── Compute grades and write back to JSON ──
    json_modified = False
    for h_key, h_logic in horses_logic.items():
        m_data = h_logic.get('matrix', {})
        try:
            grade_result = _compute_letter_grade(m_data, h_logic)
        except ValueError as e:
            print(f"🚨 Compile error:\n{e}", file=sys.stderr)
            _write_compile_blocked(args.output, str(e))
            if os.path.exists(args.output):
                quarantine_file(args.output, f"Compile error:\n{e}")
            sys.exit(1)
            
        h_logic['base_rating'] = grade_result['base_grade']
        h_logic['final_rating'] = grade_result['final_grade']
        json_modified = True

    for h in facts_horses:
        hl = horses_logic.get(str(h['num']), horses_logic.get(h['num'], {}))
        if not hl:
            hl = {"rating": "[未分析]", "core_logic": "[查無JSON節點]", "matrix": {}}
            
        body.append(generate_hkjc_horse_compiled(h, hl))
        body.append('---\n')
        
    body.append(build_hkjc_verdict_compiled(logic_data, facts_horses))
    
    final_markdown = '\n'.join(body)
    
    try:
        # Post-compile Markdown text guard
        assert_no_dummy_text(final_markdown, f"{Path(args.output).name} Analysis.md")
    except ValueError as e:
        print(f"🚨 Post-compile check failed:\n{e}", file=sys.stderr)
        
        # Write compile block reason
        blocked_file = Path(args.output).parent / ".runtime" / f"compile_blocked_{Path(args.output).stem}.txt"
        blocked_file.parent.mkdir(parents=True, exist_ok=True)
        blocked_file.write_text(str(e), encoding='utf-8')
        
        if os.path.exists(args.output):
            quarantine_file(args.output, f"Post-compile dummy text detected:\n{e}")
        sys.exit(1)
    
    # Atomic write: temp file → os.replace → final output
    # Never leaves a half-written Analysis.md on disk
    tmp_output = args.output + '.tmp'
    try:
        Path(tmp_output).write_text(final_markdown, encoding='utf-8')
        os.replace(tmp_output, args.output)
    except Exception:
        # Clean up partial temp file on any write error
        if os.path.exists(tmp_output):
            os.unlink(tmp_output)
        raise
    print(f"✅ HKJC Analysis 組裝完成 → {args.output}")

    # ── Write computed grades back to Logic.json ──
    if json_modified:
        with open(args.logic_json, 'w', encoding='utf-8') as f:
            json.dump(logic_data, f, ensure_ascii=False, indent=2)
        print(f"✅ 已回寫計算評級至 → {Path(args.logic_json).name}")

if __name__ == '__main__':
    main()
