#!/usr/bin/env python3
import os
os.environ.setdefault('PYTHONUTF8', '1')
"""
compile_analysis_template_hkjc.py — V8 HKJC Output Compiler (JSON -> Markdown)
========================================================================

Takes a given `Facts.md` and a matching `Race_X_Logic.json` (generated by the LLM),
and compiles them into a perfectly formatted V8 `Analysis.md`, applying the Calculator Pattern.

Usage:
  python .agents/skills/hkjc_racing/hkjc_wong_choi/scripts/compile_analysis_template_hkjc.py <Facts.md> <Logic.json> --output <Analysis.md>
"""

import sys
import json
import argparse
from pathlib import Path
import re

# We will reuse the core logic from generate_skeleton.py by importing it safely
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..', '..', 'scripts')))
import generate_skeleton as gs

# ── ABCD 正規字母評級系統 (from compute_rating_matrix_hkjc.py) ──────────
GRADE_ORDER = ['S', 'S-', 'A+', 'A', 'A-', 'B+', 'B', 'B-', 'C+', 'C', 'C-', 'D+', 'D']

# Map JSON matrix key → compute_rating dimension key
MATRIX_TO_DIM = {
    'stability':       'stability',
    'speed_mass':      'sectional',
    'eem':             'eem',
    'trainer_jockey':  'trainer_signal',
    'scenario':        'scenario',
    'freshness':       'distance_freshness',
    'formline':        'form_line',
    'class_advantage': 'class_advantage',
}

DIMENSION_TYPES = {
    'stability':          'core',
    'sectional':          'core',
    'eem':                'semi_core',
    'trainer_signal':     'semi_core',
    'scenario':           'auxiliary',
    'distance_freshness': 'auxiliary',
    'form_line':          'auxiliary',
    'class_advantage':    'auxiliary',
}

def _score_to_tick(score):
    """Convert a score to 5-tier tick: ✅✅/✅/➖/❌/❌❌."""
    if isinstance(score, str):
        s = score.strip()
        if s == '✅✅': return '✅✅'
        if '✅' in s: return '✅'
        if s == '❌❌': return '❌❌'
        if '❌' in s: return '❌'
        if '➖' in s or 'N/A' in s: return '➖'
        try:
            score = int(s)
        except ValueError:
            return '➖'
    if not isinstance(score, (int, float)):
        return '➖'
    if score >= 9:
        return '✅✅'
    elif score >= 7:
        return '✅'
    elif score >= 4:
        return '➖'
    elif score >= 2:
        return '❌'
    else:
        return '❌❌'

def _count_dimensions(dims: dict) -> dict:
    """Count dimensions with 5-tier support. ✅✅=2✅, ❌❌=2❌."""
    counts = {
        'core_strong': 0, 'core_neutral': 0, 'core_weak': 0,
        'semi_strong': 0, 'semi_neutral': 0, 'semi_weak': 0,
        'aux_strong': 0, 'aux_neutral': 0, 'aux_weak': 0,
        'total_strong': 0, 'total_weak': 0,
        'has_core_weak': False, 'has_core_double_weak': False,
        # Raw counts for display
        'core_dbl_strong': 0, 'semi_dbl_strong': 0, 'aux_dbl_strong': 0,
        'total_dbl_strong': 0, 'total_dbl_weak': 0,
        'core_single_strong': 0, 'semi_single_strong': 0, 'aux_single_strong': 0,
    }
    for dim_key, value in dims.items():
        v = value.strip() if isinstance(value, str) else str(value)
        if v in ('N/A', '不計入'):
            continue
        dim_type = DIMENSION_TYPES.get(dim_key, 'auxiliary')
        if v == '✅✅':
            counts['total_strong'] += 2
            counts['total_dbl_strong'] += 1
            if dim_type == 'core':
                counts['core_strong'] += 2
                counts['core_dbl_strong'] += 1
            elif dim_type == 'semi_core':
                counts['semi_strong'] += 2
                counts['semi_dbl_strong'] += 1
            else:
                counts['aux_strong'] += 2
                counts['aux_dbl_strong'] += 1
        elif v == '✅':
            counts['total_strong'] += 1
            if dim_type == 'core':
                counts['core_strong'] += 1
                counts['core_single_strong'] += 1
            elif dim_type == 'semi_core':
                counts['semi_strong'] += 1
                counts['semi_single_strong'] += 1
            else:
                counts['aux_strong'] += 1
                counts['aux_single_strong'] += 1
        elif v == '❌❌':
            counts['total_weak'] += 2
            counts['total_dbl_weak'] += 1
            if dim_type == 'core':
                counts['core_weak'] += 2
                counts['has_core_weak'] = True
                counts['has_core_double_weak'] = True
            elif dim_type == 'semi_core': counts['semi_weak'] += 2
            else: counts['aux_weak'] += 2
        elif v == '❌':
            counts['total_weak'] += 1
            if dim_type == 'core':
                counts['core_weak'] += 1
                counts['has_core_weak'] = True
            elif dim_type == 'semi_core': counts['semi_weak'] += 1
            else: counts['aux_weak'] += 1
        else:  # ➖ neutral
            if dim_type == 'core': counts['core_neutral'] += 1
            elif dim_type == 'semi_core': counts['semi_neutral'] += 1
            else: counts['aux_neutral'] += 1
    return counts

def _lookup_base_grade(c: dict) -> tuple:
    cs, ss, axs, tw = c['core_strong'], c['semi_strong'], c['aux_strong'], c['total_weak']
    if cs >= 2 and ss >= 2 and axs >= 2 and tw == 0:
        return 'S', f'2核心✅ + 2半核心✅ + {axs}輔助✅ + 0❌'
    if cs >= 2 and ss >= 1 and axs >= 1 and tw == 0:
        return 'S-', f'2核心✅ + {ss}半核心✅ + {axs}輔助✅ + 0❌'
    if cs >= 2 and tw == 0:
        return 'A+', f'2核心✅ + 0❌'
    if (cs >= 1 and ss >= 1 and tw == 0) or (cs >= 2 and tw <= 1):
        return 'A', f'{cs}核心✅ + {ss}半核心✅ + {tw}❌'
    if cs >= 1 and tw <= 1:
        return 'A-', f'{cs}核心✅ + ❌≤1'
    if (cs >= 1 and tw == 2) or (ss >= 2 and tw <= 1):
        return 'B+', f'{cs}核心✅/{ss}半核心✅ + {tw}❌'
    if ss >= 1 and axs >= 2 and tw <= 2:
        return 'B', f'{ss}半核心✅ + {axs}輔助✅ + {tw}❌'
    if cs == 0 and ss == 0 and axs >= 3 and tw <= 2:
        return 'B-', f'0核心/半核心✅ + {axs}輔助✅'
    if tw == 3 and (cs >= 1 or ss >= 1):
        return 'C+', f'{tw}❌ + 有核心/半核心✅挽救'
    if tw == 3:
        return 'C', f'{tw}❌ + 無核心/半核心✅'
    if tw == 4:
        return 'C-', f'{tw}❌'
    ts = c['total_strong']
    if tw >= 5 and (cs >= 1 or ss >= 1 or axs >= 2):
        return 'D+', f'{tw}❌ + 有✅({ts})'
    if tw >= 5 or ts == 0:
        return 'D', f'{tw}❌ / 無✅'
    return 'C', f'未匹配 (core✅={cs}, semi✅={ss}, aux✅={axs}, ❌={tw})'

def _grade_idx(g: str) -> int:
    return GRADE_ORDER.index(g) if g in GRADE_ORDER else 99

def _apply_core_constraint(grade: str, counts: dict, dims: dict) -> tuple:
    if not counts['has_core_weak']:
        return grade, ''
    # ❌❌ in core = strict cap at B+, no exemption
    if counts.get('has_core_double_weak'):
        if _grade_idx(grade) < _grade_idx('B+'):
            return 'B+', '核心防護牆: 核心❌❌ → 封頂B+ (無豁免)'
        return grade, ''
    if dims.get('sectional', '').strip() in ('✅', '✅✅') and dims.get('eem', '').strip() in ('✅', '✅✅'):
        if _grade_idx(grade) < _grade_idx('A-'):
            return 'A-', '核心❌但段速✅+EEM✅豁免 → 封頂A-'
        return grade, ''
    if _grade_idx(grade) < _grade_idx('B+'):
        return 'B+', '核心防護牆: 核心❌ → 封頂B+'
    return grade, ''

def _apply_micro(grade: str, direction: str) -> tuple:
    i = _grade_idx(grade)
    if direction == 'UP' and i > 0:
        return GRADE_ORDER[i - 1], '升一級'
    elif direction == 'DOWN' and i < len(GRADE_ORDER) - 1:
        return GRADE_ORDER[i + 1], '降一級'
    return grade, '無變動'

def _infer_ticks_from_rating(rating: str) -> dict:
    """When matrix is absent, infer reasonable dimension ticks from final_rating string."""
    r = rating.strip() if rating else ''
    # S / S- / A+ / A : mostly ✅✅ or ✅
    if r in ('S', 'S-', 'A+'):
        return {'stability': '✅✅', 'sectional': '✅✅', 'eem': '✅',
                'trainer_signal': '✅', 'scenario': '✅', 'distance_freshness': '✅',
                'form_line': '✅', 'class_advantage': '✅'}
    if r in ('A',):
        return {'stability': '✅✅', 'sectional': '✅', 'eem': '✅',
                'trainer_signal': '✅', 'scenario': '✅', 'distance_freshness': '➖',
                'form_line': '✅', 'class_advantage': '➖'}
    if r in ('A-',):
        return {'stability': '✅', 'sectional': '✅', 'eem': '✅',
                'trainer_signal': '➖', 'scenario': '➖', 'distance_freshness': '➖',
                'form_line': '✅', 'class_advantage': '➖'}
    if r in ('B+',):
        return {'stability': '✅', 'sectional': '➖', 'eem': '✅',
                'trainer_signal': '✅', 'scenario': '➖', 'distance_freshness': '➖',
                'form_line': '➖', 'class_advantage': '➖'}
    if r in ('B',):
        return {'stability': '➖', 'sectional': '✅', 'eem': '➖',
                'trainer_signal': '✅', 'scenario': '➖', 'distance_freshness': '➖',
                'form_line': '➖', 'class_advantage': '➖'}
    if r in ('B-', 'C+', 'C'):
        return {'stability': '➖', 'sectional': '➖', 'eem': '➖',
                'trainer_signal': '➖', 'scenario': '➖', 'distance_freshness': '➖',
                'form_line': '➖', 'class_advantage': '➖'}
    if r in ('C-', 'D+', 'D', 'D-', 'E', 'E-'):
        return {'stability': '❌', 'sectional': '❌', 'eem': '❌',
                'trainer_signal': '❌', 'scenario': '❌', 'distance_freshness': '❌',
                'form_line': '❌', 'class_advantage': '❌'}
    return {k: '➖' for k in MATRIX_TO_DIM.values()}


def _build_synthetic_matrix_reasoning(h_logic: dict) -> dict:
    """Build reasoning strings from analytical_breakdown when matrix is missing."""
    ab = h_logic.get('analytical_breakdown', {})
    forg = h_logic.get('forgiveness_archive', {})
    # Map each matrix dimension → best available analytical_breakdown text
    return {
        'stability':       ab.get('stability_risk', ab.get('trend_analysis', '見馬匹剖析')),
        'speed_mass':      ab.get('pace_adaptation', ab.get('trend_analysis', '見段速法醫')),
        'eem':             ab.get('trend_analysis', '見EEM能量'),
        'trainer_jockey':  (ab.get('trainer_signal', '') + ' ' + ab.get('jockey_fit', '')).strip() or '見馬匹剖析',
        'scenario':        ab.get('pace_adaptation', ab.get('track_distance_suitability', '見步速分析')),
        'freshness':       ab.get('track_distance_suitability', ab.get('engine_distance', '見路程適性')),
        'formline':        ab.get('hidden_form', ab.get('class_assessment', '見賽績線')),
        'class_advantage': ab.get('class_assessment', '見級數評估'),
        'forgiveness':     forg.get('conclusion', forg.get('factors', '見寬恕檔案')),
    }


def _compute_letter_grade(m_data: dict, h_logic: dict) -> dict:
    """Compute the proper ABCD letter grade from matrix numeric scores.
    Falls back to final_rating-based inference when matrix is absent.
    """
    matrix_missing = not m_data  # no matrix at all

    if matrix_missing:
        # Use final_rating string to infer dims directly
        fr = h_logic.get('final_rating', '')
        dims = _infer_ticks_from_rating(fr)
    else:
        # Step 1: Convert numeric scores to ✅/❌/➖
        dims = {}
        for json_key, dim_key in MATRIX_TO_DIM.items():
            item = m_data.get(json_key, {})
            score = item.get('score', 5)
            dims[dim_key] = _score_to_tick(score)

    # Step 2: Count dimensions
    counts = _count_dimensions(dims)

    # Step 3: Check forgiveness bonus (5-tier aware)
    forg_item = m_data.get('forgiveness_bonus', {})
    forg_tick = _score_to_tick(forg_item.get('score', 0))
    if forg_tick == '✅✅':
        counts['aux_strong'] += 2
        counts['total_strong'] += 2
        counts['aux_dbl_strong'] += 1
        counts['total_dbl_strong'] += 1
    elif forg_tick == '✅':
        counts['aux_strong'] += 1
        counts['total_strong'] += 1

    # Step 4: Lookup base grade
    base_grade, base_rule = _lookup_base_grade(counts)

    # Step 5: Core constraint
    constrained_grade, constraint_note = _apply_core_constraint(base_grade, counts, dims)

    # Step 6: If matrix was missing, override final grade with the explicitly stored final_rating
    if matrix_missing:
        fr = h_logic.get('final_rating', '')
        if fr:
            constrained_grade = fr
            base_grade = fr
            base_rule = f'直接引用 final_rating={fr} (matrix缺失)'
            constraint_note = ''

    # Step 7: Micro adjustment
    ft = h_logic.get('fine_tune', {})
    ft_dir = ft.get('direction', '無') if isinstance(ft, dict) else str(ft)
    # Skip micro adjustment when matrix is missing (grade already exact)
    if matrix_missing:
        adjusted_grade, micro_note = constrained_grade, '無 (matrix缺失，直接引用評級)'
    else:
        adjusted_grade, micro_note = _apply_micro(constrained_grade, ft_dir.upper())

    return {
        'dims': dims,
        'counts': counts,
        'base_grade': base_grade,
        'base_rule': base_rule,
        'constraint_note': constraint_note,
        'adjusted_grade': adjusted_grade,
        'micro_note': micro_note,
        'final_grade': adjusted_grade,
        'matrix_missing': matrix_missing,
    }

def build_hkjc_panorama_compiled(json_data, facts_text, facts_horses=None):
    v = json_data.get('race_analysis', {})
    sm = v.get('speed_map', {})
    
    # Build num→name lookup
    num_to_name = {}
    if facts_horses:
        num_to_name = {str(h['num']): h['name'] for h in facts_horses}
    
    def _map_names(num_list):
        """Convert ['7','8'] or '7, 8' or ['7, 8'] to '[7] 電訊巴打, [8] 穿甲金鷹'."""
        if isinstance(num_list, str):
            num_list = [x.strip() for x in num_list.replace('、', ',').split(',')]
        elif isinstance(num_list, list):
            flat = []
            for item in num_list:
                if isinstance(item, str) and ',' in item:
                    flat.extend([x.strip() for x in item.split(',')])
                elif isinstance(item, str) and '、' in item:
                    flat.extend([x.strip() for x in item.split('、')])
                else:
                    flat.append(str(item).strip())
            num_list = flat
            
        parts = []
        for n in num_list:
            if not n: continue
            name = num_to_name.get(str(n), '')
            parts.append(f'[{n}] {name}' if name else str(n))
        return ', '.join(parts) or '[未指定]'
    
    venue = "[馬場]"
    dist = "[路程]"
    cls_grade = "[班次]"
    
    m = re.search(r'場地:\s*([^|]*?)\s*\|\s*距離:\s*([^|]*?)\s*\|\s*班次:\s*([^\n]+)', facts_text)
    if m:
        v_val = m.group(1).strip()
        if v_val: venue = v_val
        d_val = m.group(2).strip()
        if d_val and d_val != "0m": dist = d_val
        c_val = m.group(3).strip()
        if c_val: cls_grade = c_val
        
    race_type = "`[全天候跑道 (AWT)]`" if "AWT" in venue or "泥地" in facts_text else "`[草地]`"

    pace = sm.get('predicted_pace', '[未預測]')
    leaders = _map_names(sm.get('leaders', []))
    on_pace = _map_names(sm.get('on_pace', []))
    mid = _map_names(sm.get('mid_pack', []))
    closers = _map_names(sm.get('closers', []))
    
    weather_going = "詳見情報"
    bias = sm.get('track_bias', '[未預測]')
    if not bias: bias = '[未預測]'
    tactical_nodes = sm.get('tactical_nodes', '[未提供]')
    if not tactical_nodes: tactical_nodes = '[未提供]'
    collapse = sm.get('collapse_point', '[未提供]')
    if not collapse: collapse = '[未提供]'
    
    pace_details = (
        f"- **預計步速:** {pace}\n"
        f"- **跑道偏差:** {bias}\n"
        f"- **戰術節點:** {tactical_nodes}\n"
        f"- **崩潰點:** {collapse}"
    )
    
    return f"""## [第一部分] 🗺️ 戰場全景

| 項目 | 內容 |
|:---|:---|
| 賽事格局 | {cls_grade} / {dist} / {race_type.replace('`[','').replace(']`','')} / {venue} |
| **賽事類型** | **{race_type}** |
| 天氣 / 場地 | {weather_going} |
| 跑道偏差 | {bias} |
| 步速預測 | {pace} |

**📍 Speed Map (速度地圖):**
- 領放群: {leaders}
- 前中段: {on_pace}
- 中後段: {mid}
- 後上群: {closers}

**🏃 步速瀑布推演 (Step 0 結論):**
{pace_details}
"""

def generate_hkjc_horse_compiled(h_fact, h_logic):
    lines = []
    jockey_str = h_fact['jockey'] if h_fact['jockey'] else 'Unknown'
    trainer_str = h_fact['trainer'] if h_fact['trainer'] else 'Unknown'
    weight_str = str(h_fact['weight']) if h_fact['weight'] else 'Unknown'

    # rating/final_rating will be computed by ABCD grade system below (Section 9-10)
    rating = '[待計算]'
    final_rating = '[待計算]'
    # Build advantages/disadvantages from analytical_breakdown when dedicated keys are absent
    _ab = h_logic.get('analytical_breakdown', {})
    _default_advantages = (
        _ab.get('track_distance_suitability', '') or
        _ab.get('hidden_form', '') or
        _ab.get('trend_analysis', '') or
        '見馬匹剖析'
    )
    _default_disadvantages = (
        _ab.get('stability_risk', '') or
        _ab.get('pace_adaptation', '') or
        _ab.get('class_assessment', '') or
        '見馬匹剖析'
    )
    disadvantages = h_logic.get('disadvantages', h_logic.get('risk_level', _default_disadvantages))
    advantages = h_logic.get('advantages', h_logic.get('competitive_advantage', _default_advantages))
    fgv = h_logic.get('scenario_tags', '無')

    # ── 1. 馬匹標題 + 情境標記 ──────────────────────────────────────────
    lines.append(f"**【No.{h_fact['num']}】 {h_fact['name']}** | 騎師:{jockey_str} | 練馬師:{trainer_str} | 負磅:{weight_str} | 檔位:{h_fact['barrier']}")
    lines.append(f"**📌 情境標記:** `{fgv}`\n")

    # ── 2. 近績解構 (排位表事實錨點) ────────────────────────────────────
    lines.append('#### ⏱️ 近績解構')
    if h_fact.get('summary') and '(無往績記錄)' not in h_fact.get('summary', ''):
        summary_clean = h_fact['summary'].replace('📌 **賽績總結:**', '').replace('📌 賽績總結:', '').strip()
        lines.append(summary_clean)
    else:
        lines.append('- **(無往績記錄)**')
    lines.append('')

    # ── 3. 完整賽績檔案 (Facts 注入，僅一次) ────────────────────────────
    if h_fact.get('table') and '(無往績記錄)' not in h_fact.get('table', ''):
        lines.append('#### 📋 完整賽績與寬恕檔案 (包含 Step 12 判斷)\n')
        race_forgiveness = h_logic.get('race_forgiveness', [])
        lines.append(gs._truncate_table(h_fact['table']) + '\n')
        lines.append(f"- **逐場寬恕判定:** `{json.dumps(race_forgiveness, ensure_ascii=False)}`\n")
    else:
        lines.append('#### 📋 完整賽績檔案: (無往績記錄)\n')

    # ── 4. 馬匹剖析 (10 項全套) ─────────────────────────────────────────
    h_analysis = h_logic.get('analytical_breakdown', {})
    lines.append('#### 🐴 馬匹剖析')
    lines.extend([
        f"- **走勢趨勢 (Step 10.3+):** {h_analysis.get('trend_analysis', '[FILL]')}",
        f"- **隱藏賽績 (Step 6+12):** {h_analysis.get('hidden_form', '[FILL]')}",
        f"- **穩定性/贏馬回落 (Step 5):** {h_analysis.get('stability_risk', '[FILL]')}",
        f"- **級數評估 (Step 8.1):** {h_analysis.get('class_assessment', '[FILL]')}",
        f"- **路程場地適性 (Step 2):** {h_analysis.get('track_distance_suitability', '[FILL]')}",
        f"- **引擎距離 (Step 2.6):** {h_analysis.get('engine_distance', '[FILL]')}",
        f"- **配備變動 (Step 6):** {h_analysis.get('gear_changes', '[FILL]')}",
        f"- **部署與練馬師訊號 (Step 8.2):** {h_analysis.get('trainer_signal', '[FILL]')}",
        f"- **人馬配搭 (Step 2.5):** {h_analysis.get('jockey_fit', '[FILL]')}",
        f"- **步速段速 (Step 0+10):** {h_analysis.get('pace_adaptation', '[FILL]')}",
    ])
    lines.append('')

    # ── 5. 段速法醫 ──────────────────────────────────────────────────────
    sf = h_logic.get('sectional_forensic', {})
    lines.append('#### 🔬 段速法醫 (Step 10)')
    lines.append(
        f"- **原始 L600/L400:** {sf.get('raw_L400', '[FILL]')} | "
        f"**修正因素:** {sf.get('correction_factor', '[FILL]')} | "
        f"**修正判斷:** {sf.get('corrected_assessment', '[FILL]')}"
    )
    lines.append(f"- **所示趨勢(近 3 仗):** `{sf.get('trend', '[FILL]')}`\n")

    # ── 6. EEM 能量 ───────────────────────────────────────────────────────
    eem = h_logic.get('eem_energy', {})
    lines.append('#### ⚡ EEM 能量 (Step 11)')
    lines.append(f"- **上仗走位:** {eem.get('last_run_position', '[FILL]')}")
    lines.append(f"- **累積消耗:** `{eem.get('cumulative_drain', '[FILL]')}`")
    lines.append(f"- **總評:** {eem.get('assessment', '[FILL]')}\n")

    # ── 7. 寬恕檔案 ───────────────────────────────────────────────────────
    forg = h_logic.get('forgiveness_archive', {})
    lines.append('#### 📋 寬恕檔案 (Step 12)')
    lines.append(f"- **因素:** {forg.get('factors', '[FILL]')}")
    lines.append(f"- **結論:** `{forg.get('conclusion', '[FILL]')}`\n")

    # ── 8. 賽績線 (Facts 注入，僅一次，無重複) ──────────────────────────
    if h_fact.get('formline') and '(無往績記錄)' not in h_fact.get('formline', ''):
        lines.append('#### 🔗 賽績線 (近績對手強弱追蹤庫)\n')
        fl_clean = h_fact['formline'].replace('🔗 **賽績線 (近 5 場正式賽事，官方追蹤):**', '').replace('🔗 賽績線 (近 5 場正式賽事，官方追蹤):', '').strip()
        lines.append(fl_clean + '\n')
        formline_str = h_analysis.get('formline_strength', '')
        if formline_str and formline_str != '[FILL]':
            lines.append(f"- **綜合結論:** `{formline_str}`\n")
        else:
            lines.append(f"- **綜合結論:** `詳見賽績線數據`\n")
    else:
        lines.append('#### 🔗 賽績線: (無往績記錄)\n')

    # ── 9. 評級矩陣 (8 維度) + 正規 ABCD 字母評級 ──────────────────────
    lines.append('#### 📊 評級矩陣 (Step 14)')
    matrix_keys = [
        ("stability",      "位置穩定性", "核心"),
        ("speed_mass",     "段速質量",   "核心"),
        ("eem",            "EEM 潛力",   "半核心"),
        ("trainer_jockey", "練馬師訊號", "半核心"),
        ("scenario",       "情境適配",   "輔助"),
        ("freshness",      "路程/新鮮度","輔助"),
        ("formline",       "賽績線",     "輔助"),
        ("class_advantage","級數優勢",   "輔助"),
    ]
    m_data = h_logic.get('matrix', {})

    # Compute proper ABCD letter grade
    grade_result = _compute_letter_grade(m_data, h_logic)
    gr_dims = grade_result['dims']
    gr_counts = grade_result['counts']
    matrix_missing = grade_result.get('matrix_missing', False)

    # Build reasoning fallback from analytical_breakdown when matrix is absent
    synth_reasons = _build_synthetic_matrix_reasoning(h_logic) if matrix_missing else {}

    # Map matrix JSON key → synthetic reasoning key
    MATRIX_TO_SYNTH = {
        'stability':       'stability',
        'speed_mass':      'speed_mass',
        'eem':             'eem',
        'trainer_jockey':  'trainer_jockey',
        'scenario':        'scenario',
        'freshness':       'freshness',
        'formline':        'formline',
        'class_advantage': 'class_advantage',
    }

    for en_key, zh_key, c_type in matrix_keys:
        item = m_data.get(en_key, {})
        if matrix_missing:
            reason = synth_reasons.get(MATRIX_TO_SYNTH.get(en_key, ''), '見馬匹剖析')
        else:
            reason = item.get('reasoning', item.get('reason', '[無提供]'))
        dim_key = MATRIX_TO_DIM.get(en_key, '')
        tick = gr_dims.get(dim_key, '➖')
        lines.append(f"- **{zh_key}** [{c_type}]: `{tick}` | 理據: `{reason}`")

    forgive_item = m_data.get('forgiveness_bonus', {})
    forg_score = forgive_item.get('score', '[-]')
    if matrix_missing:
        forg_reason = synth_reasons.get('forgiveness', '見寬恕檔案')
        forg_tick = '➖'
    else:
        forg_reason = forgive_item.get('reasoning', forgive_item.get('reason', '[無提供]'))
        forg_tick = _score_to_tick(forg_score)
    lines.append(f"- 寬恕加分: `{forg_tick}` | 理據: `{forg_reason}`\n")

    # ── 10. 矩陣算術 + 14.2 基礎評級 (ABCD 正規字母制) ────────────────
    cw = '有' if gr_counts['has_core_weak'] else '無'
    cdw = '有' if gr_counts.get('has_core_double_weak') else '無'
    lines.append(f"**🔢 矩陣算術:** 核心✅✅={gr_counts.get('core_dbl_strong',0)} | 核心✅={gr_counts.get('core_single_strong',0)} | 半核心✅✅={gr_counts.get('semi_dbl_strong',0)} | 半核心✅={gr_counts.get('semi_single_strong',0)} | 輔助✅✅={gr_counts.get('aux_dbl_strong',0)} | 輔助✅={gr_counts.get('aux_single_strong',0)} | 總❌={gr_counts['total_weak']} | 總❌❌={gr_counts.get('total_dbl_weak',0)} | 核心❌={cw} | 核心❌❌={cdw} → 查表命中行={grade_result['base_grade']}")
    lines.append(f"**14.2 基礎評級:** `{grade_result['base_grade']}` | **規則**: `{grade_result['base_rule']}`")
    if grade_result['constraint_note']:
        lines.append(f"**核心防護牆:** `{grade_result['constraint_note']}`")

    # ── 11. 14.2B 微調 ────────────────────────────────────────────────────
    ft = h_logic.get('fine_tune', {})
    ft_dir = ft.get('direction', '無') if isinstance(ft, dict) else str(ft)
    ft_trig = ft.get('trigger', '無') if isinstance(ft, dict) else '無'
    lines.append(f"**14.2B 微調:** `{ft_dir}` ({grade_result['micro_note']}) | 觸發: `{ft_trig}`")

    # ── 12. 14.3 覆蓋 ────────────────────────────────────────────────────
    ovr = h_logic.get('override', {})
    ovr_rule = ovr.get('rule', '無') if isinstance(ovr, dict) else str(ovr)
    lines.append(f"**14.3 覆蓋:** `{ovr_rule}`\n")

    # Update rating/final_rating to use the computed ABCD letter grade
    rating = grade_result['base_grade']
    final_rating = grade_result['final_grade']

    # ── 13. 結論與評語 ───────────────────────────────────────────────────
    lines.append('#### 💡 結論與評語 (Conclusion & Analyst View)')
    lines.extend([
        f"> - **核心邏輯:** {h_logic.get('core_logic', '[缺失核心邏輯]')}",
        f"> - **最大競爭優勢:** {advantages}",
        f"> - **最大失敗風險:** {disadvantages}\n"
    ])

    # ── 14. 法醫級推演錨點 (已移除 — V10) ─────────────────────────────────

    # ── 15. 最終評級 ─────────────────────────────────────────────────────
    lines.append(f"**⭐ 最終評級:** `{final_rating}`\n")

    # ── 16. 冷門馬訊號 ───────────────────────────────────────────────────
    uh = h_logic.get('underhorse', {})
    uh_trig = "觸發" if uh.get('triggered') else "未觸發"
    lines.append(f"🐴⚡ **冷門馬訊號 (Underhorse Signal):** `{uh_trig}`")
    if uh_trig == "觸發":
        lines.append(f"- **受惠條件:** {uh.get('condition', '')}")
        lines.append(f"- **理由:** {uh.get('reason', '')}")

    return '\n'.join(lines)


def build_hkjc_verdict_compiled(json_data, facts_horses):
    v = json_data.get('race_analysis', {}).get('verdict', {})
    horse_names = {h['num']: h['name'] for h in facts_horses}
    horses_logic = json_data.get('horses', {})

    lines = []
    lines.append('#### [第三部分] 最終預測 (The Verdict)\n')
    lines.append(f"- **跑道形勢:** {v.get('track_scenario', '[FILL]')}")
    lines.append(f"- **信心指數:** `{v.get('confidence', '[中]')}`")
    lines.append(f"- **關鍵變數:** {v.get('key_variables', '[FILL]')}\n")

    lines.append('**🏆 Top 4 位置精選**\n')

    # ── AUTO-COMPUTE Top 4 from ALL horses' grades (ignore LLM's manual picks) ──
    # Build a lookup of LLM's original reason/risk keyed by horse_num
    llm_picks = {}
    for item in v.get('top4', []):
        h_num = str(item.get('horse_num', item.get('horse_number', '')))
        llm_picks[h_num] = item

    # Compute grade for every horse
    all_graded = []
    for h_num_str, h_obj in horses_logic.items():
        if "final_rating" in h_obj:
            grade = h_obj["final_rating"]
            gr_res = {'final_grade': grade, 'num_checks': 0}
        else:
            m_data = h_obj.get('matrix', {})
            gr_res = _compute_letter_grade(m_data, h_obj)
            grade = gr_res['final_grade']
        grade_i = _grade_idx(grade)
        all_graded.append((h_num_str, grade, grade_i, gr_res))

    # Sort by grade index (lower = better), then horse number as tiebreaker
    all_graded.sort(key=lambda x: (x[2], int(x[0]) if x[0].isdigit() else 999))

    # Take top 4
    t4_auto = all_graded[:4]

    labels = ['🥇 **第一選**', '🥈 **第二選**', '🥉 **第三選**', '🏅 **第四選**']
    csv_rows = []
    race_info = json_data.get('race_analysis', {})
    race_num = race_info.get('race_number', '?')
    race_class = race_info.get('race_class', '?')
    race_dist = race_info.get('distance', '?')

    top_nums = []  # track for Top 2 confidence section
    for i, label in enumerate(labels):
        if i < len(t4_auto):
            h_num_str, grade, grade_i, gr_res = t4_auto[i]
            h_num_int = int(h_num_str) if h_num_str.isdigit() else 0
            h_name = horse_names.get(h_num_int, '')
            h_obj = horses_logic.get(h_num_str, {})
            m_data = h_obj.get('matrix', {})
            # core_check: count ✅ ticks from computed dims (works with & without matrix)
            _gr_for_check = _compute_letter_grade(m_data, h_obj)
            _dims_for_check = _gr_for_check.get('dims', {})
            core_check = sum(1 for v_tick in _dims_for_check.values() if '✅' in str(v_tick))
            jockey = next((hf['jockey'] for hf in facts_horses if str(hf['num']) == h_num_str), '')
            trainer = next((hf['trainer'] for hf in facts_horses if str(hf['num']) == h_num_str), '')

            # Use LLM reason/risk if available; accept both 'rationale' and 'reason' keys
            if h_num_str in llm_picks:
                pick = llm_picks[h_num_str]
                reason = pick.get('rationale', pick.get('reason', ''))
                risk_raw = pick.get('risk', '')
                # risk may be a list or string
                if isinstance(risk_raw, list):
                    risk = ' / '.join(str(r) for r in risk_raw)
                else:
                    risk = str(risk_raw) if risk_raw else ''
                # fallback if still empty
                if not reason:
                    reason = h_obj.get('core_logic', h_obj.get('advantages', '[見核心邏輯]'))
                if not risk:
                    risk = h_obj.get('disadvantages', h_obj.get('risk_level', '[見分析]'))
            else:
                reason = h_obj.get('core_logic', h_obj.get('advantages', h_obj.get('competitive_advantage', '[自動選入]')))
                risk_raw = h_obj.get('disadvantages', h_obj.get('risk_level', '[見分析]'))
                if isinstance(risk_raw, list):
                    risk = ' / '.join(str(r) for r in risk_raw)
                else:
                    risk = str(risk_raw) if risk_raw else '[見分析]'

            lines.extend([
                label,
                f"- **馬號及馬名:** [{h_num_str}] {h_name}",
                f"- **評級與✅數量:** `[{grade}]` | ✅ {core_check}",
                f"- **核心理據:** {reason}",
                f"- **最大風險:** {risk}\n"
            ])
            csv_rows.append(f"{race_num},{race_class},{race_dist},{jockey},{trainer},{h_num_str},{h_name},{grade}")
            top_nums.append(h_num_str)

    top1_num = top_nums[0] if len(top_nums) > 0 else '?'
    top2_num = top_nums[1] if len(top_nums) > 1 else '?'
    lines.extend([
        '**🎯 Top 2 入三甲信心度 (Top 2 Place Confidence)**',
        f"🥇 [{top1_num}]:`[{v.get('top2_confidence_1', '🟢高')}]` — 最大威脅:[{top2_num}]",
        f"🥈 [{top2_num}]:`[{v.get('top2_confidence_2', '🟢高')}]` — 最大威脅:[{top1_num}]\n",
        '**🔄 步速逆轉保險 (Pace Flip Insurance):**'
    ])

    fli = v.get('pace_flip_insurance', {})
    faster = fli.get('if_faster', {})
    slower = fli.get('if_slower', {})
    lines.append(f"- 若步速比預測更快 → 最受惠: {faster.get('benefit', '')} | 最受損: {faster.get('hurt', '')}")
    lines.append(f"- 若步速比預測更慢 → 最受惠: {slower.get('benefit', '')} | 最受損: {slower.get('hurt', '')}\n")
    
    lines.extend([
        '**🚨 緊急煞車檢查 (Emergency Brake Protocol):**',
        f"- {v.get('emergency_brake', '無')}\n",
        '---\n',
        '#### [第四部分] 分析盲區(緊隨第三部分)\n',
        f"**1. 段速含金量:** {v.get('blind_spots', {}).get('sectionals', '無')}",
        f"**2. 風險管理:** {v.get('blind_spots', {}).get('risk_management', '無')}",
        f"**3. 試閘與預期假象:** {v.get('blind_spots', {}).get('trials_illusion', '無')}",
        f"**4. 特定與老馬風險:** {v.get('blind_spots', {}).get('age_risk', '無')}\n"
    ])
    
    lines.append('**6. 🎯 步速崩潰冷門 (Pace Collapse Dark Horse) [強制檢查點]:**')
    lines.append(f"{v.get('blind_spots', {}).get('pace_collapse_darkhorse', '無')}\n")
    lines.append('\n```csv\nPLACEHOLDER\n```\n')

    return '\n'.join(lines)


def main():
    try:
        sys.stdout.reconfigure(encoding='utf-8', errors='replace')
    except Exception:
        pass
    parser = argparse.ArgumentParser()
    parser.add_argument("facts", help="Facts.md Path")
    parser.add_argument("logic_json", help="Logic.json Path")
    parser.add_argument("--output", required=True, help="Output Analysis.md Path")
    args = parser.parse_args()
    
    facts_text = Path(args.facts).read_text(encoding='utf-8')
    with open(args.logic_json, 'r', encoding='utf-8') as f:
        logic_data = json.load(f)
        
    facts_horses = gs.parse_facts_md_hkjc(facts_text)
    
    body = []
    body.append(build_hkjc_panorama_compiled(logic_data, facts_text, facts_horses))
    body.append('---\n#### [第二部分] 全場馬匹深度分析\n')
    
    horses_logic = logic_data.get('horses', {})

    # ── Compute grades and write back to JSON ──
    json_modified = False
    for h_key, h_logic in horses_logic.items():
        m_data = h_logic.get('matrix', {})
        grade_result = _compute_letter_grade(m_data, h_logic)
        h_logic['base_rating'] = grade_result['base_grade']
        h_logic['final_rating'] = grade_result['final_grade']
        json_modified = True

    for h in facts_horses:
        hl = horses_logic.get(str(h['num']), horses_logic.get(h['num'], {}))
        if not hl:
            hl = {"rating": "[未分析]", "core_logic": "[查無JSON節點]", "analytical_breakdown": {}}
            
        body.append(generate_hkjc_horse_compiled(h, hl))
        body.append('---\n')
        
    body.append(build_hkjc_verdict_compiled(logic_data, facts_horses))
    
    Path(args.output).write_text('\n'.join(body), encoding='utf-8')
    print(f"✅ HKJC Analysis 組裝完成 → {args.output}")

    # ── Write computed grades back to Logic.json ──
    if json_modified:
        with open(args.logic_json, 'w', encoding='utf-8') as f:
            json.dump(logic_data, f, ensure_ascii=False, indent=2)
        print(f"✅ 已回寫計算評級至 → {Path(args.logic_json).name}")

if __name__ == '__main__':
    main()

