# AUTO-GENERATED from tennis-data.co.uk ATP/WTA season xlsx. Do not edit by hand.
# Regenerate via: python3 scripts/build_tennisdata_index.py
# Key: (tour, normalised_tournament_name) -> (level, surface, normalised_location).
# Surface is stable year-to-year (reliable); level is best-effort from historical
# data and can lag promotions/demotions, so the curated list takes precedence.

TENNISDATA_TOURNAMENTS = {
    ('ATP', 'abierto mexicano'): ('ATP_500', 'Hard', 'acapulco'),
    ('ATP', 'abn amro world tennis tournament'): ('ATP_500', 'Hard', 'rotterdam'),
    ('ATP', 'adelaide international'): ('ATP_250', 'Hard', 'adelaide'),
    ('ATP', 'adelaide international 1'): ('ATP_250', 'Hard', 'adelaide'),
    ('ATP', 'adelaide international 2'): ('ATP_250', 'Hard', 'adelaide'),
    ('ATP', 'almaty open'): ('ATP_250', 'Hard', 'almaty'),
    ('ATP', 'argentina open'): ('ATP_250', 'Clay', 'buenos aires'),
    ('ATP', 'asb classic'): ('ATP_250', 'Hard', 'auckland'),
    ('ATP', 'astana open'): ('ATP_250', 'Hard', 'nur sultan'),
    ('ATP', 'atlanta open'): ('ATP_250', 'Hard', 'atlanta'),
    ('ATP', 'australian open'): ('GRAND_SLAM', 'Hard', 'melbourne'),
    ('ATP', 'barcelona open'): ('ATP_500', 'Clay', 'barcelona'),
    ('ATP', 'belgrade open'): ('ATP_250', 'Hard', 'belgrade'),
    ('ATP', 'bmw open'): ('ATP_250', 'Clay', 'munich'),
    ('ATP', 'bnp paribas masters'): ('ATP_1000', 'Hard', 'paris'),
    ('ATP', 'bnp paribas open'): ('ATP_1000', 'Hard', 'indian wells'),
    ('ATP', 'brisbane international'): ('ATP_250', 'Hard', 'brisbane'),
    ('ATP', 'canadian open'): ('ATP_1000', 'Hard', 'montreal'),
    ('ATP', 'chengdu open'): ('ATP_250', 'Hard', 'chengdu'),
    ('ATP', 'chile open'): ('ATP_250', 'Clay', 'santiago'),
    ('ATP', 'china open'): ('ATP_500', 'Hard', 'beijing'),
    ('ATP', 'citi open'): ('ATP_500', 'Hard', 'washington'),
    ('ATP', 'cordoba open'): ('ATP_250', 'Clay', 'cordoba'),
    ('ATP', 'croatia open'): ('ATP_250', 'Clay', 'umag'),
    ('ATP', 'dallas open'): ('ATP_250', 'Hard', 'dallas'),
    ('ATP', 'delray beach open'): ('ATP_250', 'Hard', 'delray beach'),
    ('ATP', 'dubai tennis championships'): ('ATP_500', 'Hard', 'dubai'),
    ('ATP', 'eastbourne international'): ('ATP_250', 'Grass', 'eastbourne'),
    ('ATP', 'estoril open'): ('ATP_250', 'Clay', 'estoril'),
    ('ATP', 'european open'): ('ATP_250', 'Hard', 'antwerp'),
    ('ATP', 'firenze open'): ('ATP_250', 'Hard', 'florence'),
    ('ATP', 'french open'): ('GRAND_SLAM', 'Clay', 'paris'),
    ('ATP', 'generali open'): ('ATP_250', 'Clay', 'kitzbuhel'),
    ('ATP', 'geneva open'): ('ATP_250', 'Clay', 'geneva'),
    ('ATP', 'gijon open'): ('ATP_250', 'Hard', 'gijon'),
    ('ATP', 'grand prix hassan ii'): ('ATP_250', 'Clay', 'marrakech'),
    ('ATP', 'hall of fame championships'): ('ATP_250', 'Grass', 'newport'),
    ('ATP', 'halle open'): ('ATP_500', 'Grass', 'halle'),
    ('ATP', 'hangzhou open'): ('ATP_250', 'Hard', 'hangzhou'),
    ('ATP', 'hong kong tennis open'): ('ATP_250', 'Hard', 'hong kong'),
    ('ATP', 'internazionali bnl d italia'): ('ATP_1000', 'Clay', 'rome'),
    ('ATP', 'japan open tennis championships'): ('ATP_500', 'Hard', 'tokyo'),
    ('ATP', 'korea open'): ('ATP_250', 'Hard', 'seoul'),
    ('ATP', 'los cabos open'): ('ATP_250', 'Hard', 'los cabos'),
    ('ATP', 'lyon open'): ('ATP_250', 'Clay', 'lyon'),
    ('ATP', 'maharashtra open'): ('ATP_250', 'Hard', 'pune'),
    ('ATP', 'mallorca championships'): ('ATP_250', 'Grass', 'mallorca'),
    ('ATP', 'masters cup'): ('ATP_FINALS', 'Hard', 'turin'),
    ('ATP', 'melbourne summer set'): ('ATP_250', 'Hard', 'melbourne'),
    ('ATP', 'mercedes cup'): ('ATP_250', 'Grass', 'stuttgart'),
    ('ATP', 'miami open'): ('ATP_1000', 'Hard', 'miami'),
    ('ATP', 'millennium estoril open'): ('ATP_250', 'Clay', 'estoril'),
    ('ATP', 'monte carlo masters'): ('ATP_1000', 'Clay', 'monte carlo'),
    ('ATP', 'mutua madrid open'): ('ATP_1000', 'Clay', 'madrid'),
    ('ATP', 'napoli cup'): ('ATP_250', 'Hard', 'napoli'),
    ('ATP', 'nordea open'): ('ATP_250', 'Clay', 'bastad'),
    ('ATP', 'nordic open'): ('ATP_250', 'Hard', 'stockholm'),
    ('ATP', 'open 13'): ('ATP_250', 'Hard', 'marseille'),
    ('ATP', 'open de moselle'): ('ATP_250', 'Hard', 'metz'),
    ('ATP', 'open sud de france'): ('ATP_250', 'Hard', 'montpellier'),
    ('ATP', 'qatar exxon mobil open'): ('ATP_250', 'Hard', 'doha'),
    ('ATP', 'queen s club championships'): ('ATP_500', 'Grass', 'queens club'),
    ('ATP', 'rakuten japan open tennis championships'): ('ATP_500', 'Hard', 'tokyo'),
    ('ATP', 'rio open'): ('ATP_500', 'Clay', 'rio de janeiro'),
    ('ATP', 'rosmalen grass court championships'): ('ATP_250', 'Grass', 's hertogenbosch'),
    ('ATP', 'san diego open'): ('ATP_250', 'Hard', 'san diego'),
    ('ATP', 'serbia open'): ('ATP_250', 'Clay', 'belgrade'),
    ('ATP', 'shanghai masters'): ('ATP_1000', 'Hard', 'shanghai'),
    ('ATP', 'sofia open'): ('ATP_250', 'Hard', 'sofia'),
    ('ATP', 'srpska open'): ('ATP_250', 'Clay', 'banja luka'),
    ('ATP', 'stockholm open'): ('ATP_250', 'Hard', 'stockholm'),
    ('ATP', 'stuttgart open'): ('ATP_250', 'Grass', 'stuttgart'),
    ('ATP', 'suisse open gstaad'): ('ATP_250', 'Clay', 'gstaad'),
    ('ATP', 'swiss indoors'): ('ATP_500', 'Hard', 'basel'),
    ('ATP', 'sydney tennis classic'): ('ATP_250', 'Hard', 'sydney'),
    ('ATP', 'tel aviv open'): ('ATP_250', 'Hard', 'tel aviv'),
    ('ATP', 'tiriac open'): ('ATP_250', 'Clay', 'bucharest'),
    ('ATP', 'u s men s clay court championships'): ('ATP_250', 'Clay', 'houston'),
    ('ATP', 'us open'): ('GRAND_SLAM', 'Hard', 'new york'),
    ('ATP', 'vienna open'): ('ATP_500', 'Hard', 'vienna'),
    ('ATP', 'western southern financial group masters'): ('ATP_1000', 'Hard', 'cincinnati'),
    ('ATP', 'wimbledon'): ('GRAND_SLAM', 'Grass', 'london'),
    ('ATP', 'winston salem open at wake forest university'): ('ATP_250', 'Hard', 'winston salem'),
    ('ATP', 'zhuhai championships'): ('ATP_250', 'Hard', 'zhuhai'),
    ('WTA', 'abierto zapopan'): ('WTA_250', 'Hard', 'guadalajara'),
    ('WTA', 'abu dhabi wta women s tennis open'): ('WTA_500', 'Hard', 'abu dhabi'),
    ('WTA', 'adelaide international'): ('WTA_500', 'Hard', 'adelaide'),
    ('WTA', 'adelaide international 1'): ('WTA_500', 'Hard', 'adelaide'),
    ('WTA', 'adelaide international 2'): ('WTA_500', 'Hard', 'adelaide'),
    ('WTA', 'asb classic'): ('WTA_250', 'Hard', 'auckland'),
    ('WTA', 'atx open'): ('WTA_250', 'Hard', 'austin'),
    ('WTA', 'australian open'): ('GRAND_SLAM', 'Hard', 'melbourne'),
    ('WTA', 'bad homburg open'): ('WTA_250', 'Grass', 'bad homburg'),
    ('WTA', 'bett1open'): ('WTA_500', 'Grass', 'berlin'),
    ('WTA', 'bnp paribas open'): ('WTA_1000', 'Hard', 'indian wells'),
    ('WTA', 'brisbane international'): ('WTA_500', 'Hard', 'brisbane'),
    ('WTA', 'budapest open'): ('WTA_250', 'Clay', 'budapest'),
    ('WTA', 'canadian open'): ('WTA_1000', 'Hard', 'toronto'),
    ('WTA', 'championnats de granby'): ('WTA_250', 'Hard', 'granby'),
    ('WTA', 'charleston open'): ('WTA_500', 'Clay', 'charleston'),
    ('WTA', 'chennai open'): ('WTA_250', 'Hard', 'chennai'),
    ('WTA', 'china open'): ('WTA_1000', 'Hard', 'beijing'),
    ('WTA', 'citi open'): ('WTA_500', 'Hard', 'washington'),
    ('WTA', 'copa colsanitas'): ('WTA_250', 'Clay', 'bogota'),
    ('WTA', 'dubai duty free tennis championships'): ('WTA_1000', 'Hard', 'dubai'),
    ('WTA', 'eastbourne international'): ('WTA_500', 'Grass', 'eastbourne'),
    ('WTA', 'european open'): ('WTA_250', 'Clay', 'hamburg'),
    ('WTA', 'french open'): ('GRAND_SLAM', 'Clay', 'paris'),
    ('WTA', 'german open'): ('WTA_500', 'Grass', 'berlin'),
    ('WTA', 'grand prix sar lalla meryem'): ('WTA_250', 'Clay', 'rabat'),
    ('WTA', 'guadalajara open'): ('WTA_500', 'Hard', 'guadalajara'),
    ('WTA', 'guangzhou open'): ('WTA_250', 'Hard', 'guangzhou'),
    ('WTA', 'hobart international'): ('WTA_250', 'Hard', 'hobart'),
    ('WTA', 'hong kong tennis open'): ('WTA_250', 'Hard', 'hong kong'),
    ('WTA', 'iasi open'): ('WTA_250', 'Clay', 'iasi'),
    ('WTA', 'internationaux de strasbourg'): ('WTA_500', 'Clay', 'strasbourg'),
    ('WTA', 'internazionali bnl d italia'): ('WTA_1000', 'Clay', 'rome'),
    ('WTA', 'internazionali femminili di palermo'): ('WTA_250', 'Clay', 'palermo'),
    ('WTA', 'istanbul cup'): ('WTA_250', 'Clay', 'istanbul'),
    ('WTA', 'japan open'): ('WTA_250', 'Hard', 'osaka'),
    ('WTA', 'jasmin open'): ('WTA_250', 'Hard', 'monastir'),
    ('WTA', 'jiangxi open'): ('WTA_250', 'Hard', 'jiujiang'),
    ('WTA', 'jiangxi tennis open'): ('WTA_250', 'Hard', 'nanchang'),
    ('WTA', 'korea open'): ('WTA_500', 'Hard', 'seoul'),
    ('WTA', 'ladies linz open'): ('WTA_500', 'Hard', 'linz'),
    ('WTA', 'ladies open lausanne'): ('WTA_250', 'Clay', 'lausanne'),
    ('WTA', 'ladies trophy'): ('WTA_500', 'Hard', 'st petersburg'),
    ('WTA', 'lyon open'): ('WTA_250', 'Hard', 'lyon'),
    ('WTA', 'melbourne summer set 1'): ('WTA_250', 'Hard', 'melbourne'),
    ('WTA', 'melbourne summer set 2'): ('WTA_250', 'Hard', 'melbourne'),
    ('WTA', 'merida open'): ('WTA_250', 'Hard', 'merida'),
    ('WTA', 'miami open'): ('WTA_1000', 'Hard', 'miami'),
    ('WTA', 'monterrey open'): ('WTA_500', 'Hard', 'monterrey'),
    ('WTA', 'morocco open'): ('WTA_250', 'Clay', 'rabat'),
    ('WTA', 'mubadala silicon valley classic'): ('WTA_500', 'Hard', 'san jose'),
    ('WTA', 'mutua madrid open'): ('WTA_1000', 'Clay', 'madrid'),
    ('WTA', 'ningbo open'): ('WTA_500', 'Hard', 'ningbo'),
    ('WTA', 'nottingham open'): ('WTA_250', 'Grass', 'nottingham'),
    ('WTA', 'open de rouen'): ('WTA_250', 'Clay', 'rouen'),
    ('WTA', 'ostrava open'): ('WTA_500', 'Hard', 'ostrava'),
    ('WTA', 'parma ladies open'): ('WTA_250', 'Clay', 'parma'),
    ('WTA', 'poland open'): ('WTA_250', 'Clay', 'warsaw'),
    ('WTA', 'porsche tennis grand prix'): ('WTA_500', 'Clay', 'stuttgart'),
    ('WTA', 'prague open'): ('WTA_250', 'Clay', 'prague'),
    ('WTA', 'qatar open'): ('WTA_1000', 'Hard', 'doha'),
    ('WTA', 'rosmalen grass court championships'): ('WTA_250', 'Grass', 's hertogenbosch'),
    ('WTA', 'rothesay classic'): ('WTA_250', 'Grass', 'birmingham'),
    ('WTA', 'rothesay international'): ('WTA_500', 'Grass', 'eastbourne'),
    ('WTA', 'san diego open'): ('WTA_500', 'Hard', 'san diego'),
    ('WTA', 'slovenia open'): ('WTA_250', 'Hard', 'portoroz'),
    ('WTA', 'sydney tennis classic'): ('WTA_500', 'Hard', 'sydney'),
    ('WTA', 'tallinn open'): ('WTA_250', 'Hard', 'tallinn'),
    ('WTA', 'tennis in the land'): ('WTA_250', 'Hard', 'cleveland'),
    ('WTA', 'thailand open'): ('WTA_250', 'Hard', 'hua hin'),
    ('WTA', 'thailand open 2'): ('WTA_250', 'Hard', 'hua hin'),
    ('WTA', 'toray pan pacific open tennis tournament'): ('WTA_500', 'Hard', 'tokyo'),
    ('WTA', 'transylvania open'): ('WTA_250', 'Hard', 'cluj napoca'),
    ('WTA', 'us open'): ('GRAND_SLAM', 'Hard', 'new york'),
    ('WTA', 'western southern financial group women s open'): ('WTA_1000', 'Hard', 'cincinnati'),
    ('WTA', 'wimbledon'): ('GRAND_SLAM', 'Grass', 'london'),
    ('WTA', 'wuhan open'): ('WTA_1000', 'Hard', 'wuhan'),
    ('WTA', 'zhengzhou open'): ('WTA_500', 'Hard', 'zhengzhou'),
}
