"""Keep the history regression cases in the main Agent scripts test suite."""
import importlib.util
from pathlib import Path

path = Path(__file__).resolve().parents[1] / 'test_hkjc_fact_source_alignment.py'
spec = importlib.util.spec_from_file_location('history_cases', path)
cases = importlib.util.module_from_spec(spec)
spec.loader.exec_module(cases)


test_profile_join_uses_date_not_position = cases.test_profile_join_uses_date_not_position
test_stats_exclude_unknown_zero_and_future_with_audit = cases.test_stats_exclude_unknown_zero_and_future_with_audit
test_non_finish_status_is_retained_not_invented_as_last_place = cases.test_non_finish_status_is_retained_not_invented_as_last_place
test_rendered_history_does_not_shift_after_non_finish = cases.test_rendered_history_does_not_shift_after_non_finish
test_standby_runner_cannot_replace_declared_runner = cases.test_standby_runner_cannot_replace_declared_runner
test_withdrawn_racecard_runner_is_not_emitted_to_facts_field = cases.test_withdrawn_racecard_runner_is_not_emitted_to_facts_field
test_missing_profile_id_does_not_shift_later_horses = cases.test_missing_profile_id_does_not_shift_later_horses
test_cli_profile_override_preserves_empty_position = cases.test_cli_profile_override_preserves_empty_position
test_profile_history_adapter_prevents_false_debut = cases.test_profile_history_adapter_prevents_false_debut
test_cli_positional_ids_that_do_not_line_up_are_rejected = cases.test_cli_positional_ids_that_do_not_line_up_are_rejected
test_cli_ids_conflicting_with_formguide_brand_are_rejected = cases.test_cli_ids_conflicting_with_formguide_brand_are_rejected
test_status_classification = cases.test_status_classification
test_dnf_ends_a_layoff_but_withdrawal_and_unknown_do_not = cases.test_dnf_ends_a_layoff_but_withdrawal_and_unknown_do_not
test_missing_race_date_refuses_instead_of_leaking_later_runs = cases.test_missing_race_date_refuses_instead_of_leaking_later_runs
test_unverified_replacement_is_flagged_not_rendered_as_debut = cases.test_unverified_replacement_is_flagged_not_rendered_as_debut
test_habitual_early_position_is_pre_race_and_needs_two_runs = cases.test_habitual_early_position_is_pre_race_and_needs_two_runs
