#!/usr/bin/env python3
"""
generate_skeleton.py — V2 Analysis Skeleton Auto-Generator
===========================================================

Reads a Facts.md file (generated by inject_fact_anchors.py or
inject_hkjc_fact_anchors.py) and produces an Analysis.md skeleton with:
  - 📋 完整賽績檔案 tables pre-embedded (from Facts.md)
  - 📊 段速趨勢 + ⚡ EEM 能量摘要 pre-embedded
  - All analysis fields as [FILL] placeholders for the LLM
  - ★ V2: Pre-generated Final Verdict table (Part 3) to prevent drift

The LLM only needs to fill in the analytical sections, not copy data.

Usage:
    python3 generate_skeleton.py <Facts.md> [--output <Analysis.md>] [--batch-size 3]
        [--mode au|hkjc]   # auto-detected if not specified
"""
import re
import sys
from pathlib import Path


# ── Facts.md Parsers ─────────────────────────────────────────────────────

def detect_mode(text: str) -> str:
    """Auto-detect whether this is AU or HKJC format."""
    if '### 馬匹 #' in text:
        return 'au'
    elif '### 馬號' in text:
        return 'hkjc'
    return 'au'  # default


def parse_facts_md_au(text: str) -> list[dict]:
    """Parse AU-format Facts.md and extract per-horse blocks."""
    horse_pattern = re.compile(r'^### 馬匹 #(\d+) (.+?) \(檔位 (\d+)\)', re.MULTILINE)
    matches = list(horse_pattern.finditer(text))

    horses = []
    for i, match in enumerate(matches):
        num = int(match.group(1))
        name = match.group(2).strip()
        barrier = int(match.group(3))

        start = match.start()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        block = text[start:end].strip()

        anchor = _extract_between(block, '📌 事實錨點', '📋 完整賽績檔案')
        table = _extract_between(block, '📋 完整賽績檔案', '📊 段速趨勢')
        trends = _extract_between(block, '📊 段速趨勢', '⚡ EEM 能量摘要')
        eem = _extract_between(block, '⚡ EEM 能量摘要', '🔗 賽績線')
        formline = _extract_between(block, '🔗 賽績線', '🔧 引擎與距離')
        engine = _extract_from(block, '🔧 引擎與距離')

        horses.append({
            'num': num, 'name': name, 'barrier': barrier,
            'jockey': '', 'trainer': '', 'weight': 0,
            'anchor': anchor, 'table': table, 'trends': trends,
            'eem': eem, 'formline': formline, 'engine': engine,
            'mode': 'au',
        })

    return horses


def parse_facts_md_hkjc(text: str) -> list[dict]:
    """Parse HKJC-format Facts.md and extract per-horse blocks."""
    # Pattern: ### 馬號 1 — 智勝勳章 | 騎師: 奧爾民 | 練馬師: 方嘉柏 | 負磅: 134 | 檔位: 7
    horse_pattern = re.compile(
        r'^### 馬號 (\d+) — (.+?)(?:\s*\|)', re.MULTILINE
    )
    matches = list(horse_pattern.finditer(text))

    horses = []
    for i, match in enumerate(matches):
        num = int(match.group(1))
        name = match.group(2).strip()

        start = match.start()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        block = text[start:end].strip()

        # Extract header details
        header_line = block.split('\n')[0]
        jockey_m = re.search(r'騎師:\s*(\S+)', header_line)
        trainer_m = re.search(r'練馬師:\s*(\S+)', header_line)
        weight_m = re.search(r'負磅:\s*(\d+)', header_line)
        barrier_m = re.search(r'檔位:\s*(\d+)', header_line)

        jockey = jockey_m.group(1) if jockey_m else ''
        trainer = trainer_m.group(1) if trainer_m else ''
        weight = int(weight_m.group(1)) if weight_m else 0
        barrier = int(barrier_m.group(1)) if barrier_m else 0

        # Extract data blocks using different markers for HKJC format
        summary = _extract_between(block, '📌 **賽績總結', '📋 **完整賽績檔案')
        table = _extract_between(block, '📋 **完整賽績檔案', '📊 **段速趨勢')
        if '📋 **較舊歷史賽績' in table:
            table = table[:table.find('📋 **較舊歷史賽績')].strip()
        if not table:
            table = _extract_between(block, '📋 **完整賽績檔案', '🔧 **引擎距離')
            if '📋 **較舊歷史賽績' in table:
                table = table[:table.find('📋 **較舊歷史賽績')].strip()
        
        trends = _extract_between(block, '📊 **段速趨勢', '🔧 **引擎距離')
        engine = _extract_between(block, '🔧 **引擎距離', '📏 **頭馬距離')
        if not engine:
            engine = _extract_between(block, '🔧 **引擎距離', '💡 **LLM')
        
        # New dimensions
        margin_trend = _extract_between(block, '📏 **頭馬距離', '📊 **體重趨勢')
        weight_trend = _extract_between(block, '📊 **體重趨勢', '🔧 **配備變動')
        gear = _extract_between(block, '🔧 **配備變動', '📈 **評分變動')
        rating = _extract_between(block, '📈 **評分變動', '🏃 **走位 PI')
        pi = _extract_between(block, '🏃 **走位 PI', '🔗 **賽績線')
        if not pi:
            pi = _extract_between(block, '🏃 **走位 PI', '💡 **LLM')
        formline = _extract_between(block, '🔗 **賽績線', '💡 **LLM')

        # Combine new dimensions into one block
        new_dims = '\n'.join(filter(None, [margin_trend, weight_trend, gear, rating, pi]))

        horses.append({
            'num': num, 'name': name, 'barrier': barrier,
            'jockey': jockey, 'trainer': trainer, 'weight': weight,
            'summary': summary, 'table': table, 'trends': trends,
            'engine': engine, 'new_dims': new_dims, 'formline': formline,
            'mode': 'hkjc',
        })

    return horses


def _extract_between(block: str, start_marker: str, end_marker: str) -> str:
    """Extract text from line containing start_marker to line before end_marker."""
    start_idx = block.find(start_marker)
    if start_idx == -1:
        return ''
    line_start = block.rfind('\n', 0, start_idx)
    line_start = line_start + 1 if line_start != -1 else 0

    end_idx = block.find(end_marker, start_idx + len(start_marker))
    if end_idx == -1:
        return block[line_start:].strip()
    line_end = block.rfind('\n', 0, end_idx)
    if line_end <= line_start:
        return block[line_start:end_idx].strip()
    return block[line_start:line_end].strip()


def _extract_from(block: str, start_marker: str) -> str:
    """Extract text from line containing start_marker to end of block."""
    start_idx = block.find(start_marker)
    if start_idx == -1:
        return ''
    line_start = block.rfind('\n', 0, start_idx)
    line_start = line_start + 1 if line_start != -1 else 0
    return block[line_start:].strip()


# ── Skeleton Generators ──────────────────────────────────────────────────

def generate_horse_skeleton_hkjc(horse: dict) -> str:
    """Generate a HKJC analysis skeleton for one horse."""
    lines = []
    h = horse

    # Header
    jockey_str = h['jockey'] if h['jockey'] else '[FILL]'
    trainer_str = h['trainer'] if h['trainer'] else '[FILL]'
    weight_str = str(h['weight']) if h['weight'] else '[FILL]'

    lines.append(f"### 【No.{h['num']}】{h['name']} (檔位:{h['barrier']}) | "
                 f"騎師:{jockey_str} / 練馬師:{trainer_str} | 負重:{weight_str}lb | 評分:[FILL]")
    lines.append('**📌 情境標記:** `[FILL]`')
    lines.append('')

    # ⏱️ 近績解構
    lines.append('#### ⏱️ 近績解構')
    if h.get('summary'):
        lines.append(h['summary'])
    else:
        lines.append('- **近績序列:** `[FILL]` | **狀態週期:** `[FILL]`')
        lines.append('- **統計數據:** 季內 [FILL] | 同程 [FILL] | 同場同程 [FILL]')
    lines.append('- **趨勢總評:** [FILL]')
    lines.append('')

    # 📋 完整賽績檔案
    lines.append('#### 📋 完整賽績檔案')
    if h['table']:
        lines.append(h['table'])
    lines.append('')

    # 📊 段速趨勢
    if h.get('trends'):
        lines.append(h['trends'])
        lines.append('')

    # 🔧 引擎距離
    if h.get('engine'):
        lines.append(h['engine'])
        lines.append('')

    # New dimensions (margin/weight/gear/rating/PI)
    if h.get('new_dims'):
        lines.append(h['new_dims'])
        lines.append('')

    # 🐴 馬匹剖析
    lines.append('#### 🐴 馬匹剖析')
    lines.append('- **班次負重:** [FILL]')
    lines.append('- **引擎距離:** [FILL]')
    lines.append('- **步態場地:** [FILL]')
    lines.append('- **配備意圖:** [FILL]')
    lines.append('- **人馬組合:** [FILL]')
    lines.append('')



    # 🔗 賽績線
    if h.get('formline'):
        lines.append(h['formline'])
        lines.append('')

    # 🧭 陣型預判
    lines.append('#### 🧭 陣型預判')
    lines.append('- 預計守位 (800m 處):[FILL]，形勢 `[FILL]`')
    lines.append('')

    # ⚠️ 風險儀表板
    lines.append('#### ⚠️ 風險儀表板')
    lines.append('- 重大風險:`[FILL]` | 穩定指數:`[FILL]`')
    lines.append('')

    # 📊 評級矩陣
    lines.append('#### 📊 評級矩陣')
    lines.append('- **狀態與穩定性** [核心]: `[FILL]` | 理據: `[FILL]`')
    lines.append('- **段速與引擎** [核心]: `[FILL]` | 理據: `[FILL]`')
    lines.append('- **EEM與形勢** [半核心]: `[FILL]` | 理據: `[FILL]`')
    lines.append('- **騎練訊號** [半核心]: `[FILL]` | 理據: `[FILL]`')
    lines.append('- **級數與負重** [輔助]: `[FILL]` | 理據: `[FILL]`')
    lines.append('- **場地適性** [輔助]: `[FILL]` | 理據: `[FILL]`')
    lines.append('- **賽績線** [輔助]: `[FILL]` | 理據: `[FILL]`')
    lines.append('- **裝備與距離** [輔助]: `[FILL]` | 理據: `[FILL]`')
    lines.append('- **🔢 矩陣算術:** 核心✅=[FILL] | 半核心✅=[FILL] | 輔助✅=[FILL] | 總❌=[FILL] | 核心❌=[FILL] → 查表命中行=[FILL]')
    lines.append('- **基礎評級:** `[FILL]` | **規則**: `[FILL]`')
    lines.append('- **微調:** `[FILL]` | **觸發**: `[FILL]`')
    lines.append('- **覆蓋規則:** `[FILL]`')
    lines.append('')

    # 💡 核心邏輯與結論
    lines.append('#### 💡 核心邏輯與結論')
    lines.append('> [FILL — 核心邏輯為主體，必須涵蓋段速法醫 + EEM 走位 + 戰術推演]')
    lines.append('> - **核心邏輯:** [FILL — S/A ≥150字 | B ≥100字 | C/D ≥80字]')
    lines.append('> - **最大競爭優勢:** [FILL]')
    lines.append('> - **最大失敗風險:** [FILL]')
    lines.append('')
    lines.append('⭐ **最終評級:** `[FILL]`')
    lines.append('')

    return '\n'.join(lines)


def generate_horse_skeleton_au(horse: dict) -> str:
    """Generate an AU analysis skeleton for one horse (original logic)."""
    lines = []

    lines.append(f"### 【No.{horse['num']}】{horse['name']} (檔位:{horse['barrier']}) | 騎師:[FILL] / 練馬師:[FILL] | 負重:[FILL]kg | 評分:[FILL]")
    lines.append('**📌 情境標記:** `[FILL]`')
    lines.append('')

    lines.append('#### ⏱️ 近績解構')
    lines.append('- **近績序列:** `[FILL]` (剛戰 → 最舊) | **狀態週期:** `[FILL]`')
    lines.append('- **統計數據:** 季內 [FILL] | 同程 [FILL] | 同場同程 [FILL]')
    lines.append('- **趨勢總評:** [FILL]')
    lines.append('')

    lines.append('#### 📋 完整賽績檔案')
    if horse.get('table'):
        lines.append(horse['table'])
    lines.append('')

    if horse.get('trends'):
        lines.append(horse['trends'])
        lines.append('')
    if horse.get('eem'):
        lines.append(horse['eem'])
        lines.append('')

    lines.append('#### 🐴 馬匹剖析')
    lines.append('- **班次負重:** [FILL]')
    lines.append('- **引擎距離:** [FILL]')
    lines.append('- **步態場地:** [FILL]')
    lines.append('- **配備意圖:** [FILL]')
    lines.append('- **人馬組合:** [FILL]')
    lines.append('')


    if horse.get('formline'):
        lines.append(horse['formline'])
        lines.append('')

    lines.append('#### 🧭 陣型預判')
    lines.append('- 預計守位 (800m 處):[FILL]，形勢 `[FILL]`')
    lines.append('')

    lines.append('#### ⚠️ 風險儀表板')
    lines.append('- 重大風險:`[FILL]` | 穩定指數:`[FILL]`')
    lines.append('')

    lines.append('#### 📊 評級矩陣')
    lines.append('- **狀態與穩定性** [核心]: `[FILL]` | 理據: `[FILL]`')
    lines.append('- **段速與引擎** [核心]: `[FILL]` | 理據: `[FILL]`')
    lines.append('- **EEM與形勢** [半核心]: `[FILL]` | 理據: `[FILL]`')
    lines.append('- **騎練訊號** [半核心]: `[FILL]` | 理據: `[FILL]`')
    lines.append('- **級數與負重** [輔助]: `[FILL]` | 理據: `[FILL]`')
    lines.append('- **場地適性** [輔助]: `[FILL]` | 理據: `[FILL]`')
    lines.append('- **賽績線** [輔助]: `[FILL]` | 理據: `[FILL]`')
    lines.append('- **裝備與距離** [輔助]: `[FILL]` | 理據: `[FILL]`')
    lines.append('- **🔢 矩陣算術:** 核心✅=[FILL] | 半核心✅=[FILL] | 輔助✅=[FILL] | 總❌=[FILL] | 核心❌=[FILL] → 查表命中行=[FILL]')
    lines.append('- **基礎評級:** `[FILL]` | **規則**: `[FILL]`')
    lines.append('- **微調:** `[FILL]` | **觸發**: `[FILL]`')
    lines.append('- **覆蓋規則:** `[FILL]`')
    lines.append('')

    lines.append('#### 💡 核心邏輯與結論')
    lines.append('> [FILL — 核心邏輯為主體，必須涵蓋段速法醫 + EEM 走位 + 戰術推演]')
    lines.append('> - **核心邏輯:** [FILL — S/A ≥150字 | B ≥100字 | C/D ≥80字]')
    lines.append('> - **最大競爭優勢:** [FILL]')
    lines.append('> - **最大失敗風險:** [FILL]')
    lines.append('')
    lines.append('⭐ **最終評級:** `[FILL]`')
    lines.append('')

    return '\n'.join(lines)


# ── Final Verdict Template (Phase 5: Drift-Proof) ───────────────────────

def generate_final_verdict(horses: list[dict]) -> str:
    """Generate a pre-formatted Final Verdict section.
    
    This template is FIXED by Python — the LLM only fills [FILL] fields.
    Format drift is eliminated because the table structure is pre-generated.
    """
    lines = []

    lines.append('#### [第三部分] 最終預測 (The Verdict)\n')
    lines.append('- **跑道形勢:** [FILL]')
    lines.append('- **信心指數:** `[極高/高/中高/中/低]`')
    lines.append('- **關鍵變數:** [FILL]')
    lines.append('')
    lines.append('**🏆 Top 4 位置精選**\n')
    
    labels = ['🥇 **第一選**', '🥈 **第二選**', '🥉 **第三選**', '🏅 **第四選**']
    for label in labels:
        lines.append(f'{label}')
        lines.append('- **馬號及馬名:** [FILL]')
        lines.append('- **評級與✅數量:** `[FILL]` | ✅ [FILL]')
        lines.append('- **核心理據:** [FILL]')
        lines.append('- **最大風險:** [FILL]')
        lines.append('')

    lines.append('**🎯 Top 2 入三甲信心度 (Top 2 Place Confidence)**')
    lines.append('🥇 [FILL]:`[🟢極高 / 🟢高 / 🟡中 / 🔴低]` — 最大威脅:[FILL]')
    lines.append('🥈 [FILL]:`[🟢極高 / 🟢高 / 🟡中 / 🔴低]` — 最大威脅:[FILL]')
    lines.append('')
    
    lines.append('**🔄 步速逆轉保險 (Pace Flip Insurance)**')
    lines.append('- 若步速比預測更快 → 最受惠: [FILL] | 最受損: [FILL]')
    lines.append('- 若步速比預測更慢 → 最受惠: [FILL] | 最受損: [FILL]')
    lines.append('')
    
    lines.append('**🚨 緊急煞車檢查 (Emergency Brake Protocol)**')
    lines.append('[FILL]')
    lines.append('')
    lines.append('---')
    lines.append('')
    
    lines.append('#### [第四部分] 分析盲區(緊隨第三部分)\n')
    lines.append('**1. 段速含金量:** [FILL]')
    lines.append('**2. 風險管理:** [FILL]')
    lines.append('**3. 試閘與預期假象:** [FILL]')
    lines.append('**4. 特定與老馬風險:** [FILL]')
    lines.append('**5. 步速情境分支:**')
    lines.append('- 快步速:最利 → [FILL];最不利 → [FILL]')
    lines.append('- 慢步速:最利 → [FILL];最不利 → [FILL]')
    lines.append('')
    lines.append('**6. 🎯 步速崩潰冷門 (Pace Collapse Dark Horse) [強制檢查點]:**')
    lines.append('[FILL]')
    lines.append('')
    lines.append('**🐴⚡ 冷門馬總計 (Underhorse Signal Summary):**')
    lines.append('[FILL]')
    lines.append('')
    
    return '\n'.join(lines)


# ── Main ─────────────────────────────────────────────────────────────────

def main():
    import argparse as _ap
    parser = _ap.ArgumentParser(
        description='generate_skeleton.py V2 — 自動骨架生成器（從 Facts.md 嵌入數據 + Final Verdict 鎖定）'
    )
    parser.add_argument('facts', help='Facts.md 路徑')
    parser.add_argument('--output', '-o', default=None,
                        help='輸出 Analysis.md 路徑（默認 = 同目錄）')
    parser.add_argument('--batch-size', type=int, default=3,
                        help='每批馬匹數（默認 3）')
    parser.add_argument('--mode', choices=['au', 'hkjc'], default=None,
                        help='模式：au 或 hkjc（自動偵測）')
    args = parser.parse_args()

    facts_path = args.facts
    if not Path(facts_path).exists():
        print(f"❌ 找不到文件: {facts_path}")
        sys.exit(1)

    text = Path(facts_path).read_text(encoding='utf-8')
    mode = args.mode or detect_mode(text)

    if mode == 'hkjc':
        horses = parse_facts_md_hkjc(text)
    else:
        horses = parse_facts_md_au(text)

    if not horses:
        print("❌ Facts.md 中找不到馬匹")
        sys.exit(1)

    print(f"📝 模式: {mode.upper()} | 馬匹: {len(horses)}")

    # Generate skeleton
    body_lines = []

    # Part 1 placeholder
    body_lines.append('## [第一部分] 🗺️ 戰場全景')
    body_lines.append('')
    body_lines.append('[FILL — 由 LLM 填充]')
    body_lines.append('')
    body_lines.append('---')
    body_lines.append('')
    body_lines.append('## [第二部分] 🔬 深度顯微鏡')
    body_lines.append('')

    # Generate per-horse skeletons
    batch_size = args.batch_size
    skeleton_fn = generate_horse_skeleton_hkjc if mode == 'hkjc' else generate_horse_skeleton_au

    for i, horse in enumerate(horses):
        body_lines.append(skeleton_fn(horse))
        body_lines.append('---')
        body_lines.append('')

        # Batch compliance check
        batch_pos = (i % batch_size) + 1
        if batch_pos == batch_size or i == len(horses) - 1:
            done = i + 1
            body_lines.append(
                f'✅ 批次完成:{done}/{len(horses)} 馬匹 | '
                f'每匹含 ⏱️近績+📋賽績檔案+🐴剖析+🔗賽績線+🧭陣型+⚠️風險+📊矩陣+💡核心邏輯+⭐評級 全 9 欄位 | D 級馬 ≥300 字 ✔️'
            )
            body_lines.append('')

    # Part 3-5: Pre-generated Final Verdict (drift-proof)
    body_lines.append('---')
    body_lines.append('')
    body_lines.append(generate_final_verdict(horses))

    full_output = '\n'.join(body_lines)

    # Determine output path
    if args.output:
        output_path = Path(args.output)
    else:
        facts_dir = Path(facts_path).parent
        facts_name = Path(facts_path).stem
        out_name = facts_name.replace('Facts', 'Analysis')
        if out_name == facts_name:
            out_name = facts_name + ' Analysis'
        output_path = facts_dir / f"{out_name}.md"

    output_path.write_text(full_output, encoding='utf-8')
    print(f"✅ 骨架已生成 — {len(horses)} 匹馬")
    print(f"   已寫入 → {output_path}")
    print(f"   📋 完整賽績檔案已自動嵌入（LLM 無需複製）")
    print(f"   🏆 Final Verdict 表格已預生成（防漂移）")
    print(f"   🔍 LLM 只需填充 [FILL] 佔位符")


if __name__ == '__main__':
    main()
