#!/usr/bin/env python3
"""Fixed, full-matrix residual candidates scored with competitiveness gates.

This is not a boundary swap.  Every horse receives the same reliability-gated
dimension residual before the full field is reranked.  Candidate definitions
are fixed from domain hypotheses; no weight grid is searched.
"""
from __future__ import annotations

import csv
import json
import sys
from collections import Counter, defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / ".agents" / "skills" / "shared_racing"))
from eval_metrics import race_metrics, summarize_races  # noqa: E402


REPLAY = ROOT / "scratch" / "hkjc_prerace_replay.csv"
DIMENSIONS = ROOT / "scratch" / "hkjc_rebuilt_dimensions.csv"
OUTPUT = ROOT / "scratch" / "hkjc_competitiveness_residual_gate.json"
REPORT = ROOT / "scratch" / "hkjc_competitiveness_residual_gate_report.md"

CANDIDATES = {
    "trainer_5pct": {"trainer_signal": 0.05},
    "class_weight_5pct": {"class_weight": 0.05},
    "form_line_5pct": {"form_line": 0.05},
    "trainer_class_form_3pct": {
        "trainer_signal": 0.03,
        "class_weight": 0.03,
        "form_line": 0.03,
    },
    "broad_reliability_2pct": {
        "speed_engine": 0.02,
        "stability": 0.02,
        "distance_context": 0.02,
        "class_weight": 0.02,
        "trainer_signal": 0.02,
        "readiness_risk": 0.02,
        "form_line": 0.02,
    },
}
SPLITS = (
    "archive_development",
    "archive_temporal_holdout",
    "independent_recent",
    "external_2026_07_15",
)


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def row_key(row: dict[str, str]) -> tuple[str, str, str, str]:
    return row["dataset"], row["meeting"], row["race_number"], row["horse_number"]


def load() -> tuple[dict[tuple[str, str, str], list[dict]], dict[tuple[str, str, str, str], dict]]:
    dimension_rows = {row_key(row): row for row in read_csv(DIMENSIONS)}
    grouped: defaultdict[tuple[str, str, str], list[dict]] = defaultdict(list)
    for row in read_csv(REPLAY):
        grouped[(row["dataset"], row["meeting"], row["race_number"])].append(row)
    # Preserve the published order even where one archived meeting's stored
    # ability was generated by a later scorer version.
    for rows in grouped.values():
        previous = float("inf")
        for row in sorted(rows, key=lambda item: int(float(item["reference_original_rank"]))):
            raw = float(row["reference_original_ability"])
            row["_baseline_score"] = min(raw, previous - 0.001)
            previous = row["_baseline_score"]
    return dict(grouped), dimension_rows


def score(row: dict, dimensions: dict, candidate: str) -> float:
    value = float(row["_baseline_score"])
    if candidate == "published_baseline":
        return value
    dim = dimensions[row_key(row)]
    for name, weight in CANDIDATES[candidate].items():
        evidence = float(dim[f"dim_{name}"])
        reliability = float(dim[f"reliability_{name}"])
        value += weight * (evidence - 60.0) * reliability
    return value


def evaluate(races: list[list[dict]], dimensions: dict, candidate: str) -> dict:
    metrics = []
    for rows in races:
        ranked = sorted(
            rows,
            key=lambda row: (
                -score(row, dimensions, candidate),
                int(float(row["reference_original_rank"])),
                int(float(row["horse_number"])),
            ),
        )
        picks = [int(float(row["horse_number"])) for row in ranked]
        positions = {
            int(float(row["horse_number"])): int(float(row["label_finish_position"]))
            for row in ranked
        }
        top3 = [horse for horse, position in positions.items() if position <= 3]
        metrics.append(race_metrics(picks, top3, actual_pos=positions, field_size=len(positions)))
    summary = summarize_races(metrics)
    comp = summary["competitiveness"]
    distribution = Counter(row["top2_hits"] for row in metrics)
    return {
        "races": len(metrics),
        "zero_hit": distribution[0],
        "one_hit": distribution[1],
        "two_hit": distribution[2],
        "top3_capture_at5": round(comp["mean_top3_capture_at5"], 4),
        "top3_all_within_top5": round(comp["top3_all_within_top5"]["rate"], 4),
        "ndcg_at5": round(comp["mean_ndcg_at5"], 4),
        "winner_in_top5": round(summary["rates"]["winner_in_top5"], 4),
        "mrr": round(summary["mrr"], 4),
    }


def delta(candidate: dict, baseline: dict) -> dict:
    return {
        key: round(candidate[key] - baseline[key], 4)
        for key in candidate
        if key != "races"
    }


def gate(result: dict[str, dict]) -> dict:
    no_harm_metrics = (
        "top3_capture_at5",
        "top3_all_within_top5",
        "ndcg_at5",
        "winner_in_top5",
        "mrr",
    )
    all_split_no_harm = all(
        result[split]["delta"]["zero_hit"] <= 0
        and all(result[split]["delta"][metric] >= 0 for metric in no_harm_metrics)
        for split in SPLITS
    )
    aggregate = result["all"]["delta"]
    meaningful = aggregate["top3_capture_at5"] >= 0.002 and aggregate["ndcg_at5"] >= 0.002
    return {
        "passes": all_split_no_harm and meaningful,
        "all_split_no_harm": all_split_no_harm,
        "meaningful_aggregate_lift": meaningful,
    }


def main() -> int:
    grouped, dimensions = load()
    slices = {"all": list(grouped.values())}
    for split in SPLITS:
        slices[split] = [
            rows for rows in grouped.values()
            if rows[0]["split"] == split
        ]
    baseline = {
        split: evaluate(races, dimensions, "published_baseline")
        for split, races in slices.items()
    }
    results = {}
    gates = {}
    for candidate in CANDIDATES:
        candidate_result = {}
        for split, races in slices.items():
            metrics = evaluate(races, dimensions, candidate)
            candidate_result[split] = {
                "baseline": baseline[split],
                "candidate": metrics,
                "delta": delta(metrics, baseline[split]),
            }
        results[candidate] = candidate_result
        gates[candidate] = gate(candidate_result)
    payload = {
        "method": {
            "full_field_rerank": True,
            "micro_tiebreak": False,
            "blind_swap": False,
            "grid_search": False,
            "outcome_features_in_score": False,
            "reliability_gated_residual": "weight * (dimension - 60) * reliability",
        },
        "coverage": {
            "races": len(grouped),
            "meetings": len({key[1] for key in grouped}),
            "by_split": {split: len(races) for split, races in slices.items()},
        },
        "candidates": CANDIDATES,
        "results": results,
        "gates": gates,
        "recommendation": "HOLD_ALL" if not any(item["passes"] for item in gates.values()) else "PROMOTE_PASSING",
    }
    OUTPUT.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    lines = [
        "# HKJC Competitiveness Residual Gate",
        "",
        f"Recommendation: **{payload['recommendation']}**",
        "",
        "| Candidate | Pass | 全體 0-hit Δ | Top3@5 Δ | 全部前三@5 Δ | NDCG@5 Δ | Winner@5 Δ | MRR Δ |",
        "|---|:---:|---:|---:|---:|---:|---:|---:|",
    ]
    for candidate in CANDIDATES:
        item = results[candidate]["all"]["delta"]
        lines.append(
            f"| {candidate} | {'PASS' if gates[candidate]['passes'] else 'FAIL'} | "
            f"{item['zero_hit']:+.0f} | {item['top3_capture_at5']:+.4f} | "
            f"{item['top3_all_within_top5']:+.4f} | {item['ndcg_at5']:+.4f} | "
            f"{item['winner_in_top5']:+.4f} | {item['mrr']:+.4f} |"
        )
    REPORT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(json.dumps({"recommendation": payload["recommendation"], "gates": gates}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
