#!/usr/bin/env python3
"""
compile_analysis_template.py — V8 AU Output Compiler (JSON -> Markdown)
========================================================================

Takes a given `Facts.md` and a matching `Race_X_Logic.json` (generated by the LLM),
and compiles them into a perfectly formatted V6.4 `Analysis.md`.

Usage:
  python3 compile_analysis_template.py <Facts.md> <Logic.json> --output <Analysis.md>
"""

import sys
import os
import json
import argparse
from pathlib import Path
import re

def _truncate_table(table_str: str, max_rows: int = 5, race_forgiveness_list: list = None) -> str:
    lines = table_str.strip().split('\n')
    out_lines = []
    data_row_count = 0
    truncated = False
    
    if race_forgiveness_list is None:
        race_forgiveness_list = []
        
    for line in lines:
        is_table_row = line.strip().startswith('|') and line.strip().endswith('|')
        if is_table_row:
            clean_str = line.strip().replace('|', '').replace(' ', '').replace(':', '').replace('-', '')
            is_delimiter = len(clean_str) == 0 and '-' in line
            is_header = ('日期' in line or '#' in line) and not is_delimiter and data_row_count == 0
            
            if is_header or is_delimiter:
                modified_line = line
            else:
                forg_tag = race_forgiveness_list[data_row_count] if data_row_count < len(race_forgiveness_list) else '[-]'
                # Ensure it has brackets for safe markdown formatting
                if not forg_tag.startswith('['):
                    forg_tag = f"[{forg_tag}]"
                if forg_tag == '[-]':
                    forg_tag = "`[-]`"
                modified_line = line.replace('[需判定]', forg_tag)
                data_row_count += 1
            
            if is_header or is_delimiter:
                out_lines.append(modified_line)
            else:
                if data_row_count <= max_rows:
                    out_lines.append(modified_line)
                else:
                    truncated = True
        else:
            if truncated and "> *(...空間所限" not in out_lines[-1]:
                out_lines.append("> *(...空間所限，只截取最前 5 場；研讀完整紀錄請強烈參考 Facts.md...)*")
                truncated = False
            out_lines.append(line)
            
    if truncated and "> *(...空間所限" not in out_lines[-1]:
        out_lines.append("> *(...空間所限，只截取最前 5 場；研讀完整紀錄請強烈參考 Facts.md...)*")
        
    return '\n'.join(out_lines)

def parse_facts_md_au(text: str) -> list[dict]:
    horse_pattern = re.compile(r'^### 馬匹 #(\d+) (.+?) \(檔位 (\d+)\)(?: \| 騎師: ([^|]+) \| 練馬師: (.+))?', re.MULTILINE)
    matches = list(horse_pattern.finditer(text))
    horses = []
    for i, match in enumerate(matches):
        start = match.start()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        block = text[start:end].strip()
        
        def _extract(start_m, end_m):
            s_idx = block.find(start_m)
            if s_idx == -1: return ''
            e_idx = block.find(end_m, s_idx)
            if e_idx == -1: return block[s_idx:].strip()
            return block[s_idx:e_idx].strip()
            
        table = _extract('📋 完整賽績檔案', '\n- **📊 段速趨勢')
        trends = _extract('📊 段速趨勢', '\n- **⚡ EEM 能量摘要')
        eem = _extract('⚡ EEM 能量摘要', '\n- **🔗 賽績線')
        formline = _extract('🔗 賽績線', '\n- **🔧 引擎與距離')
        engine = _extract('🔧 引擎與距離', '\n=')
        
        recent_form_m = re.search(r'近績序列解讀[：:]\s*`?([0-9xX\-]+)`?', block)
        if not recent_form_m:
            recent_form_m = re.search(r'Last 10 字串:\s*`?([0-9xX]+)`?', block)
        recent_form = recent_form_m.group(1).replace('-', '') if recent_form_m else '[詳見下方賽績表]'
        
        jockey = match.group(4).strip() if match.group(4) else 'Unknown'
        trainer = match.group(5).strip() if match.group(5) else 'Unknown'
        
        horses.append({
            'num': int(match.group(1)), 
            'name': match.group(2).strip(), 
            'barrier': int(match.group(3)),
            'jockey': jockey,
            'trainer': trainer,
            'recent_form': recent_form,
            'table': table, 'trends': trends, 'eem': eem, 'formline': formline, 'engine': engine
        })
    return horses

def build_panorama(json_data, facts_path, facts_text):
    v = json_data.get('race_analysis', {})
    sm = v.get('speed_map', {})
    
    pace = sm.get('expected_pace', '[FILL]')
    leaders = ", ".join(sm.get('leaders', [])) or '[未指定]'
    on_pace = ", ".join(sm.get('on_pace', [])) or '[未指定]'
    mid = ", ".join(sm.get('mid_pack', [])) or '[未指定]'
    closers = ", ".join(sm.get('closers', [])) or '[未指定]'
    
    weather_going = "詳見 _Meeting_Intelligence_Package.md"
    bias = "按 Intelligence 判斷"
    race_class = "[未輸入]"
    
    # Extract Race Number
    race_num_m = re.search(r'Race\s*(\d+)', Path(facts_path).name, re.IGNORECASE)
    race_num = race_num_m.group(1) if race_num_m else "?"
    
    # Extract Distance
    dist_m = re.search(r'今仗距離:\s*(\d+m)', facts_text)
    distance = dist_m.group(1) if dist_m else "Unknown距離"
    
    try:
        meeting_dir = Path(facts_path).parent
        intel_path = meeting_dir / "_Meeting_Intelligence_Package.md"
        if intel_path.exists():
            intel_text = intel_path.read_text(encoding='utf-8')
            for line in intel_text.splitlines():
                if '場地' in line or '天氣' in line:
                    parts = line.split('：') if '：' in line else line.split(':')
                    if len(parts) > 1: weather_going = parts[-1].strip()
                elif '偏差' in line:
                    parts = line.split('：') if '：' in line else line.split(':')
                    if len(parts) > 1: bias = parts[-1].strip()
                elif re.search(rf'Race\s*{race_num}\s*(?:Class|Grade)[：:]', line, re.IGNORECASE):
                    parts = line.split('：') if '：' in line else line.split(':')
                    if len(parts) > 1: race_class = parts[-1].strip()
    except Exception:
        pass
    
    return f"""# Race {race_num} - {distance} - Class: {race_class}

## [第一部分] 🗺️ 戰場全景

| 項目 | 內容 |
|:---|:---|
| 賽事格局 | 參照上方標題 |
| **賽事類型** | **`[STANDARD RACE 標準彎道賽]`** |
| 距離與班次 | {distance} | Class: {race_class} |
| 天氣 / 場地 | {weather_going} |
| 跑道偏差 | {bias} |
| 步速預測 | {pace} |

**📍 Speed Map (速度地圖):**
- 領放群: {leaders}
- 前中段: {on_pace}
- 中後段: {mid}
- 後上群: {closers}

**🏃 步速瀑布推演 (Step 10 結論):**
- 預計步速: {pace}
"""

def generate_horse_section(horse_idx, h_fact, h_logic):
    lines = []
    
    rating = h_logic.get('rating', '[FILL]')
    core_logic = h_logic.get('core_logic', '[FILL]')
    fgv = h_logic.get('forgiveness', '無')
    risks = h_logic.get('risks', '無')
    # Header
    jockey_str = h_fact.get('jockey', 'Unknown')
    trainer_str = h_fact.get('trainer', 'Unknown')
    lines.append(f"### 【No.{h_fact['num']}】{h_fact['name']} (檔位:{h_fact['barrier']}) | 騎師: {jockey_str} | 練馬師: {trainer_str} | 評級: {rating}")
    lines.append(f"**📌 情境標記:** `{fgv}`\n")
    
    # QA placeholders
    lines.append('#### ⏱️ 近績解構')
    lines.append(f"- **近績序列:** `{h_fact.get('recent_form', '[詳見下方賽績表]')}`")
    lines.append(f"- **狀態週期:** `{h_logic.get('status_cycle', '平穩')}`")
    lines.append('')
    
    # 📋 完整賽績與寬恕檔案
    lines.append('#### 📋 完整賽績檔案')
    if h_fact.get('table'):
        race_forgiveness = h_logic.get('race_forgiveness', [])
        lines.append(_truncate_table(h_fact['table'], max_rows=5, race_forgiveness_list=race_forgiveness))
    lines.append('')
    if h_fact.get('trends'): lines.append('- **' + h_fact['trends'].strip() + '\n')
    if h_fact.get('eem'): lines.append('- **' + h_fact['eem'].strip() + '\n')
    if h_fact.get('formline'): lines.append('- **' + h_fact['formline'].strip() + '\n')
    if h_fact.get('engine'): lines.append('- **' + h_fact['engine'].strip() + '\n')
    
    # Rest of required QA sections
    lines.append('#### 🐴 馬匹剖析')
    lines.append(f"- **核心參數:** {rating} 級實力\n")
    
    lines.append('#### 🧭 陣型預判')
    lines.append(f"- 形勢: `[視乎起步]`\n")
    
    lines.append('#### ⚠️ 風險儀表板')
    lines.append(f"- 重大風險:`{risks}`\n")
    
    # 📊 評級矩陣
    lines.append('#### 📊 評級矩陣')
    
    matrix_keys = [
        ("狀態與穩定性", "核心"),
        ("段速與引擎", "核心"),
        ("EEM與形勢", "半核心"),
        ("騎練訊號", "半核心"),
        ("級數與負重", "輔助"),
        ("場地適性", "輔助"),
        ("賽績線", "輔助"),
        ("裝備與距離", "輔助")
    ]
    
    m_data = h_logic.get('matrix', {})
    
    core_check = 0
    core_fail = 0
    semi_check = 0
    aux_check = 0
    total_fail = 0
    
    for key, c_type in matrix_keys:
        item = m_data.get(key, {})
        score = item.get('score', '[-]').replace('✅','1').replace('❌','0')  # Fallback formatting just in case
        is_check = "✅" in item.get('score', '')
        is_fail = "❌" in item.get('score', '')
        
        if is_check:
            if c_type == "核心": core_check += 1
            if c_type == "半核心": semi_check += 1
            if c_type == "輔助": aux_check += 1
        if is_fail:
            total_fail += 1
            if c_type == "核心": core_fail += 1
            
        reason = item.get('_reasoning', item.get('reason', '無填寫理據'))
        score_display = item.get('score', '[-]')
        lines.append(f"- **{key}** [{c_type}]: `{score_display}` | 理據: {reason}")

    lines.append(f"- **編號矩陣:** 核心✅={core_check} | 半核心✅={semi_check} | 輔助✅={aux_check} | 總❌={total_fail} | 核心❌={core_fail}")
    lines.append('')
    
    lines.append('#### 💡 核心邏輯與結論')
    lines.append(f"> - **核心邏輯:** {core_logic}")
    lines.append(f"> - **最大失敗風險:** {risks}\n")
    
    lines.append(f"⭐ **最終評級:** `{rating}`\n")
    
    uh = h_logic.get('underhorse', {})
    uh_trig = "觸發" if uh.get('triggered') else "未觸發"
    lines.append(f"🐴⚡ **冷門馬訊號:** `{uh_trig}`")
    if uh_trig == "觸發":
        lines.append(f"- **受惠條件:** {uh.get('condition', '')}")
        lines.append(f"- **理由:** {uh.get('reason', '')}")
        
    return '\n'.join(lines)

def build_verdict(json_data, facts_horses):
    v = json_data.get('race_analysis', {}).get('verdict', {})
    
    horse_names = {h['num']: h['name'] for h in facts_horses}
    
    lines = []
    lines.append('## [第三部分] 🏆 全場最終決策')
    lines.append(f"**信心指數:** `{v.get('confidence', '[未定]')}`\n")
    
    lines.append('**Top 4 位置精選**\n')
    t4 = v.get('top4', [])
    labels = ['🥇 **第一選**', '🥈 **第二選**', '🥉 **第三選**', '🏅 **第四選**']
    for i, label in enumerate(labels):
        if i < len(t4):
            item = t4[i]
            h_num = item.get('horse_num', '')
            h_name = horse_names.get(int(h_num), '') if str(h_num).isdigit() else ''
            h_obj = json_data.get('horses', {}).get(str(h_num), {})
            h_rating = h_obj.get('rating', 'X')
            m_data = h_obj.get('matrix', {})
            core_check = sum(1 for m in m_data.values() if "✅" in m.get('score', ''))
            
            lines.extend([
                label,
                f"- **馬號及馬名:** [{h_num}] {h_name}",
                f"- **評級與✅數量:** `[{h_rating}]` | ✅ {core_check}",
                f"- **核心理據:** {item.get('reason', '')}",
                f"- **最大風險:** {item.get('risk', '')}\n"
            ])
            
    lines.append('---')
    lines.append('**🎯 Top 2 入三甲信心度 (Top 2 Place Confidence)**')
    lines.append('🥇 [1]:`[🟢高]` — 最大威脅:[2]')
    lines.append('🥈 [2]:`[🟢高]` — 最大威脅:[1]\n')
    
    lines.append('---')
    lines.append('**🔄 步速逆轉保險 (Pace Flip Insurance):**')
    fli = v.get('pace_flip_insurance', {})
    faster = fli.get('if_faster', {})
    slower = fli.get('if_slower', {})
    lines.append(f"- 若步速比預測更快 → 受惠: {faster.get('benefit', '')} | 受損: {faster.get('hurt', '')}")
    lines.append(f"- 若步速比預測更慢 → 受惠: {slower.get('benefit', '')} | 受損: {slower.get('hurt', '')}\n")
    
    lines.append('---')
    lines.append('## [第五部分] 📊 數據庫匯出 (CSV)\n')
    lines.append('```csv')
    lines.append('race_id,horse_number,horse_name,win_odds,place_odds,verdict,risk_level')
    lines.append('[FILL: 由 compute_rating_matrix.py 自動生成]')
    lines.append('```\n')
    return '\n'.join(lines)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("facts", help="Facts.md Path")
    parser.add_argument("logic_json", help="Logic.json Path")
    parser.add_argument("--output", required=True, help="Output Analysis.md Path")
    args = parser.parse_args()
    
    facts_text = Path(args.facts).read_text(encoding='utf-8')
    with open(args.logic_json, 'r', encoding='utf-8') as f:
        logic_data = json.load(f)
        
    facts_horses = parse_facts_md_au(facts_text)
    
    body = []
    body.append(build_panorama(logic_data, args.facts, facts_text))
    body.append('---\n## [第二部分] 🔬 深度顯微鏡\n\n')
    
    horses_logic_raw = logic_data.get('horses', [])
    horses_logic_dict = {}
    if isinstance(horses_logic_raw, list):
        for item in horses_logic_raw:
            if 'id' in item:
                horses_logic_dict[str(item['id'])] = item
    else:
        horses_logic_dict = horses_logic_raw

    for h in facts_horses:
        hl = horses_logic_dict.get(str(h['num']), {})
        if not hl:
            # Fallback if somehow not analyzed
            hl = {"rating": "[未分析]", "core_logic": "[查無JSON節點]", "matrix": {}}
            
        body.append(generate_horse_section(h['num'], h, hl))
        body.append('---\n')
        
    body.append(build_verdict(logic_data, facts_horses))
    
    Path(args.output).write_text('\n'.join(body), encoding='utf-8')
    print(f"✅ Analysis 組裝完成 → {args.output}")

if __name__ == '__main__':
    main()
