#!/usr/bin/env python3
import os
os.environ.setdefault('PYTHONUTF8', '1')
import sys
if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')
"""
compile_analysis_template.py — V8 AU Output Compiler (JSON -> Markdown)
========================================================================

Takes a given `Facts.md` and a matching `Race_X_Logic.json` (generated by the LLM),
and compiles them into a perfectly formatted V6.4 `Analysis.md`.

Usage:
  python3 compile_analysis_template.py <Facts.md> <Logic.json> --output <Analysis.md>
"""

import json
import argparse
from pathlib import Path
import re

# Import shared qualitative rating engine v2 (replaces deprecated grading_engine)
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "../../../../scripts")))
from rating_engine_v2 import compute_base_grade, compute_weighted_score, apply_fine_tune, parse_matrix_scores, grade_sort_index


def _auto_derive_trial_illusion(h_logic: dict) -> bool:
    """V9.5: Auto-derive trial_illusion from checklist answers.
    If primary_evidence_source='trial_only' or grade_without_trial='no_data',
    force trial_illusion=True regardless of what LLM set."""
    if h_logic.get('trial_illusion', False):
        return True  # Already set by LLM
    cl = h_logic.get('pre_analysis_checklist', {})
    if cl.get('primary_evidence_source') == 'trial_only':
        return True
    if cl.get('grade_without_trial') == 'no_data':
        return True
    return False


def _apply_scenario_caps(grade: str, h_logic: dict) -> str:
    """V9.5: Apply all scenario-based hard caps to a grade.
    Priority order (strictest first):
      P2 High: is_2yo, distance_wall, long_spell → cap A-
      P3 Medium: trial_illusion → cap B+
                 wet_track_tier=4 → cap A-, wet_track_tier=5 → cap B+
    """
    gi = grade_sort_index  # alias
    
    # P2: Scenario Caps (High)
    if h_logic.get('is_2yo', False) and gi(grade) < gi('A-'):
        grade = 'A-'
    if h_logic.get('distance_wall', False) and gi(grade) < gi('A-'):
        grade = 'A-'
    if h_logic.get('long_spell', False) and gi(grade) < gi('A-'):
        grade = 'A-'
    
    # P3: Scenario Caps (Medium)
    trial_illusion = _auto_derive_trial_illusion(h_logic)
    if trial_illusion and gi(grade) < gi('B+'):
        grade = 'B+'
    
    wet_tier = h_logic.get('wet_track_tier', 0)
    if wet_tier == 4 and gi(grade) < gi('A-'):
        grade = 'A-'
    elif wet_tier == 5 and gi(grade) < gi('B+'):
        grade = 'B+'
    
    return grade

def _truncate_table(table_str: str, max_rows: int = 5, race_forgiveness_list: list = None) -> str:
    lines = table_str.strip().split('\n')
    out_lines = []
    data_row_count = 0
    truncated = False
    
    if race_forgiveness_list is None:
        race_forgiveness_list = []
        
    for line in lines:
        is_table_row = line.strip().startswith('|') and line.strip().endswith('|')
        if is_table_row:
            clean_str = line.strip().replace('|', '').replace(' ', '').replace(':', '').replace('-', '')
            is_delimiter = len(clean_str) == 0 and '-' in line
            is_header = ('日期' in line or '#' in line) and not is_delimiter and data_row_count == 0
            
            if is_header or is_delimiter:
                modified_line = line
            else:
                forg_tag = race_forgiveness_list[data_row_count] if data_row_count < len(race_forgiveness_list) else '[-]'
                # Ensure it has brackets for safe markdown formatting
                if not forg_tag.startswith('['):
                    forg_tag = f"[{forg_tag}]"
                if forg_tag == '[-]':
                    forg_tag = "`[-]`"
                modified_line = line.replace('[需判定]', forg_tag)
                data_row_count += 1
            
            if is_header or is_delimiter:
                out_lines.append(modified_line)
            else:
                if data_row_count <= max_rows:
                    out_lines.append(modified_line)
                else:
                    truncated = True
        else:
            if truncated and "> *(...空間所限" not in out_lines[-1]:
                out_lines.append("> *(...空間所限，只截取最前 5 場；研讀完整紀錄請強烈參考 Facts.md...)*")
                truncated = False
            out_lines.append(line)
            
    if truncated and "> *(...空間所限" not in out_lines[-1]:
        out_lines.append("> *(...空間所限，只截取最前 5 場；研讀完整紀錄請強烈參考 Facts.md...)*")
        
    return '\n'.join(out_lines)

def parse_facts_md_au(text: str) -> list[dict]:
    horse_pattern = re.compile(r'^### 馬匹 #(\d+) (.+?) \(檔位 (\d+)\)(?: \| 騎師: ([^|]+) \| 練馬師: (.+))?', re.MULTILINE)
    matches = list(horse_pattern.finditer(text))
    horses = []
    for i, match in enumerate(matches):
        start = match.start()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        block = text[start:end].strip()
        
        def _extract(start_m, end_m):
            s_idx = block.find(start_m)
            if s_idx == -1: return ''
            e_idx = block.find(end_m, s_idx)
            if e_idx == -1: return block[s_idx:].strip()
            return block[s_idx:e_idx].strip()
            
        table = _extract('📋 完整賽績檔案', '\n- **📊 段速趨勢')
        trends = _extract('📊 段速趨勢', '\n- **⚡ EEM 能量摘要')
        eem = _extract('⚡ EEM 能量摘要', '\n- **🔗 賽績線')
        formline = _extract('🔗 賽績線', '\n- **🔧 引擎與距離')
        engine = _extract('🔧 引擎與距離', '\n=')
        
        recent_form_m = re.search(r'近績序列解讀[：:]\s*`?([0-9xX\-]+)`?', block)
        if not recent_form_m:
            recent_form_m = re.search(r'Last 10 字串:\s*`?([0-9xX]+)`?', block)
        recent_form = recent_form_m.group(1).replace('-', '') if recent_form_m else '[詳見下方賽績表]'
        
        jockey = match.group(4).strip() if match.group(4) else 'Unknown'
        trainer = match.group(5).strip() if match.group(5) else 'Unknown'
        
        horses.append({
            'num': int(match.group(1)), 
            'name': match.group(2).strip(), 
            'barrier': int(match.group(3)),
            'jockey': jockey,
            'trainer': trainer,
            'recent_form': recent_form,
            'table': table, 'trends': trends, 'eem': eem, 'formline': formline, 'engine': engine
        })
    return horses

def build_panorama(json_data, facts_path, facts_text, facts_horses=None):
    v = json_data.get('race_analysis', {})
    sm = v.get('speed_map', {})
    
    # Build num→name lookup
    num_to_name = {}
    if facts_horses:
        num_to_name = {str(h['num']): h['name'] for h in facts_horses}
    
    def _map_names(num_list):
        if isinstance(num_list, str):
            num_list = [x.strip() for x in num_list.replace('、', ',').split(',')]
        elif isinstance(num_list, list):
            flat = []
            for item in num_list:
                if isinstance(item, str) and ',' in item:
                    flat.extend([x.strip() for x in item.split(',')])
                elif isinstance(item, str) and '、' in item:
                    flat.extend([x.strip() for x in item.split('、')])
                else:
                    flat.append(str(item).strip())
            num_list = flat

        parts = []
        for n in num_list:
            if not n: continue
            name = num_to_name.get(str(n), '')
            parts.append(f'[{n}] {name}' if name else str(n))
        return ', '.join(parts) or '[未指定]'
    
    pace = sm.get('expected_pace', '[FILL]')
    leaders = _map_names(sm.get('leaders', []))
    on_pace = _map_names(sm.get('on_pace', []))
    mid = _map_names(sm.get('mid_pack', []))
    closers = _map_names(sm.get('closers', []))
    
    weather_going = "詳見 _Meeting_Intelligence_Package.md"
    bias = "按 Intelligence 判斷"
    race_class = "[未輸入]"
    tactical_nodes = sm.get('tactical_nodes', '[未提供]')
    if not tactical_nodes: tactical_nodes = '[未提供]'
    collapse = sm.get('collapse_point', '[未提供]')
    if not collapse: collapse = '[未提供]'
    
    # Extract Race Number
    race_num_m = re.search(r'Race\s*(\d+)', Path(facts_path).name, re.IGNORECASE)
    race_num = race_num_m.group(1) if race_num_m else "?"
    
    # Extract Distance — prefer Facts.md header, fallback to Racecard header
    dist_m = re.search(r'今仗距離:\s*(\d+m)', facts_text)
    distance = dist_m.group(1) if dist_m else "Unknown距離"
    
    # Extract Class and Distance from Racecard header (e.g. "RACE 1 — 900m | Maiden SW | $75,000")
    try:
        meeting_dir = Path(facts_path).parent
        rc_candidates = [f for f in meeting_dir.iterdir() if f"Race {race_num}" in f.name and "Racecard" in f.name]
        if rc_candidates:
            rc_header = rc_candidates[0].read_text(encoding='utf-8').splitlines()[0]
            # Extract class from header
            class_from_rc = re.search(r'\d+m\s*\|\s*([^|$]+?)(?:\s*\||\s*$)', rc_header)
            if class_from_rc and race_class == "[未輸入]":
                race_class = class_from_rc.group(1).strip()
            # Extract distance from header as backup
            dist_from_rc = re.search(r'[—–-]\s*(\d{3,5})m', rc_header)
            if dist_from_rc and distance == "Unknown距離":
                distance = f"{dist_from_rc.group(1)}m"
    except Exception:
        pass
    
    try:
        meeting_dir = Path(facts_path).parent
        intel_path = meeting_dir / "_Meeting_Intelligence_Package.md"
        if intel_path.exists():
            intel_text = intel_path.read_text(encoding='utf-8')
            for line in intel_text.splitlines():
                if '場地' in line or '天氣' in line:
                    parts = line.split('：') if '：' in line else line.split(':')
                    if len(parts) > 1: weather_going = parts[-1].strip()
                elif '偏差' in line:
                    parts = line.split('：') if '：' in line else line.split(':')
                    if len(parts) > 1: bias = parts[-1].strip()
                elif re.search(rf'Race\s*{race_num}\s*(?:Class|Grade)[：:]', line, re.IGNORECASE):
                    parts = line.split('：') if '：' in line else line.split(':')
                    if len(parts) > 1: race_class = parts[-1].strip()
    except Exception:
        pass
    
    pace_details = (
        f"- **預計步速:** {pace}\n"
        f"- **跑道偏差:** {bias}\n"
        f"- **戰術節點:** {tactical_nodes}\n"
        f"- **崩潰點:** {collapse}"
    )
    
    return f"""# Race {race_num} - {distance} - Class: {race_class}

## [第一部分] 🗺️ 戰場全景

| 項目 | 內容 |
|:---|:---|
| 賽事格局 | 參照上方標題 |
| **賽事類型** | **`[STANDARD RACE 標準彎道賽]`** |
| 距離與班次 | {distance} | Class: {race_class} |
| 天氣 / 場地 | {weather_going} |
| 跑道偏差 | {bias} |
| 步速預測 | {pace} |

**📍 Speed Map (速度地圖):**
- 領放群: {leaders}
- 前中段: {on_pace}
- 中後段: {mid}
- 後上群: {closers}

**🏃 步速瀑布推演 (Step 10 結論):**
{pace_details}
"""

def generate_horse_section(horse_idx, h_fact, h_logic):
    lines = []

    # ── Calculate with rating_engine_v2 (qualitative) ──
    matrix_keys_map = {
        "狀態與穩定性": "core", "段速與引擎": "core",
        "EEM與形勢": "semi", "騎練訊號": "semi",
        "級數與負重": "aux", "場地適性": "aux", 
        "賽績線": "aux", "裝備與距離": "aux",
    }
    m_data = h_logic.get('matrix', {})
    core_pass, semi_pass, aux_pass, core_fail, total_fail = parse_matrix_scores(m_data, matrix_keys_map)
    
    b_grade = compute_base_grade(core_pass, semi_pass, aux_pass, core_fail, total_fail, matrix_dims=m_data)
    w_score = compute_weighted_score(core_pass, semi_pass, aux_pass, core_fail, total_fail)
    
    ft = h_logic.get('fine_tune', {})
    ft_dir  = ft.get('direction', '無') if isinstance(ft, dict) else str(ft)
    final_rating = apply_fine_tune(b_grade, ft_dir)
    # V9.5: Apply all scenario caps (trial_illusion, is_2yo, long_spell, etc.)
    final_rating = _apply_scenario_caps(final_rating, h_logic)
    rating = b_grade # fall back for string formatting below
    core_logic = h_logic.get('core_logic', '[FILL]')
    advantages = h_logic.get('advantages', h_logic.get('competitive_advantage', '[缺失優勢]'))
    disadvantages = h_logic.get('disadvantages', h_logic.get('risks', h_logic.get('risk_level', '[缺失風險]')))
    fgv = h_logic.get('forgiveness', h_logic.get('scenario_tags', '無'))
    jockey_str = h_fact.get('jockey', 'Unknown')
    trainer_str = h_fact.get('trainer', 'Unknown')

    # ── 1. 馬匹標題 + 情境標記 ──────────────────────────────────────────
    lines.append(f"### 【No.{h_fact['num']}】{h_fact['name']} (檔位:{h_fact['barrier']}) | 騎師: {jockey_str} | 練馬師: {trainer_str} | 評級: {final_rating}")
    lines.append(f"**📌 情境標記:** `{fgv}`\n")

    # ── 2. 近績解構 ──────────────────────────────────────────────────────
    lines.append('#### ⏱️ 近績解構')
    lines.append(f"- **近績序列:** `{h_fact.get('recent_form', '[詳見下方賽績表]')}`")
    lines.append(f"- **狀態週期:** `{h_logic.get('status_cycle', '[FILL]')}`")
    lines.append(f"- **趨勢總評:** {h_logic.get('trend_summary', '[FILL]')}\n")

    # ── 3. 完整賽績檔案 (Facts，僅一次) ─────────────────────────────────
    lines.append('#### 📋 完整賽績檔案 (包含 Step 12 寬恕判斷)\n')
    if h_fact.get('table'):
        race_forgiveness = h_logic.get('race_forgiveness', [])
        lines.append(_truncate_table(h_fact['table'], max_rows=5, race_forgiveness_list=race_forgiveness))
    lines.append('')
    # Inject EEM + Trends from Facts (once, cleanly labelled)
    if h_fact.get('trends'):
        lines.append(h_fact['trends'].strip() + '\n')
    if h_fact.get('eem'):
        lines.append(h_fact['eem'].strip() + '\n')

    # ── 4. 馬匹剖析 (5 項 AU 標準) ──────────────────────────────────────
    h_analysis = h_logic.get('analytical_breakdown', {})
    lines.append('#### 🐴 馬匹剖析')
    lines.extend([
        f"- **班次負重:** {h_analysis.get('class_weight', '[FILL]')}",
        f"- **引擎距離 (Type A/B/C + Sire):** {h_analysis.get('engine_distance', '[FILL]')}",
        f"- **步態場地:** {h_analysis.get('track_surface_gait', '[FILL]')}",
        f"- **配備意圖:** {h_analysis.get('gear_intent', '[FILL]')}",
        f"- **人馬組合:** {h_analysis.get('jockey_trainer_combination', '[FILL]')}",
    ])
    lines.append('')

    # ── 5. 段速法醫 ──────────────────────────────────────────────────────
    sf = h_logic.get('sectional_forensic', {})
    lines.append('#### 🔬 段速法醫')
    lines.append(
        f"- **原始 L600/L400:** {sf.get('raw_L400', '[FILL]')} | "
        f"**修正因素:** {sf.get('correction_factor', '[FILL]')} | "
        f"**修正判斷:** {sf.get('corrected_assessment', '[FILL]')}"
    )
    lines.append(f"- **趨勢(近 3 仗):** `{sf.get('trend', '[FILL]')}`\n")

    # ── 6. EEM 能量 ───────────────────────────────────────────────────────
    eem = h_logic.get('eem_energy', {})
    lines.append('#### ⚡ EEM 能量')
    lines.append(f"- **上仗走位:** {eem.get('last_run_position', '[FILL]')}")
    lines.append(f"- **累積消耗:** `{eem.get('cumulative_drain', '[FILL]')}`")
    lines.append(f"- **總評:** {eem.get('assessment', '[FILL]')}\n")

    # ── 7. 寬恕認定 ───────────────────────────────────────────────────────
    forg = h_logic.get('forgiveness_archive', {})
    lines.append('#### 📋 寬恕認定')
    lines.append(f"- **因素:** {forg.get('factors', '[FILL]')}")
    lines.append(f"- **結論:** `{forg.get('conclusion', '[FILL]')}`\n")

    # ── 8. 賽績線 (Facts，僅一次) ────────────────────────────────────────
    if h_fact.get('formline'):
        lines.append('#### 🔗 賽績線\n')
        lines.append(h_fact['formline'].strip() + '\n')
        lines.append(f"- **綜合結論:** `{h_analysis.get('formline_strength', '[FILL]')}`\n")

    # ── 9. 陣型預判 ───────────────────────────────────────────────────────
    tactical = h_logic.get('tactical_plan', {})
    lines.append('#### 🧭 陣型預判')
    lines.append(f"- **預計守位:** {tactical.get('expected_position', '[FILL]')}")
    lines.append(f"- **形勢判定:** {tactical.get('race_scenario', '[FILL]')}\n")

    # ── 10. 風險儀表板 ────────────────────────────────────────────────────
    lines.append('#### ⚠️ 風險儀表板')
    lines.append(f"- **重大風險:** {disadvantages}")
    lines.append(f"- **穩定指數:** `{h_logic.get('stability_index', '[FILL]')}/10`\n")

    # ── 11. 評級矩陣 (8 AU 維度) + 5 級制 ────────────────────────────────
    lines.append('#### 📊 評級矩陣 (Step 14)')
    matrix_keys = [
        ("狀態與穩定性", "核心"),
        ("段速與引擎",   "核心"),
        ("EEM與形勢",    "半核心"),
        ("騎練訊號",     "半核心"),
        ("級數與負重",   "輔助"),
        ("場地適性",     "輔助"),
        ("賽績線",       "輔助"),
        ("裝備與距離",   "輔助"),
    ]
    m_data = h_logic.get('matrix', {})

    for key, c_type in matrix_keys:
        item = m_data.get(key, {})
        score_display = str(item.get('score', '[-]')).strip()
        reason = item.get('reasoning', item.get('_reasoning', item.get('reason', '無填寫理據')))
        lines.append(f"- **{key}** [{c_type}]: `{score_display}` | 理據: {reason}")

    lines.append('')

    # ── 12. 矩陣算術 ( rating_engine_v2 查表法 ) ───────────────────────────────
    cw = '有' if core_fail > 0 else '無'
    lines.append(f"**🔢 矩陣算術:** 核心✅={core_pass} | 半核心✅={semi_pass} | 輔助✅={aux_pass} | 總❌={total_fail} | 核心❌={cw} → 查表命中行={w_score}")

    # ── 13. 基礎評級 ─────────────────────────────────────────────────────
    lines.append(f"**14.2 基礎評級:** `{b_grade}` | `{w_score}`")

    # ── 14. 微調 (14.2B) ─────────────────────────────────────────────────
    ft = h_logic.get('fine_tune', {})
    ft_dir  = ft.get('direction', '無') if isinstance(ft, dict) else str(ft)
    # V9.5: Support new trigger_code + trigger_detail, fallback to legacy 'trigger'
    ft_code = ft.get('trigger_code', '') if isinstance(ft, dict) else ''
    ft_detail = ft.get('trigger_detail', '') if isinstance(ft, dict) else ''
    ft_trig_legacy = ft.get('trigger', '無') if isinstance(ft, dict) else '無'
    ft_trig = f"{ft_code} — {ft_detail}" if ft_code and ft_code != '無' else (ft_trig_legacy if ft_trig_legacy != '無' else '無')
    lines.append(f"**微調:** `{ft_dir}` | 觸發: `{ft_trig}`")

    # ── 15. 覆蓋規則 (14.3) ──────────────────────────────────────────────
    ovr = h_logic.get('override', {})
    ovr_rule = ovr.get('rule', '無') if isinstance(ovr, dict) else str(ovr)
    lines.append(f"**覆蓋規則:** `{ovr_rule}`\n")

    # ── 16. 核心邏輯 ─────────────────────────────────────────────────────
    lines.append('#### 💡 核心邏輯與結論')
    lines.append(f"> - **核心邏輯:** {core_logic}")
    lines.append(f"> - **最大競爭優勢:** {advantages}")
    lines.append(f"> - **最大失敗風險:** {disadvantages}\n")

    # ── 17. 法醫級推演錨點 (已移除 — V10) ────────────────────────────────

    # ── 17b. 場地雙軌評級 (UNSTABLE 時觸發) ──────────────────────────────
    dual = h_logic.get('dual_track', {})
    if dual and dual.get('triggered'):
        lines.append('#### 📗📙 場地雙軌評級')
        lines.append(f"- **草地評級:** `{dual.get('turf_rating', '[FILL]')}`")
        lines.append(f"- **全天候評級:** `{dual.get('awt_rating', '[FILL]')}`")
        lines.append(f"- **適用條件:** {dual.get('condition', '[FILL]')}\n")

    # ── 18. 最終評級 + 冷門馬 ────────────────────────────────────────────
    lines.append(f"⭐ **最終評級:** `{final_rating}`\n")

    uh = h_logic.get('underhorse', {})
    uh_trig = "觸發" if uh.get('triggered') else "未觸發"
    lines.append(f"🐴⚡ **冷門馬訊號:** `{uh_trig}`")
    if uh_trig == "觸發":
        lines.append(f"- **受惠條件:** {uh.get('condition', '')}")
        lines.append(f"- **理由:** {uh.get('reason', '')}")

    return '\n'.join(lines)

def build_verdict(json_data, facts_horses):
    v = json_data.get('race_analysis', {}).get('verdict', {})
    horse_names = {h['num']: h['name'] for h in facts_horses}
    horses_logic = json_data.get('horses', {})
    # Normalize if horses is a list
    if isinstance(horses_logic, list):
        horses_logic = {str(item.get('id', i)): item for i, item in enumerate(horses_logic)}

    # ── Grade computation for AU matrix format (using rating_engine_v2) ──
    def compute_au_grade(h_obj):
        matrix_keys_map = {
            "狀態與穩定性": "core", "段速與引擎": "core",
            "EEM與形勢": "semi", "騎練訊號": "semi",
            "級數與負重": "aux", "場地適性": "aux", 
            "賽績線": "aux", "裝備與距離": "aux",
        }
        m_data = h_obj.get('matrix', {})
        core_pass, semi_pass, aux_pass, core_fail, total_fail = parse_matrix_scores(m_data, matrix_keys_map)
        
        b_grade = compute_base_grade(core_pass, semi_pass, aux_pass, core_fail, total_fail, matrix_dims=m_data)
        w_score = compute_weighted_score(core_pass, semi_pass, aux_pass, core_fail, total_fail)
        
        ft = h_obj.get('fine_tune', {})
        ft_dir  = ft.get('direction', '無') if isinstance(ft, dict) else str(ft).upper()
        if ft_dir == 'UP': ft_dir = '+'
        elif ft_dir == 'DOWN': ft_dir = '-'
        
        f_grade = apply_fine_tune(b_grade, ft_dir)
        # V9.5: Apply all scenario caps
        f_grade = _apply_scenario_caps(f_grade, h_obj)
        return f_grade, w_score

    lines = []
    lines.append('## [第三部分] 🏆 全場最終決策')
    lines.append(f"**信心指數:** `{v.get('confidence', '[未定]')}`\n")
    lines.append('**🏆 Top 4 位置精選**\n')

    # ── AUTO-COMPUTE Top 4 from ALL horses' grades ──
    llm_picks = {}
    for item in v.get('top4', []):
        h_num = str(item.get('horse_num', item.get('horse_number', '')))
        llm_picks[h_num] = item

    all_graded = []
    for h_num_str, h_obj in horses_logic.items():
        grade, w_score = compute_au_grade(h_obj)
        grade_i = grade_sort_index(grade)
        all_graded.append((h_num_str, grade, grade_i, w_score))

    all_graded.sort(key=lambda x: (x[2], -x[3], int(x[0]) if x[0].isdigit() else 999))
    t4_auto = all_graded[:4]

    labels = ['🥇 **第一選**', '🥈 **第二選**', '🥉 **第三選**', '🏅 **第四選**']
    csv_rows = []
    top_nums = []

    for i, label in enumerate(labels):
        if i < len(t4_auto):
            h_num_str, grade, grade_i, w_score = t4_auto[i]
            h_num_int = int(h_num_str) if h_num_str.isdigit() else 0
            h_name = horse_names.get(h_num_int, '')
            h_obj = horses_logic.get(h_num_str, {})
            m_data = h_obj.get('matrix', {})
            core_check = sum(1 for m in m_data.values() if isinstance(m, dict) and "✅" in m.get('score', ''))
            jockey = next((hf['jockey'] for hf in facts_horses if str(hf['num']) == h_num_str), '')
            trainer = next((hf['trainer'] for hf in facts_horses if str(hf['num']) == h_num_str), '')

            if h_num_str in llm_picks:
                reason = llm_picks[h_num_str].get('reason', '')
                risk = llm_picks[h_num_str].get('risk', '')
            else:
                reason = h_obj.get('advantages', h_obj.get('competitive_advantage', '[自動選入]'))
                risk = h_obj.get('disadvantages', h_obj.get('risk_level', '[見分析]'))

            lines.extend([
                label,
                f"- **馬號及馬名:** [{h_num_str}] {h_name}",
                f"- **評級與✅數量:** `[{grade}]` | ✅ {core_check}",
                f"- **核心理據:** {reason}",
                f"- **最大風險:** {risk}\n"
            ])
            csv_rows.append(f"{h_num_str},{h_name},{jockey},{trainer},{grade},{reason[:40] if reason else ''}")
            top_nums.append(h_num_str)

    top1 = top_nums[0] if len(top_nums) > 0 else '?'
    top2 = top_nums[1] if len(top_nums) > 1 else '?'
    lines.extend([
        '---',
        '**🎯 Top 2 入三甲信心度 (Top 2 Place Confidence)**',
        f"🥇 [{top1}]:`[{v.get('top2_confidence_1', '🟢高')}]` — 最大威脅:[{top2}]",
        f"🥈 [{top2}]:`[{v.get('top2_confidence_2', '🟢高')}]` — 最大威脅:[{top1}]\n",
        '---',
        '**🔄 步速逆轉保險 (Pace Flip Insurance):**'
    ])

    fli = v.get('pace_flip_insurance', {})
    faster = fli.get('if_faster', {})
    slower = fli.get('if_slower', {})
    lines.append(f"- 若步速比預測更快 → 受惠: {faster.get('benefit', '[FILL]')} | 受損: {faster.get('hurt', '[FILL]')}")
    lines.append(f"- 若步速比預測更慢 → 受惠: {slower.get('benefit', '[FILL]')} | 受損: {slower.get('hurt', '[FILL]')}\n")

    # ── CSV 匯出 (真實數據) ───────────────────────────────────────────────
    lines.append('---')
    lines.append('## [第五部分] 📊 數據庫匯出 (CSV)\n')
    lines.append('```csv')
    lines.append('horse_num,horse_name,jockey,trainer,rating,core_reason_summary')
    if csv_rows:
        lines.extend(csv_rows)
    else:
        lines.append('[No Top 4 data in JSON verdict]')
    lines.append('```\n')
    
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("facts", help="Facts.md Path")
    parser.add_argument("logic_json", help="Logic.json Path")
    parser.add_argument("--output", required=True, help="Output Analysis.md Path")
    args = parser.parse_args()
    
    facts_text = Path(args.facts).read_text(encoding='utf-8')
    with open(args.logic_json, 'r', encoding='utf-8') as f:
        logic_data = json.load(f)
        
    facts_horses = parse_facts_md_au(facts_text)
    
    body = []
    body.append(build_panorama(logic_data, args.facts, facts_text, facts_horses))
    body.append('---\n## [第二部分] 🔬 深度顯微鏡\n\n')
    
    horses_logic_raw = logic_data.get('horses', [])
    horses_logic_dict = {}
    if isinstance(horses_logic_raw, list):
        for item in horses_logic_raw:
            if 'id' in item:
                horses_logic_dict[str(item['id'])] = item
    else:
        horses_logic_dict = horses_logic_raw

    # ── Compute grades and write back to JSON ──
    matrix_keys_map = {
        "狀態與穩定性": "core", "段速與引擎": "core",
        "EEM與形勢": "semi", "騎練訊號": "semi",
        "級數與負重": "aux", "場地適性": "aux", 
        "賽績線": "aux", "裝備與距離": "aux",
    }
    json_modified = False
    for h_key, h_logic in horses_logic_dict.items():
        m_data = h_logic.get('matrix', {})
        core_pass, semi_pass, aux_pass, core_fail, total_fail = parse_matrix_scores(m_data, matrix_keys_map)
        b_grade = compute_base_grade(core_pass, semi_pass, aux_pass, core_fail, total_fail, matrix_dims=m_data)
        ft = h_logic.get('fine_tune', {})
        ft_dir = ft.get('direction', '無') if isinstance(ft, dict) else str(ft)
        f_grade = apply_fine_tune(b_grade, ft_dir)
        # V9.5: Apply all scenario caps
        f_grade = _apply_scenario_caps(f_grade, h_logic)
        # Write computed grades back to JSON
        h_logic['base_rating'] = b_grade
        h_logic['final_rating'] = f_grade
        json_modified = True

    for h in facts_horses:
        hl = horses_logic_dict.get(str(h['num']), {})
        if not hl:
            # Fallback if somehow not analyzed
            hl = {"rating": "[未分析]", "core_logic": "[查無JSON節點]", "matrix": {}}
            
        body.append(generate_horse_section(h['num'], h, hl))
        body.append('---\n')
        
    body.append(build_verdict(logic_data, facts_horses))
    
    Path(args.output).write_text('\n'.join(body), encoding='utf-8')
    print(f"✅ Analysis 組裝完成 → {args.output}")

    # ── Write computed grades back to Logic.json ──
    if json_modified:
        with open(args.logic_json, 'w', encoding='utf-8') as f:
            json.dump(logic_data, f, ensure_ascii=False, indent=2)
        print(f"✅ 已回寫計算評級至 → {Path(args.logic_json).name}")

if __name__ == '__main__':
    main()

