#!/usr/bin/env python3
"""Backfill legacy AU Logic with point-in-time Sportsbet PQ evidence.

Dry-run is the default.  ``--apply`` writes only secondary recovery fields;
primary captured Performance Quality is never replaced.  The supplied sidecar
must have been generated by ``au_sportsbet_performance_quality_candidate.py``,
which censors every historical run whose date is not strictly before the target
meeting date.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from collections import Counter
from pathlib import Path
from statistics import mean, pstdev

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))
sys.path.insert(0, str(SCRIPT_DIR / "racing_engine"))

from au_archive_calibrator import (  # noqa: E402
    ARCHIVE_ROOT,
    detect_meeting_date,
    detect_meeting_track,
    get_true_horse_name,
    parse_int,
)
from au_sportsbet_performance_quality_candidate import (  # noqa: E402
    _identity,
    load_quality_cache,
)
from engine_core import clip_score  # noqa: E402
from io_utils import write_json_atomic  # noqa: E402

RECOVERY_KEYS = (
    "sportsbet_performance_quality_raw",
    "sportsbet_performance_quality_run_count",
    "sportsbet_performance_quality_source",
    "sportsbet_performance_quality_score",
    "sportsbet_performance_quality_runs",
)


def _race_payload(quality: dict, date: str, track: str, race_number: int) -> dict:
    prefix = (date, _identity(track), race_number)
    digests = {
        key[3]: digest for key, digest in quality.items()
        if key[:3] == prefix and int(digest.get("run_count") or 0) >= 2
    }
    values = [float(digest["raw"]) for digest in digests.values()]
    if len(values) < 3 or pstdev(values) <= 0:
        return {}
    field_mean, field_stdev = mean(values), pstdev(values)
    return {
        name: {
            "raw": float(digest["raw"]),
            "run_count": int(digest["run_count"]),
            "runs": digest.get("runs") or [],
            "score": clip_score(
                60.0 + 20.0 * (float(digest["raw"]) - field_mean) / field_stdev
            ),
        }
        for name, digest in digests.items()
    }


def backfill_archive(
    archive_root: Path,
    quality: dict,
    *,
    apply: bool = False,
    rollback: bool = False,
) -> dict:
    counts = Counter()
    changed_files = []
    # Completed meetings live under ``Archive/``.  Follow the Logic files and
    # group by their parent instead of assuming one directory depth; otherwise
    # the backfill and the canonical runtime audit silently operate on different
    # race populations.
    meeting_files: dict[Path, list[Path]] = {}
    for logic_path in archive_root.rglob("Race_*_Logic.json"):
        meeting_files.setdefault(logic_path.parent, []).append(logic_path)
    for meeting_dir in sorted(meeting_files, key=lambda path: str(path)):
        logic_files = sorted(meeting_files[meeting_dir])
        try:
            sample = json.loads(logic_files[0].read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            counts["meeting_sample_invalid"] += 1
            continue
        date = detect_meeting_date(meeting_dir)
        track = detect_meeting_track(meeting_dir, sample)
        if not date or not track:
            counts["meeting_identity_missing"] += 1
            continue
        counts["meetings"] += 1
        for logic_path in logic_files:
            counts["logic_files"] += 1
            try:
                logic = json.loads(logic_path.read_text(encoding="utf-8"))
            except (OSError, json.JSONDecodeError):
                counts["logic_invalid"] += 1
                continue
            analysis = logic.get("race_analysis") or {}
            race_number = (
                parse_int(analysis.get("race_number"))
                or parse_int(logic_path.stem.split("_")[1])
            )
            payload = (
                {} if rollback
                else _race_payload(quality, date, track, race_number)
            )
            if not rollback and not payload:
                counts["race_field_gate_failed"] += 1
                continue
            changed = False
            for horse in (logic.get("horses") or {}).values():
                if not isinstance(horse, dict):
                    continue
                counts["runners"] += 1
                data = horse.setdefault("_data", {})
                if rollback:
                    removed = sum(data.pop(key, None) is not None for key in RECOVERY_KEYS)
                    if removed:
                        counts["runners_rolled_back"] += 1
                        counts["fields_removed"] += removed
                        changed = True
                    continue
                if data.get("performance_quality_raw") is not None:
                    counts["primary_preserved"] += 1
                    continue
                recovered = payload.get(_identity(get_true_horse_name(horse)))
                if not recovered:
                    counts["runner_no_recovery"] += 1
                    continue
                desired = {
                    "sportsbet_performance_quality_raw": recovered["raw"],
                    "sportsbet_performance_quality_run_count": recovered["run_count"],
                    "sportsbet_performance_quality_source": (
                        "class_adjusted_margin_complete_formguide_point_in_time"
                    ),
                    "sportsbet_performance_quality_score": recovered["score"],
                    "sportsbet_performance_quality_runs": recovered["runs"],
                }
                if all(data.get(key) == value for key, value in desired.items()):
                    counts["already_current"] += 1
                    continue
                data.update(desired)
                counts["runners_recovered"] += 1
                changed = True
            if changed:
                counts["files_changed"] += 1
                changed_files.append(str(logic_path))
                if apply:
                    write_json_atomic(logic_path, logic)
    return {
        "mode": "rollback" if rollback else ("apply" if apply else "dry-run"),
        "archive_root": str(archive_root),
        "counts": dict(counts),
        "changed_files": changed_files,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--archive-root", type=Path, default=ARCHIVE_ROOT)
    parser.add_argument(
        "--sidecar", type=Path,
        help="Point-in-time recovery sidecar (required unless --rollback).",
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--apply", action="store_true")
    mode.add_argument(
        "--rollback", action="store_true",
        help="Remove only the five secondary recovery fields written by this tool.",
    )
    parser.add_argument(
        "--report", type=Path,
        default=Path("/private/tmp/au_sportsbet_pq_backfill_report.json"),
    )
    args = parser.parse_args()
    if args.rollback:
        quality, extraction = {}, {}
    else:
        cached = load_quality_cache(args.sidecar) if args.sidecar else None
        if not cached:
            raise SystemExit(f"Invalid or missing sidecar: {args.sidecar}")
        quality, extraction = cached
    report = backfill_archive(
        args.archive_root,
        quality,
        apply=args.apply or args.rollback,
        rollback=args.rollback,
    )
    report["sidecar"] = str(args.sidecar) if args.sidecar else None
    report["sidecar_records"] = len(quality)
    report["extraction"] = extraction
    write_json_atomic(args.report, report)
    display = dict(report)
    display["changed_files"] = (
        f"{len(report['changed_files'])} paths; full list in {args.report}"
    )
    print(json.dumps(display, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
