#!/usr/bin/env python3
"""Leakage-safe AU Wong Choi WIN/PLACE betting-strategy backtest.

The model ranking is frozen before prices and outcomes are joined.  A strategy
may use the morning price as a decision-time gate and may later settle at BSP,
but it may never use BSP to decide whether the bet existed.

The historical score snapshot adapter exists so old research assets remain
auditable.  Every report labels and fingerprints that snapshot; it must not be
described as the current RacingEngine unless it was generated by the current
runtime audit.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import json
import math
import random
import re
from collections import defaultdict
from dataclasses import asdict, dataclass
from pathlib import Path
from statistics import mean
from typing import Callable, Iterable

SCRIPT_DIR = Path(__file__).resolve().parent

COMMISSION = 0.05
MIN_PRICE = 1.01
MAX_PRICE = 1000.0
ODDS_THRESHOLDS = (1.0, 1.5, 2.0, 2.5, 3.0, 4.0, 5.0)
GAP_THRESHOLDS = (None, 1.0, 2.0)
RANK_SCOPES = ("top1", "top2", "both")
MARKETS = ("win", "place")
EXECUTIONS = ("morning", "bsp")


def normalize_name(value: object) -> str:
    text = re.sub(r"^\s*\d+\.?\s*", "", str(value or "").lower())
    return re.sub(r"[^a-z0-9]", "", text)


def normalize_venue(value: object) -> str:
    text = re.sub(r"[^a-z0-9]", "", str(value or "").lower())
    aliases = {
        "rosehillgardens": "rosehill",
        "sandownlakeside": "sandown",
        "sandownhillside": "sandown",
        "caulfieldheath": "caulfield",
        "ballaratsynthetic": "ballarat",
        "randwickkensington": "kensington",
        "royalrandwick": "randwick",
    }
    return aliases.get(text, text)


def as_float(value: object) -> float | None:
    try:
        number = float(value)
    except (TypeError, ValueError):
        return None
    return number if math.isfinite(number) else None


def valid_price(value: object) -> float | None:
    number = as_float(value)
    if number is None or number <= MIN_PRICE or number > MAX_PRICE:
        return None
    return number


def parse_event_date(value: object) -> str | None:
    match = re.match(r"(\d{2})-(\d{2})-(\d{4})", str(value or ""))
    if not match:
        return None
    return f"{match.group(3)}-{match.group(2)}-{match.group(1)}"


def parse_menu_venue(value: object) -> str | None:
    match = re.match(r"(.+?)\s+\(AUS\)", str(value or ""))
    return normalize_venue(match.group(1)) if match else None


def parse_race_number(value: object) -> int | None:
    match = re.match(r"\s*R(\d+)\b", str(value or ""), re.I)
    return int(match.group(1)) if match else None


def parse_meeting_identity(value: object) -> tuple[str | None, str | None]:
    text = str(value or "").strip()
    date_match = re.match(r"(\d{4}-\d{2}-\d{2})\s+(.+)", text)
    if not date_match:
        return None, None
    venue = re.sub(r"\s+Race\s+\d+\s*-\s*\d+\s*$", "", date_match.group(2))
    return date_match.group(1), normalize_venue(venue)


def race_type_bucket(event_name: object) -> str:
    text = str(event_name or "").lower()
    tail = re.sub(r"^\s*r\d+\s+\d+m\s*", "", text)
    if re.search(r"\b(g1|g2|g3|group|listed|lr)\b", tail):
        return "stakes"
    if re.search(r"\b(mdn|maiden)\b", tail):
        return "maiden"
    if re.search(r"\bbm\s*\d+", tail):
        return "benchmark"
    if re.search(r"\b(hcp|handicap)\b", tail):
        return "handicap"
    if re.search(r"\b(2yo|3yo)\b", tail):
        return "age_restricted"
    return "other"


def file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def source_fingerprint(paths: Iterable[Path]) -> dict:
    entries = []
    combined = hashlib.sha256()
    for path in sorted(paths, key=lambda item: str(item)):
        sha = file_sha256(path)
        entry = {
            "path": str(path.resolve()),
            "size": path.stat().st_size,
            "sha256": sha,
        }
        entries.append(entry)
        combined.update(json.dumps(entry, sort_keys=True).encode("utf-8"))
    return {
        "files": len(entries),
        "combined_sha256": combined.hexdigest(),
        "entries": entries,
    }


def _put_unique(
    index: dict,
    ambiguous: set,
    key: tuple,
    row: dict,
) -> None:
    prior = index.get(key)
    if prior is None and key not in ambiguous:
        index[key] = row
        return
    if prior and prior.get("event_id") == row.get("event_id"):
        prior_volume = as_float(prior.get("pptradedvol")) or 0.0
        volume = as_float(row.get("pptradedvol")) or 0.0
        if volume > prior_volume:
            index[key] = row
        return
    index.pop(key, None)
    ambiguous.add(key)


def load_market_index(betfair_dir: Path) -> tuple[dict, dict]:
    """Return strict (date, venue, race, horse) WIN/PLACE indexes.

    PLACE rows do not contain a race number.  They are bridged to the WIN
    market by venue, event timestamp and Betfair selection ID/name.
    """
    audit = defaultdict(int)
    win_index: dict[tuple, dict] = {}
    win_ambiguous: set[tuple] = set()
    bridge_id: dict[tuple, int] = {}
    bridge_name: dict[tuple, int] = {}
    win_files = sorted(betfair_dir.glob("dwbfpricesauswin*.csv"))
    place_files = sorted(betfair_dir.glob("dwbfpricesausplace*.csv"))

    for path in win_files:
        with path.open(encoding="utf-8-sig", errors="replace", newline="") as handle:
            for row in csv.DictReader(handle):
                audit["win_rows"] += 1
                date = parse_event_date(row.get("event_dt"))
                venue = parse_menu_venue(row.get("menu_hint"))
                race = parse_race_number(row.get("event_name"))
                horse = normalize_name(row.get("selection_name"))
                if not date or not venue or not race or not horse:
                    audit["win_invalid_identity"] += 1
                    continue
                key = (date, venue, race, horse)
                _put_unique(win_index, win_ambiguous, key, row)
                event_dt = str(row.get("event_dt") or "")
                selection_id = str(row.get("selection_id") or "")
                if selection_id:
                    bridge_id[(date, venue, event_dt, selection_id)] = race
                bridge_name[(date, venue, event_dt, horse)] = race

    place_index: dict[tuple, dict] = {}
    place_ambiguous: set[tuple] = set()
    for path in place_files:
        with path.open(encoding="utf-8-sig", errors="replace", newline="") as handle:
            for row in csv.DictReader(handle):
                audit["place_rows"] += 1
                date = parse_event_date(row.get("event_dt"))
                venue = parse_menu_venue(row.get("menu_hint"))
                event_dt = str(row.get("event_dt") or "")
                selection_id = str(row.get("selection_id") or "")
                horse = normalize_name(row.get("selection_name"))
                if not date or not venue or not horse:
                    audit["place_invalid_identity"] += 1
                    continue
                race = bridge_id.get((date, venue, event_dt, selection_id))
                if race is None:
                    race = bridge_name.get((date, venue, event_dt, horse))
                if race is None:
                    audit["place_unbridged_to_win_race"] += 1
                    continue
                _put_unique(
                    place_index,
                    place_ambiguous,
                    (date, venue, race, horse),
                    row,
                )

    audit.update(
        {
            "win_files": len(win_files),
            "place_files": len(place_files),
            "win_unique": len(win_index),
            "place_unique": len(place_index),
            "win_ambiguous": len(win_ambiguous),
            "place_ambiguous": len(place_ambiguous),
        }
    )
    for key in (
        "win_invalid_identity",
        "place_invalid_identity",
        "place_unbridged_to_win_race",
    ):
        audit.setdefault(key, 0)
    return {"win": win_index, "place": place_index}, dict(audit)


def _market_fields(row: dict | None, prefix: str) -> dict:
    if not row:
        return {
            f"{prefix}_morning": None,
            f"{prefix}_bsp": None,
            f"{prefix}_won": None,
        }
    return {
        f"{prefix}_morning": valid_price(row.get("morningwap")),
        f"{prefix}_bsp": valid_price(row.get("bsp")),
        f"{prefix}_won": str(row.get("win_lose") or "").strip() in {"1", "1.0"},
    }


def finalize_aligned_race(
    *,
    date: str,
    venue: str,
    race_no: int,
    aligned: list[dict],
    markets: dict,
    audit: defaultdict,
    race_class: object = None,
) -> dict | None:
    """Join prices after scoring, validate outcomes, then rank one race."""
    for row in aligned:
        key = (date, venue, race_no, normalize_name(row["horse_name"]))
        win_row = markets["win"].get(key)
        place_row = markets["place"].get(key)
        audit["win_joined" if win_row else "win_unmatched"] += 1
        audit["place_joined" if place_row else "place_unmatched"] += 1
        fields = {
            **_market_fields(win_row, "win"),
            **_market_fields(place_row, "place"),
        }
        if (
            fields["win_won"] is not None
            and bool(fields["win_won"]) != (row["finish"] == 1)
        ):
            audit["win_outcome_mismatch"] += 1
            fields.update(
                {"win_morning": None, "win_bsp": None, "win_won": None}
            )
        row.update(fields)
        row["_win_row"] = win_row

    if (
        len(aligned) < 4
        or sum(row["finish"] == 1 for row in aligned) != 1
        or sum(row["finish"] <= 3 for row in aligned) < 3
    ):
        audit["rejected_race_alignment"] += 1
        return None

    ranked = sorted(
        aligned,
        key=lambda row: (-row["score"], row["horse_number"]),
    )
    for rank, row in enumerate(ranked, 1):
        row["model_rank"] = rank
    top_gap = ranked[0]["score"] - ranked[1]["score"]
    event_row = next(
        (row["_win_row"] for row in ranked if row.get("_win_row")),
        None,
    )
    race_type_source = (
        race_class
        if present_race_class(race_class)
        else (event_row or {}).get("event_name")
    )
    event_dt = str((event_row or {}).get("event_dt") or "")
    for market in MARKETS:
        priced = [
            row
            for row in ranked
            if row.get(f"{market}_morning") is not None
        ]
        priced.sort(
            key=lambda row: (
                row[f"{market}_morning"],
                row["horse_number"],
            )
        )
        market_rank = {
            row["horse_number"]: index
            for index, row in enumerate(priced, 1)
        }
        for row in ranked:
            row[f"{market}_morning_rank"] = market_rank.get(
                row["horse_number"]
            )
    for row in ranked:
        row.pop("_win_row", None)
    return {
        "date": date,
        "venue": venue,
        "race_number": race_no,
        "event_dt": event_dt,
        "race_type": race_type_bucket(race_type_source),
        "field_size": len(ranked),
        "top1_top2_gap": round(top_gap, 6),
        "selections": ranked,
    }


def present_race_class(value: object) -> bool:
    return str(value or "").strip().lower() not in {
        "",
        "unknown",
        "n/a",
        "none",
    }


def load_snapshot_races(
    score_path: Path,
    finish_path: Path,
    markets: dict,
    *,
    score_key: str,
) -> tuple[list[dict], dict]:
    scores = json.loads(score_path.read_text(encoding="utf-8"))
    finishes = json.loads(finish_path.read_text(encoding="utf-8"))
    audit = defaultdict(int)
    races = []
    for meeting, meeting_rows in scores.items():
        date, venue = parse_meeting_identity(meeting)
        finish_meeting = finishes.get(meeting) or {}
        if not date or not venue:
            audit["invalid_meeting_identity"] += 1
            continue
        if not finish_meeting:
            audit["meeting_without_finish_map"] += 1
            continue
        for race_raw, horse_rows in meeting_rows.items():
            race_no = int(race_raw)
            finish_race = finish_meeting.get(str(race_no)) or {}
            aligned = []
            for horse_no_raw, source in horse_rows.items():
                audit["score_horses"] += 1
                horse_no = int(horse_no_raw)
                result = finish_race.get(str(horse_no))
                score = as_float(source.get(score_key))
                if not result or score is None:
                    audit["missing_result_or_score"] += 1
                    continue
                if normalize_name(result.get("name")) != normalize_name(source.get("name")):
                    audit["horse_name_mismatch"] += 1
                    continue
                finish = int(as_float(result.get("pos")) or 99)
                horse_name = str(source.get("name") or result.get("name") or "")
                aligned.append(
                    {
                        "horse_number": horse_no,
                        "horse_name": horse_name,
                        "score": score,
                        "finish": finish,
                    }
                )
            race = finalize_aligned_race(
                date=date,
                venue=venue,
                race_no=race_no,
                aligned=aligned,
                markets=markets,
                audit=audit,
            )
            if race:
                races.append(race)
    races.sort(
        key=lambda race: (
            race["date"],
            race["event_dt"],
            race["venue"],
            race["race_number"],
        )
    )
    audit["accepted_races"] = len(races)
    audit["accepted_horses"] = sum(len(race["selections"]) for race in races)
    for key in (
        "invalid_meeting_identity",
        "meeting_without_finish_map",
        "missing_result_or_score",
        "horse_name_mismatch",
        "win_unmatched",
        "place_unmatched",
        "win_outcome_mismatch",
        "rejected_race_alignment",
    ):
        audit.setdefault(key, 0)
    return races, dict(audit)


def load_runtime_dataset_races(
    dataset_path: Path,
    markets: dict,
) -> tuple[list[dict], dict]:
    """Load scores frozen by au_runtime_failure_audit."""
    payload = json.loads(dataset_path.read_text(encoding="utf-8"))
    audit = defaultdict(int)
    races = []
    for source_race in payload.get("races") or []:
        metadata = source_race.get("metadata") or {}
        date = str(metadata.get("date") or "")
        venue = normalize_venue(metadata.get("track"))
        race_no = int(as_float(metadata.get("race_number")) or 0)
        if not re.fullmatch(r"\d{4}-\d{2}-\d{2}", date) or not venue or not race_no:
            audit["invalid_meeting_identity"] += 1
            continue
        aligned = []
        for source in source_race.get("rows") or []:
            audit["score_horses"] += 1
            horse_no = int(as_float(source.get("horse_number")) or 0)
            horse_name = str(source.get("horse_name") or "")
            score = as_float(source.get("score"))
            finish = int(as_float(source.get("actual_pos")) or 99)
            if not horse_no or not normalize_name(horse_name) or score is None:
                audit["missing_result_or_score"] += 1
                continue
            aligned.append(
                {
                    "horse_number": horse_no,
                    "horse_name": horse_name,
                    "score": score,
                    "finish": finish,
                }
            )
        race = finalize_aligned_race(
            date=date,
            venue=venue,
            race_no=race_no,
            aligned=aligned,
            markets=markets,
            audit=audit,
            race_class=metadata.get("race_class"),
        )
        if race:
            races.append(race)
    races.sort(
        key=lambda race: (
            race["date"],
            race["event_dt"],
            race["venue"],
            race["race_number"],
        )
    )
    audit["accepted_races"] = len(races)
    audit["accepted_horses"] = sum(len(race["selections"]) for race in races)
    for key in (
        "invalid_meeting_identity",
        "missing_result_or_score",
        "win_unmatched",
        "place_unmatched",
        "win_outcome_mismatch",
        "rejected_race_alignment",
    ):
        audit.setdefault(key, 0)
    return races, dict(audit)


@dataclass(frozen=True)
class Strategy:
    market: str
    ranks: str
    execution: str
    min_morning_odds: float
    morning_market_top2: bool
    min_score_gap: float | None

    @property
    def id(self) -> str:
        gap = "none" if self.min_score_gap is None else f"{self.min_score_gap:g}"
        return (
            f"{self.market}:{self.ranks}:{self.execution}:"
            f"min{self.min_morning_odds:g}:"
            f"consensus{int(self.morning_market_top2)}:gap{gap}"
        )

    @property
    def complexity(self) -> int:
        return (
            int(self.min_morning_odds > 1.0)
            + int(self.morning_market_top2)
            + int(self.min_score_gap is not None)
        )


def strategy_grid() -> list[Strategy]:
    return [
        Strategy(market, ranks, execution, threshold, consensus, gap)
        for market in MARKETS
        for ranks in RANK_SCOPES
        for execution in EXECUTIONS
        for threshold in ODDS_THRESHOLDS
        for consensus in (False, True)
        for gap in GAP_THRESHOLDS
    ]


def _rank_indexes(scope: str) -> tuple[int, ...]:
    return {"top1": (0,), "top2": (1,), "both": (0, 1)}[scope]


def select_bets(
    races: list[dict],
    strategy: Strategy,
    *,
    dates: set[str] | None = None,
) -> list[dict]:
    bets = []
    for race in races:
        if dates is not None and race["date"] not in dates:
            continue
        if (
            strategy.min_score_gap is not None
            and race["top1_top2_gap"] < strategy.min_score_gap
        ):
            continue
        for index in _rank_indexes(strategy.ranks):
            if len(race["selections"]) <= index:
                continue
            row = race["selections"][index]
            morning = row.get(f"{strategy.market}_morning")
            odds = row.get(f"{strategy.market}_{strategy.execution}")
            won = row.get(f"{strategy.market}_won")
            if morning is None or odds is None or won is None:
                continue
            if float(morning) < strategy.min_morning_odds:
                continue
            if (
                strategy.morning_market_top2
                and (row.get(f"{strategy.market}_morning_rank") or 999) > 2
            ):
                continue
            bets.append(
                {
                    "date": race["date"],
                    "venue": race["venue"],
                    "race_number": race["race_number"],
                    "event_dt": race["event_dt"],
                    "market": strategy.market,
                    "model_rank": index + 1,
                    "horse_number": row["horse_number"],
                    "horse_name": row["horse_name"],
                    "odds": float(odds),
                    "morning_odds": float(morning),
                    "won": bool(won),
                    "field_size": race["field_size"],
                    "race_type": race["race_type"],
                    "score_gap": race["top1_top2_gap"],
                }
            )
    return bets


def longest_streak(values: Iterable[bool]) -> int:
    current = worst = 0
    for lost in values:
        current = current + 1 if lost else 0
        worst = max(worst, current)
    return worst


def settle_events(bets: list[dict], commission: float) -> list[dict]:
    grouped: dict[tuple, list[dict]] = defaultdict(list)
    for bet in bets:
        grouped[
            (
                bet["date"],
                bet["event_dt"],
                bet["venue"],
                bet["race_number"],
                bet["market"],
            )
        ].append(bet)
    events = []
    for key, event_bets in sorted(grouped.items()):
        gross = sum(
            (bet["odds"] - 1.0) if bet["won"] else -1.0
            for bet in event_bets
        )
        net = gross * (1.0 - commission) if gross > 0 else gross
        events.append(
            {
                "key": key,
                "bets": event_bets,
                "stake": float(len(event_bets)),
                "pnl": net,
            }
        )
    return events


def strategy_metrics(
    bets: list[dict],
    *,
    commission: float = COMMISSION,
    bootstrap: int = 0,
    seed: int = 730,
) -> dict:
    ordered = sorted(
        bets,
        key=lambda bet: (
            bet["date"],
            bet["event_dt"],
            bet["venue"],
            bet["race_number"],
            bet["model_rank"],
        ),
    )
    events = settle_events(ordered, commission)
    stake = float(len(ordered))
    pnl = sum(event["pnl"] for event in events)
    balance = peak = max_drawdown = 0.0
    for event in events:
        balance += event["pnl"]
        peak = max(peak, balance)
        max_drawdown = max(max_drawdown, peak - balance)
    ci = [0.0, 0.0]
    if bootstrap and events:
        rng = random.Random(seed)
        samples = []
        for _ in range(bootstrap):
            sample = rng.choices(events, k=len(events))
            sample_stake = sum(event["stake"] for event in sample)
            samples.append(
                100.0 * sum(event["pnl"] for event in sample) / sample_stake
            )
        samples.sort()
        ci = [
            round(samples[int(0.025 * len(samples))], 2),
            round(samples[int(0.975 * len(samples))], 2),
        ]
    return {
        "bets": len(ordered),
        "events": len(events),
        "wins": sum(bet["won"] for bet in ordered),
        "strike_pct": round(
            100.0 * sum(bet["won"] for bet in ordered) / max(1, len(ordered)),
            2,
        ),
        "stake": round(stake, 2),
        "pnl": round(pnl, 2),
        "roi_pct": round(100.0 * pnl / max(1.0, stake), 2),
        "average_odds": (
            round(mean(bet["odds"] for bet in ordered), 3)
            if ordered
            else None
        ),
        "max_drawdown_units": round(max_drawdown, 2),
        "max_drawdown_stake_pct": round(
            100.0 * max_drawdown / max(1.0, stake),
            2,
        ),
        "longest_losing_bet_streak": longest_streak(
            not bet["won"] for bet in ordered
        ),
        "longest_losing_event_streak": longest_streak(
            event["pnl"] < 0 for event in events
        ),
        "ci95_roi_pct": ci,
    }


def split_dates(races: list[dict]) -> dict[str, set[str]]:
    dates = sorted({race["date"] for race in races})
    if len(dates) < 5:
        return {
            "discovery": set(dates),
            "confirmation": set(),
            "terminal": set(),
        }
    discovery_end = max(1, int(len(dates) * 0.60))
    confirmation_end = max(discovery_end + 1, int(len(dates) * 0.80))
    confirmation_end = min(confirmation_end, len(dates) - 1)
    return {
        "discovery": set(dates[:discovery_end]),
        "confirmation": set(dates[discovery_end:confirmation_end]),
        "terminal": set(dates[confirmation_end:]),
    }


def _half_dates(dates: set[str]) -> tuple[set[str], set[str]]:
    ordered = sorted(dates)
    midpoint = max(1, len(ordered) // 2)
    return set(ordered[:midpoint]), set(ordered[midpoint:])


def discover_strategy(
    races: list[dict],
    candidates: list[Strategy],
    dates: set[str],
    *,
    market: str,
) -> tuple[Strategy | None, list[dict]]:
    first_dates, second_dates = _half_dates(dates)
    rows = []
    for candidate in candidates:
        if candidate.market != market:
            continue
        bets = select_bets(races, candidate, dates=dates)
        all_metrics = strategy_metrics(bets)
        first = strategy_metrics(
            select_bets(races, candidate, dates=first_dates)
        )
        second = strategy_metrics(
            select_bets(races, candidate, dates=second_dates)
        )
        if (
            all_metrics["bets"] < 80
            or first["bets"] < 25
            or second["bets"] < 25
        ):
            continue
        stability_pass = first["roi_pct"] >= 0 and second["roi_pct"] >= 0
        score = (
            all_metrics["roi_pct"]
            - 0.5 * all_metrics["max_drawdown_stake_pct"]
            - 1.5 * candidate.complexity
        )
        rows.append(
            {
                "strategy": candidate,
                "metrics": all_metrics,
                "first_half_roi_pct": first["roi_pct"],
                "second_half_roi_pct": second["roi_pct"],
                "stability_pass": stability_pass,
                "selection_score": round(score, 4),
            }
        )
    rows.sort(
        key=lambda row: (
            not row["stability_pass"],
            -row["selection_score"],
            row["strategy"].complexity,
            row["strategy"].id,
        )
    )
    chosen = next(
        (row["strategy"] for row in rows if row["stability_pass"]),
        None,
    )
    return chosen, rows


def odds_bucket(bet: dict) -> str:
    odds = bet["morning_odds"]
    if odds < 1.5:
        return "<1.5"
    if odds < 2.0:
        return "1.5-1.99"
    if odds < 2.5:
        return "2.0-2.49"
    if odds < 3.0:
        return "2.5-2.99"
    if odds < 4.0:
        return "3.0-3.99"
    if odds < 6.0:
        return "4.0-5.99"
    return "6.0+"


def field_bucket(bet: dict) -> str:
    return "1-8" if bet["field_size"] <= 8 else (
        "9-11" if bet["field_size"] <= 11 else "12+"
    )


def gap_bucket(bet: dict) -> str:
    gap = bet["score_gap"]
    if gap < 0.5:
        return "<0.5"
    if gap < 1.0:
        return "0.5-0.99"
    if gap < 2.0:
        return "1.0-1.99"
    return "2.0+"


def grouped_metrics(
    bets: list[dict],
    key_fn: Callable[[dict], str],
) -> dict:
    groups: dict[str, list[dict]] = defaultdict(list)
    for bet in bets:
        groups[key_fn(bet)].append(bet)
    return {
        key: strategy_metrics(rows)
        for key, rows in sorted(groups.items())
    }


def public_discovery(rows: list[dict], limit: int = 15) -> list[dict]:
    return [
        {
            "strategy": asdict(row["strategy"]),
            "strategy_id": row["strategy"].id,
            "metrics": row["metrics"],
            "first_half_roi_pct": row["first_half_roi_pct"],
            "second_half_roi_pct": row["second_half_roi_pct"],
            "stability_pass": row["stability_pass"],
            "selection_score": row["selection_score"],
        }
        for row in rows[:limit]
    ]


def evaluate_selected(
    races: list[dict],
    strategy: Strategy | None,
    partitions: dict[str, set[str]],
) -> dict | None:
    if strategy is None:
        return None
    split = {
        name: strategy_metrics(
            select_bets(races, strategy, dates=dates),
            bootstrap=3000,
            seed=730 + index,
        )
        for index, (name, dates) in enumerate(partitions.items())
    }
    confirmation = split["confirmation"]
    terminal = split["terminal"]
    confirmation_terminal_dates = (
        partitions["confirmation"] | partitions["terminal"]
    )
    confirmation_terminal = strategy_metrics(
        select_bets(
            races,
            strategy,
            dates=confirmation_terminal_dates,
        ),
        bootstrap=5000,
        seed=739,
    )
    promotion_pass = (
        confirmation["bets"] >= 50
        and terminal["bets"] >= 50
        and confirmation["roi_pct"] > 0
        and terminal["roi_pct"] > 0
        and confirmation_terminal["ci95_roi_pct"][0] > 0
    )
    all_bets = select_bets(races, strategy)
    return {
        "strategy": asdict(strategy),
        "strategy_id": strategy.id,
        "split": split,
        "confirmation_terminal": confirmation_terminal,
        "promotion_pass": promotion_pass,
        "all": strategy_metrics(all_bets, bootstrap=5000),
        "by_model_rank": grouped_metrics(
            all_bets,
            lambda bet: f"Top {bet['model_rank']}",
        ),
        "by_odds_range": grouped_metrics(all_bets, odds_bucket),
        "by_field_size": grouped_metrics(all_bets, field_bucket),
        "by_race_type": grouped_metrics(
            all_bets,
            lambda bet: bet["race_type"],
        ),
        "by_score_gap": grouped_metrics(all_bets, gap_bucket),
    }


def baseline_rows(
    races: list[dict],
    partitions: dict[str, set[str]],
) -> list[dict]:
    rows = []
    for market in MARKETS:
        for ranks in RANK_SCOPES:
            for execution in EXECUTIONS:
                strategy = Strategy(
                    market=market,
                    ranks=ranks,
                    execution=execution,
                    min_morning_odds=1.0,
                    morning_market_top2=False,
                    min_score_gap=None,
                )
                rows.append(
                    {
                        "strategy_id": strategy.id,
                        "strategy": asdict(strategy),
                        "all": strategy_metrics(
                            select_bets(races, strategy),
                            bootstrap=3000,
                        ),
                        "split": {
                            name: strategy_metrics(
                                select_bets(races, strategy, dates=dates)
                            )
                            for name, dates in partitions.items()
                        },
                    }
                )
    return rows


def render_markdown(report: dict) -> str:
    lines = [
        "# AU Wong Choi Betting Strategy Backtest",
        "",
        f"- Model snapshot: `{report['design']['model_version']}`",
        f"- Accepted races / horses: {report['dataset']['races']} / "
        f"{report['dataset']['horses']}",
        "- Decision price: morning WAP proxy；BSP只可作事後結算。",
        "- Betfair 5% commission按同一場、同一 market淨盈利計。",
        "",
        "## Baselines",
        "",
        "| Market | Picks | Execution | Bets | Strike | ROI | P&L | Max DD | Losing streak |",
        "|---|---|---|---:|---:|---:|---:|---:|---:|",
    ]
    for row in report["baselines"]:
        strategy = row["strategy"]
        metric = row["all"]
        lines.append(
            f"| {strategy['market']} | {strategy['ranks']} | "
            f"{strategy['execution']} | {metric['bets']} | "
            f"{metric['strike_pct']:.1f}% | {metric['roi_pct']:+.1f}% | "
            f"{metric['pnl']:+.1f} | {metric['max_drawdown_units']:.1f} | "
            f"{metric['longest_losing_bet_streak']} |"
        )
    lines.extend(["", "## Discovery-selected candidates", ""])
    for market in MARKETS:
        selected = report["selected"].get(market)
        if not selected:
            lines.append(f"- {market.upper()}: 冇 discovery candidate通過前後半正 ROI gate。")
            continue
        strategy = selected["strategy"]
        lines.append(
            f"### {market.upper()} — `{selected['strategy_id']}`"
        )
        lines.append("")
        lines.append(
            f"- Confirmation ROI: {selected['split']['confirmation']['roi_pct']:+.1f}% "
            f"({selected['split']['confirmation']['bets']} bets)"
        )
        lines.append(
            f"- Terminal ROI: {selected['split']['terminal']['roi_pct']:+.1f}% "
            f"({selected['split']['terminal']['bets']} bets)"
        )
        lines.append(
            f"- Combined untouched holdout 95% CI: "
            f"[{selected['confirmation_terminal']['ci95_roi_pct'][0]:+.1f}%, "
            f"{selected['confirmation_terminal']['ci95_roi_pct'][1]:+.1f}%]"
        )
        lines.append(
            f"- Promotion gate: **{'PASS' if selected['promotion_pass'] else 'FAIL'}**"
        )
        lines.append(
            f"- 規則：{strategy['ranks']}；morning odds ≥ "
            f"{strategy['min_morning_odds']}; execution={strategy['execution']}; "
            f"market consensus={strategy['morning_market_top2']}; "
            f"score gap ≥ {strategy['min_score_gap']}."
        )
        lines.append("")
    lines.extend(
        [
            "## Data alignment audit",
            "",
            "```json",
            json.dumps(report["dataset"]["alignment"], indent=2, sort_keys=True),
            "```",
            "",
            "任何 `horse_name_mismatch`、ambiguous market 或 WIN outcome mismatch "
            "都唔會靜默進入 ROI。",
        ]
    )
    return "\n".join(lines) + "\n"


def run_backtest(args: argparse.Namespace) -> dict:
    market_paths = sorted(args.betfair_dir.glob("dwbfpricesaus*.csv"))
    if not market_paths:
        raise SystemExit(f"No Betfair files found: {args.betfair_dir}")
    markets, market_audit = load_market_index(args.betfair_dir)
    if args.runtime_dataset:
        races, alignment = load_runtime_dataset_races(
            args.runtime_dataset,
            markets,
        )
        model_source = args.runtime_dataset
        model_source_label = "runtime_dataset"
    else:
        if not args.score_snapshot or not args.finish_map:
            raise SystemExit(
                "--score-snapshot and --finish-map are required unless "
                "--runtime-dataset is supplied."
            )
        races, alignment = load_snapshot_races(
            args.score_snapshot,
            args.finish_map,
            markets,
            score_key=args.score_key,
        )
        model_source = args.score_snapshot
        model_source_label = "score_snapshot"
    if not races:
        raise SystemExit("No aligned model races.")
    partitions = split_dates(races)
    candidates = strategy_grid()
    selected = {}
    discovery = {}
    for market in MARKETS:
        strategy, rows = discover_strategy(
            races,
            candidates,
            partitions["discovery"],
            market=market,
        )
        discovery[market] = public_discovery(rows)
        selected[market] = evaluate_selected(races, strategy, partitions)
    report = {
        "design": {
            "model_version": args.model_version,
            "score_key": args.score_key,
            "ranking_price_input": None,
            "decision_price": "morningwap",
            "settlement_prices": ["morningwap", "bsp"],
            "commission": COMMISSION,
            "selection_split": "60% discovery / 20% confirmation / 20% terminal by unique date",
            "promotion_gate": (
                "discovery halves non-negative; confirmation and terminal "
                "ROI positive with >=50 bets each; combined untouched-holdout "
                "bootstrap 95% ROI lower bound > 0"
            ),
            "candidate_count": len(candidates),
        },
        "sources": {
            model_source_label: source_fingerprint([model_source]),
            "betfair": source_fingerprint(market_paths),
        },
        "dataset": {
            "races": len(races),
            "horses": sum(len(race["selections"]) for race in races),
            "date_start": min(race["date"] for race in races),
            "date_end": max(race["date"] for race in races),
            "partition_dates": {
                name: sorted(dates)
                for name, dates in partitions.items()
            },
            "market_index": market_audit,
            "alignment": alignment,
        },
        "baselines": baseline_rows(races, partitions),
        "discovery_shortlist": discovery,
        "selected": selected,
    }
    if args.finish_map:
        report["sources"]["finish_map"] = source_fingerprint([args.finish_map])
    return report


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    model_source = parser.add_mutually_exclusive_group(required=True)
    model_source.add_argument("--score-snapshot", type=Path)
    model_source.add_argument("--runtime-dataset", type=Path)
    parser.add_argument("--finish-map", type=Path)
    parser.add_argument("--betfair-dir", type=Path, required=True)
    parser.add_argument("--score-key", default="old_ability")
    parser.add_argument("--model-version", required=True)
    parser.add_argument(
        "--output-json",
        type=Path,
        default=Path("/private/tmp/au_betting_strategy_backtest.json"),
    )
    parser.add_argument(
        "--output-md",
        type=Path,
        default=Path("/private/tmp/au_betting_strategy_backtest.md"),
    )
    args = parser.parse_args()
    report = run_backtest(args)
    args.output_json.parent.mkdir(parents=True, exist_ok=True)
    args.output_md.parent.mkdir(parents=True, exist_ok=True)
    args.output_json.write_text(
        json.dumps(report, indent=2),
        encoding="utf-8",
    )
    args.output_md.write_text(render_markdown(report), encoding="utf-8")
    print(render_markdown(report))
    print(f"JSON: {args.output_json}")
    print(f"Markdown: {args.output_md}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
